### ISSUE TITLE
新建文章中如果如果标题输入CUIThemeStore: No theme registered with id=0，保存之后会导致左侧文章导航打不开

### ISSUE THREAD

**Issue by lsmya** [getgridea/gridea#100]

**Comment by lsmya** [comment]
应该是由于CUIThemeStore: No之间的冒号引起的

**Comment by Suremotoo** [comment]
标题特殊符号解析问题已经在下个版本解决，请耐心等待下个版本发布。
问题同：   #72

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
