### ISSUE TITLE
关于编辑

### ISSUE THREAD

**Issue by gz222** [getgridea/gridea#101]
文章中用插入链接加的网址比如www.baidu.com怎么跳转出去，现在会提示404

**Comment by Suremotoo** [comment]
如果文章中的链接要在新窗口打开，请参考使用： 
```html  <a href="https://www.baidu.com/" target="_blank" >Baidu</a> ```
Markdown 目前的超链接语法只支持在当前页面打开。
您提示404应该是语法错误导致，如果不能正常解决问题，请尽量提供问题详情+截图。
