### ISSUE TITLE
feat: 新添加一个“仅编译成HTML”的按钮

### ISSUE THREAD

**Issue by WindowsRegedit** [getgridea/gridea#1012]
## 概述

在同步按钮旁边新添加一个“仅编译成HTML”的按钮

## 动机

<img width="415" alt="image" src="https://user-images.githubusercontent.com/90195560/173825006-5316fbde-2009-49d4-bc43-9991089eee5b.png">
如图所示，使用Gridea上传文件时常常会超时。并且即使上传未成功，也会清除output文件夹，导致无法上传。
(PS: 我的代理似乎会导致Gridea报错)
<img width="381" alt="image" src="https://user-images.githubusercontent.com/90195560/173825451-86103ebb-c65e-4b19-91f1-e01d11140a7f.png">

**Comment by LiarrDev** [comment]
`output` 文件夹不会自动删除呀，直接去 `output` 文件夹 `push` 就可以了
