### ISSUE TITLE
软件界面显示no data

### ISSUE THREAD

**Issue by dreamhomes** [getgridea/gridea#102]
早上打开软件，全部目录显示no data
![Snipaste_2019-05-12_11-48-19](https://user-images.githubusercontent.com/35626972/57577540-0e064680-74ac-11e9-9a57-749355c73f9e.png)

**Comment by dreamhomes** [comment]
在系统目录下更新源文件夹之后，其它界面正常显示， 但是文章页面还是不显示写过的文章

**Comment by EryouHao** [comment]
你看下现在的源文件夹（点击应用中：系统 -> 源文件夹）是哪个文件夹，那里是否有文章？

**Comment by edwardzjl** [comment]
我也遇到了类似的问题，之前用都是正常的，这两天才发现。

刚启动的时候配置界面都是空白的：
![config](https://user-images.githubusercontent.com/7287580/57600313-103fd200-758c-11e9-92f9-8723d857b36c.png)

这时文章界面显示 no data：
![no-data1](https://user-images.githubusercontent.com/7287580/57600319-13d35900-758c-11e9-86e9-3bdf33a31bff.png)

多点几次左边的分类后，配置界面会出现之前的配置，但是文章界面变成一片空白：
![no-data](https://user-images.githubusercontent.com/7287580/57600241-dcfd4300-758b-11e9-80da-3fe920d97a44.png)

家里台式和公司电脑都出现这个问题，都是 windows 系统，osx 的暂时还没看。

**Comment by dreamhomes** [comment]
通过对目录的分析和尝试, 发现了出现问题的原因: **目录或者文章标题中使用了非法字符, 例如 :**
### 解决方法
1. 在源路径下删除带有非法字符的博客文件. .md格式的 
2. 在系统选项选择博客源目录重新加载.

**Comment by edwardzjl** [comment]
> 通过对目录的分析和尝试, 发现了出现问题的原因: **目录或者文章标题中使用了非法字符, 例如 :**
> 
> ### 解决方法
> 1. 在源路径下删除带有非法字符的博客文件. .md格式的
> 2. 在系统选项选择博客源目录重新加载.

![posts](https://user-images.githubusercontent.com/7287580/57826675-e62e2000-77d6-11e9-8358-f61f3aee3adb.png)

可能我们的问题不太一样，我好像没有用到非法字符。

**Comment by edwardzjl** [comment]
今天在osx上试了一下，0.7.7版的可以用，0.8.0版也遇到了这个问题。

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)

**Comment by edwardzjl** [comment]
更新了0.8.1后问题依然出现，后来把源文件夹设置了一个新的（之前是在0.7.7的时候创建的），然后重新配置了一下，现在好了。
我猜测是版本更新的时候对配置文件的读取有些改变，读取老版本的配置文件出错造成的。具体没有仔细研究。

**Comment by whj768702** [comment]
mac 0.8.1还存在同样问题。
