### ISSUE TITLE
无法保存

### ISSUE THREAD

**Issue by MreAtKC** [getgridea/gridea#1023]
我在使用next主题时，无法保存自定义配置，点击保存键无反应。
不知道其他主题是否会有这个现象。

**Comment by mxd0123456** [comment]
兄弟，我连Next主题都用不了，你怎么用的，我一用next就渲染失败

**Comment by wjkcxs** [comment]
> 兄弟，我连Next主题都用不了，你怎么用的，我一用next就渲染失败

这就是个半成品，bug还多。
想要搭blog可以用hexo或typcho（动态）。
@dodola

**Comment by Tenqui1** [comment]
我在保存时显示成功，但是返回又是原样

**Comment by liveznz** [comment]
自定义的某个字段问题。我自制主题，加了个 "type": "picture-upload",字段。正常操作后，关掉软件，再打开会发现picture-upload是空的......这时候保存就失效了。
