### ISSUE TITLE
编辑文章添加更多多媒体文件

### ISSUE THREAD

**Issue by muze-page** [getgridea/gridea#104]
我希望能在博文中添加音乐多媒体，比如OSS的音乐链接、或者，网易云音乐的外链。
还要一些视频。

**Comment by gaoliang** [comment]
编辑器支持html渲染，可以参考下面这个文档，用原生html实现
[https://about.gitlab.com/handbook/product/technical-writing/markdown-guide/#videos](https://about.gitlab.com/handbook/product/technical-writing/markdown-guide/#videos)

例如插入 youtube 视频，可以用
```html
<figure class="video_container">
  <iframe src="https://www.youtube.com/embed/enMumwvLAug" frameborder="0" allowfullscreen="true"> </iframe>
</figure>
```

网易云音乐可以用官方的外链播放器插件, 比如
```
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=450 src="//music.163.com/outchain/player?type=1&id=38247&auto=1&height=430"></iframe>
```

**Comment by muze-page** [comment]
我进行了相关的尝试，失败了，
`<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=865531026&auto=0&height=66"></iframe>`


![Snipaste_2019-05-16_02-23-24](https://user-images.githubusercontent.com/36845206/57799424-9a04c080-7781-11e9-8502-813d59136189.png)

![Snipaste_2019-05-16_02-22-18](https://user-images.githubusercontent.com/36845206/57799391-88231d80-7781-11e9-9120-04e22fe47868.png)

**Comment by EryouHao** [comment]
可以看下浏览器控制台报错，多半是媒体问题
