### ISSUE TITLE
如何上传文件不会被Gridea同步后吞并

### ISSUE THREAD

**Issue by zhulinyv** [getgridea/gridea#1044]
在GitHub上传了文件，但Gridea同步成功后会将上传的文件删除，如何解决此问题，望解答。

**Comment by wherelse** [comment]
把需要上传的文件放到gridea的static文件夹下，就会被一起上传

**Comment by zhulinyv** [comment]
> 把需要上传的文件放到gridea的static文件夹下，就会被一起上传

了解了，谢谢。
