### ISSUE TITLE
检测远程连接正常，同步一直在转圈

### ISSUE THREAD

**Issue by iblogc** [getgridea/gridea#1061]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   windows 11   |
| 软件版本 |  0.9.3    |
| 主题名称 |  Notes    |

---

## 期望行为

同步成功

## 当前行为
检测远程连接正常，同步一直在转圈，昨晚同步了一晚上到早上还在转圈
![image](https://user-images.githubusercontent.com/3283023/199646362-a5513e82-4365-4f30-ae91-7689de9e57b1.png)

**Comment by iblogc** [comment]
发现是posts和post-images里的文件名有中文就会导致这个现象

**Comment by iblogc** [comment]
同步 Netlify 有这个问题，GitHub Pages 没有这问题，其它同步平台没试过。

**Comment by JunJie-Zhang-SZY** [comment]
是不是网速问题呢？我也有和你一样的情况

**Comment by JunJie-Zhang-SZY** [comment]
应该不是中文的问题，我这边就是初始化配置，一直同步失败。时好时坏

**Comment by iblogc** [comment]
@JunJie-Zhang-SZY 我的是中文问题，我测试只要把文件名中文改掉就可以同步 Netlify 成功

**Comment by iblogc** [comment]
@JunJie-Zhang-SZY 我现在是两种同步方案：
- 第一种：使用 Gridea 同步到 GitHub，再在 Netlify 上配置了自动从 GitHub 拉取最新文件部署，网络问题导致同步失败 > 切换 netlify-cli 同步方案
- 第二种：使用 Gridea 同步到 Netlify，会一直卡在同步中 > 切换 netlify-cli 同步方案

**netlify-cli 同步方案**：
*前提是一定要使用某个同步方式操作了 同步 ，这样 output 文件夹下才是根据最新源文件生成的最终静态网页文件*
- 直接去`output`目录，使用 Netlify 官方提供的 [netlify-cli](https://docs.netlify.com/cli/get-started/) 工具进行同步，netlify-cli 同步没遇到过失败

output 目录位置：
Windows: C:\Users\用户名\.gridea\output
macOS: /Users/用户名/.gridea/output

```
npm install netlify-cli -g // 同一台电脑首次需要安装 netlify-cli，请保证电脑有 node 环境
netlify login // 同一台电脑首次需要登录授权
netlify deploy --prod -d . // 在 output 目录下执行，上传 output 目录下的文件到 netlify
```

**Comment by iblogc** [comment]
@JunJie-Zhang-SZY 刚刚发现配置的代理端口错了，改了下之后 github 用代理同步 和 netlify 不用代理同步都非常顺畅了，没任何问题😂

**Comment by jurray-jiajun** [comment]
感谢🙏！同样的问题，netlify不用代理也一直转圈，用netlify-cli解决了。求问一下有没有修改gridea源代码的打算，让那个button可以如此正常work。

**Comment by jurray-jiajun** [comment]
> 感谢🙏！同样的问题，netlify不用代理也一直转圈，用netlify-cli解决了。求问一下有没有修改gridea源代码的打算，让那个button可以如此正常work。

发现netlify-cli跑了一次后gridea里的同步也好了，不用修改也不用手动cli了。再次感谢，您的分享十分有益！

**Comment by iblogc** [comment]
> > 感谢🙏！同样的问题，netlify不用代理也一直转圈，用netlify-cli解决了。求问一下有没有修改gridea源代码的打算，让那个button可以如此正常work。
> 
> 发现netlify-cli跑了一次后gridea里的同步也好了，不用修改也不用手动cli了。再次感谢，您的分享十分有益！

好久了，我已经忘了这具体是什么了😂能解决问题就好
