### ISSUE TITLE
sftp上传功能，不能使用别名及自定义端口功能

### ISSUE THREAD

**Issue by Zyx-A** [getgridea/gridea#1064]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   Deepin 20.7.1   |
| 软件版本 |    0.9.3  |
| 主题名称 |    Notes  |

---

## 期望行为

SFTP 能正常工作，能访问并上传站点文件

## 当前行为

为了安全考虑，SSH的端口已被修改为非22端口。
当我在server一栏，直接写主机名，不带端口时，测试链接时，Console提示：`"Connection ended unexpectedly by remote server"`
![截图_选择区域_20221108120407](https://user-images.githubusercontent.com/18498974/200473181-df1ae1d8-0f5a-4db1-9bbe-79433c704cc5.jpg)

当我在server一栏，直接写主机名，且带端口时，测试链接时，Console提示：`"sftp.connect: client-socket error. Address lookup failed for host localhost:10022 after 2 attempts"`
![截图_选择区域_20221108120619](https://user-images.githubusercontent.com/18498974/200473221-45a8c44f-a01b-42d6-8e0e-b88daab494b3.jpg)

当我在server一栏，写别名时，测试链接时，Console提示：`"sftp.connect: client-socket error. Address lookup failed for host gridea after 2 attempts"`
![截图_选择区域_20221108120934](https://user-images.githubusercontent.com/18498974/200473245-64820689-ce58-4a47-b3e3-98eb032d009c.jpg)
![截图_选择区域_20221108120730](https://user-images.githubusercontent.com/18498974/200473253-a9a03350-169e-441e-90de-f8bdd6561685.jpg)

**Comment by wherelse** [comment]
你的配置方法有误，你这里应该将域名填为`localhost:4000`， 端口Port填为`10022`，server填`localhost`

**Comment by Zyx-A** [comment]
谢谢大佬，按照方法解决了
