### ISSUE TITLE
显示不出主题样式

### ISSUE THREAD

**Issue by FishFishh** [getgridea/gridea#1069]
我用的 gridea+gitee pages，因为github pages已经用了hexo，想重新弄一个笔记本，本地能同步成功，但是访问gitee pages的时候显示不出主题样式，在gitee上重新部署也不成功， <a href="https://fish2140579318.gitee.io/" target="_blank">问题网站</a>，主题用的是breek。这种是因为什么qwq

**Comment by FishFishh** [comment]
> 你好github pages主题显示不对，有什么解决方法吗？renzituoboke.github.io

**Comment by YoloBird** [comment]
请问gitee咋配置的，我一直远程连接失败
