### ISSUE TITLE
feat: git仓库同步保留原有commits

### ISSUE THREAD

**Issue by YanDao0313** [getgridea/gridea#1076]
## 概述

在同步至目标git仓库时，保留先前的commits，而不是直接覆盖整个仓库

## 动机

发现给[仓库](https://github.com/YandaoGroup/daoblog.top)加上的Readme文件一旦同步就会被吞（因：[git仓库](https://github.com/YandaoGroup/daoblog.top)的commits全部被删除了），而且因为这个缘故，先前的版本也只能在vercel上查看，没有体现git可以多版本管理、迭代的优势

就像下面这种：

vercel上有我每次同步的版本的部署记录⬇️

![](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5115/20221126130533.png)

但是Github上空空如也⬇️

![](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5115/20221126130646.png)

## 详细解释

保留仓库原有commtis即可，而非覆盖仓库

> “如果这是一个小功能，你可以忽略这部分。”

**Comment by picpo** [comment]
附议

**Comment by LiarrDev** [comment]
这其实是 [v0.9.3](https://github.com/getgridea/gridea/releases/tag/v0.9.3) 带来的额外变更，如果需要的话可以用 [v0.9.2](https://github.com/getgridea/gridea/releases/tag/v0.9.2)

**Comment by YanDao0313** [comment]
got it.
![image](https://user-images.githubusercontent.com/90099234/209122976-c59f92d2-7364-4c9d-97cc-083ee814552b.png)
