### ISSUE TITLE
BUG:在编辑器内点击URL会打开一个网页，且没有关闭网页按钮

### ISSUE THREAD

**Issue by 425324438** [getgridea/gridea#109]
在编辑器内点击URL会打开一个网页，且没有关闭网页按钮。当http请求返回时，HTML会渲染整个编辑器，导致编辑器无法继续操作，只能点击关闭按钮，之前编辑的内容无法保存

**Comment by EryouHao** [comment]
下个版本已修复，请等待发版

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
