### ISSUE TITLE
能不能上面的状态栏一直保持在页面顶部

### ISSUE THREAD

**Issue by chiperman** [getgridea/gridea#111]
![1](https://user-images.githubusercontent.com/34889778/58141121-c4201c00-7c74-11e9-8bd9-375b156d0e9f.png)
这样我在写后面的时候也能快捷使用这些状态栏的图标。不然每次都得回到 最开始去点击按钮。

**Comment by EryouHao** [comment]
测试版已经置顶了，可等待新版发布
