### ISSUE TITLE
有完整的部署到sftp的教程吗？

### ISSUE THREAD

**Issue by YoloBird** [getgridea/gridea#1120]

**Comment by doutianye** [comment]
https://www.bilibili.com/video/BV1p5411u775/?spm_id_from=333.337.search-card.all.click&vd_source=4789c3b7d20d588d91386fa78cd3eb1a,也是困惑我的问题，在这里找到了答案

**Comment by doutianye** [comment]
最后放弃了，上传失败

**Comment by Azad-sl** [comment]
![image](https://github.com/getgridea/gridea/assets/85327306/cd538f01-4f6c-478c-a277-04e7696da1c5)
