### ISSUE TITLE
本地导出博客文件！！！

### ISSUE THREAD

**Issue by Burne00** [getgridea/gridea#1131]
发布渠道太过单一，而且同步功能也不太稳定，特别是国内的网络情况。

能否将静态文件本地导出，用户自己来手动上传到发布平台呢？

**Comment by wherelse** [comment]
https://github.com/wherelse/gridea/releases 可以试试我修改的这个版本

**Comment by LiarrDev** [comment]
目录在 `～/.gridea/output`，可以手动 push

**Comment by 2Jiao** [comment]
@LiarrDev 但是我看图片都是 localhost 的前缀，这种 push 上去找不到图片
