### ISSUE TITLE
无法配置仓库

### ISSUE THREAD

**Issue by shunconf** [getgridea/gridea#115]
检测结果 {message: "remote: 404 page not found↵fatal: repository 'http…/shunconf/shunconf.coding.me.git.git/' not found↵", success: false}message: "remote: 404 page not found↵fatal: repository 'https://dt_g0y47lkST:QkFmTXO9KNovVPbDOADIArc44eDaTv@git.coding.net/dt_g0y47lkST/https://git.dev.tencent.com/shunconf/shunconf.coding.me.git.git/' not found↵"success: false__proto__: Object
temp1
{message: "remote: 404 page not found↵fatal: repository 'http…/shunconf/shunconf.coding.me.git.git/' not found↵", success: false}

![Snipaste_2019-05-27_04-10-00](https://user-images.githubusercontent.com/25509201/58386649-5e95ac00-8035-11e9-83cc-86d4144301a9.png)

**Comment by EryouHao** [comment]
可以看下视频教程：https://gridea.dev/docs/，目测你的仓库写错了
