### ISSUE TITLE
feat: 希望Gridea会将html中的文本也当作MD编译

### ISSUE THREAD

**Issue by DavidJYL** [getgridea/gridea#1159]
## 概述

我希望 Gridea 会将 html 中的文本也当作 Markdown 编译，如果目前不能实现，我希望增加这个功能

例如：

```html
<p>
# A
**B**
</p>
```

我希望显示：

# A

**B**

而不是
\# A
\*\*B\*\*

## 动机

我需要在折叠块中使用 Markdown 语法

**Comment by LiarrDev** [comment]
这与 Gridea 无关，Markdown 本身就不支持此语法，你应当使用 HTML 实现此功能

**Comment by DavidJYL** [comment]
> 这与 Gridea 无关，Markdown 本身就不支持此语法，你应当使用 HTML 实现此功能

@LiarrDev 抱歉，我没听懂你的意思，请问你所说的“本身就不支持”的语法是指什么？

**Comment by LiarrDev** [comment]
> > 这与 Gridea 无关，Markdown 本身就不支持此语法，你应当使用 HTML 实现此功能
> 
> @LiarrDev 抱歉，我没听懂你的意思，请问你所说的“本身就不支持”的语法是指什么？

即你上面提到的例子：

```
<p>
# A
**B**
</p>
```

假如需要在 `<p>` 标签内显示 `**B**`，此处便会产生歧义，Markdown 无法理解你究竟是想显示一个加粗的 `B`，还是带星号的 `**B**`，所以如果你想显示为加粗的 `B` 应当使用 `<bold>B</bold>`

**Comment by DavidJYL** [comment]
> > > 这与 Gridea 无关，Markdown 本身就不支持此语法，你应当使用 HTML 实现此功能
> > 
> > 
> > @LiarrDev 抱歉，我没听懂你的意思，请问你所说的“本身就不支持”的语法是指什么？
> 
> 即你上面提到的例子：
> 
> ```
> <p>
> # A
> **B**
> </p>
> ```
> 
> 假如需要在 `<p>` 标签内显示 `**B**`，此处便会产生歧义，Markdown 无法理解你究竟是想显示一个加粗的 `B`，还是带星号的 `**B**`，所以如果你想显示为加粗的 `B` 应当使用 `<bold>B</bold>`

@LiarrDev 好吧，非常感谢

那么请问我又没有办法达到我的目的呢？
或者，如果我只能使用 `html`，我该怎么使用 `Katex` 呢？

谢谢！

**Comment by LiarrDev** [comment]
> > > > 这与 Gridea 无关，Markdown 本身就不支持此语法，你应当使用 HTML 实现此功能
> > > 
> > > 
> > > @LiarrDev 抱歉，我没听懂你的意思，请问你所说的“本身就不支持”的语法是指什么？
> > 
> > 
> > 即你上面提到的例子：
> > ```
> > <p>
> > # A
> > **B**
> > </p>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 假如需要在 `<p>` 标签内显示 `**B**`，此处便会产生歧义，Markdown 无法理解你究竟是想显示一个加粗的 `B`，还是带星号的 `**B**`，所以如果你想显示为加粗的 `B` 应当使用 `<bold>B</bold>`
> 
> @LiarrDev 好吧，非常感谢
> 
> 那么请问我又没有办法达到我的目的呢？ 或者，如果我只能使用 `html`，我该怎么使用 `Katex` 呢？
> 
> 谢谢！

可以交给主题来完成，修改本地的主题文件，引入对应的 JS 即可解析

**Comment by DavidJYL** [comment]
> 可以交给主题来完成，修改本地的主题文件，引入对应的 JS 即可解析

好的，非常感谢！
