### ISSUE TITLE
[功能优化] 文章排版问题汇总

### ISSUE THREAD

**Issue by EscapeLife** [getgridea/gridea#117]
### 1. 封面图片多次显示

- **问题描述**
  - 新建文章中如果不添加封面图，则没有图片展示及时图中有文章也是不会暂时的。但是如果添加的图片，会默认放置到文章的顶部，和之前的布局有影响，显示多张图片，如下图所示。
  - 如果去除第二张图片，则布局有点尴尬，因为需要先显示一部分文字在显示图片信息。

![image](https://user-images.githubusercontent.com/16237571/58393150-ed271f00-806f-11e9-98ff-742f413162df.png)

![image](https://user-images.githubusercontent.com/16237571/58393593-dd103f00-8071-11e9-84ed-3dd4ab3e3c84.png)

---

### 2. 摘要内容显示异常

- **问题描述**
  - 如果在文章摘要内容的部分有`Markdown`语法，则首页显示就会有问题。并不会忽略`Markdown`的语法，会原样显示，导致布局异常。

![image](https://user-images.githubusercontent.com/16237571/58393698-63c51c00-8072-11e9-89f0-c80c4fe1ee8f.png)

![image](https://user-images.githubusercontent.com/16237571/58393686-50b24c00-8072-11e9-88bd-157a24db3181.png)

---

### 3. 不支持网易云等第三方插件扩展

- **问题描述**
  - 想在文章中添加一段网易云的音乐，发现不发直接添加`html`的内容，不知道是否做了特殊处理呢？

![image](https://user-images.githubusercontent.com/16237571/58393805-ec43bc80-8072-11e9-9869-8cc746998295.png)

![image](https://user-images.githubusercontent.com/16237571/58393749-aab31180-8072-11e9-9d33-de3d8236852f.png)

**Comment by EscapeLife** [comment]
@EryouHao 需要你看看是否是问题，如果是问题是否需要修复？感谢

**Comment by EscapeLife** [comment]
@EryouHao 没有反馈吗？啧啧啧。。。

**Comment by EryouHao** [comment]
很抱歉很晚才回复您的消息。

1. 封面图是文章中展示一次的，这个是主题设置的，可自行修改主题进行配置。
2. 摘要内容目前主题是按照 html 格式解析的，可自行在摘要部分使用普通文本来写，因为若是不解析 Markdown，显示 ## 1. 个人简介 也不太美观不是？
3. 可嵌入 html

**Comment by EscapeLife** [comment]
OK👌 已收到
