### ISSUE TITLE
内容显示错乱

### ISSUE THREAD

**Issue by xiaoyangst** [getgridea/gridea#1171]
直接把我的markdown拷贝进去，居然有些地方给我乱搞，我怀疑Gridea的问题，错误渲染。

![image](https://github.com/user-attachments/assets/d811b34d-e0c9-4d89-b794-a2b06a1331af)
把我的字体渲染成标题，你牛逼

给我自动加下划线和加粗，你牛逼
![image](https://github.com/user-attachments/assets/75c40567-e4c4-4b01-829a-d9b47fc32c7e)

用gridea 越久，你会发现远离它不远了，没人维护就是这样的

**Comment by xuesheng896** [comment]
> 直接把我的markdown拷贝进去，居然有些地方给我乱搞，我怀疑Gridea的问题，错误渲染。
> 
> ![image](https://private-user-images.githubusercontent.com/96154468/354897199-d811b34d-e0c9-4d89-b794-a2b06a1331af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDM5MDksIm5iZiI6MTcyMzgwMzYwOSwicGF0aCI6Ii85NjE1NDQ2OC8zNTQ4OTcxOTktZDgxMWIzNGQtZTBjOS00ZDg5LWI3OTQtYTJiMDZhMTMzMWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEwMjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNTYwMGVmMGEyOGQzOWY3YmU1MWEwNWFjZTJkNGJkMGZkMmNmOWYyZjRhOTA0ZDg0Zjk2ZWMwYjNjMTdmYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E5B6Vw-eNCYCJqr9eEEu1QlRniRNBToQKyXGLbJGvGA) 把我的字体渲染成标题，你牛逼
> 
> 给我自动加下划线和加粗，你牛逼 ![image](https://private-user-images.githubusercontent.com/96154468/354897258-75c40567-e4c4-4b01-829a-d9b47fc32c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDM5MDksIm5iZiI6MTcyMzgwMzYwOSwicGF0aCI6Ii85NjE1NDQ2OC8zNTQ4OTcyNTgtNzVjNDA1NjctZTRjNC00YjAxLTgyOWEtZDliNDdmYzMyYzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEwMjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzRmM2Y0ODBjMjgyNDU1MjY2OTkyMmE5MDM3Yzg3OTgwMTY3ODA2MjQ1NDQ1ZTMwZDYzMjQ1ODYyY2VkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-49wJxvnMQUYs57tTDHeXjAvIj7H7GLctm1F591TB7s)
> 
> 用gridea 越久，你会发现远离它不远了，没人维护就是这样的

原来没人维护了吗？那么Hugo欢迎你🤣🤣🤣

**Comment by xiaoyangst** [comment]
> > 直接把我的markdown拷贝进去，居然有些地方给我乱搞，我怀疑Gridea的问题，错误渲染。
> > ![image](https://private-user-images.githubusercontent.com/96154468/354897199-d811b34d-e0c9-4d89-b794-a2b06a1331af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDM5MDksIm5iZiI6MTcyMzgwMzYwOSwicGF0aCI6Ii85NjE1NDQ2OC8zNTQ4OTcxOTktZDgxMWIzNGQtZTBjOS00ZDg5LWI3OTQtYTJiMDZhMTMzMWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEwMjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNTYwMGVmMGEyOGQzOWY3YmU1MWEwNWFjZTJkNGJkMGZkMmNmOWYyZjRhOTA0ZDg0Zjk2ZWMwYjNjMTdmYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E5B6Vw-eNCYCJqr9eEEu1QlRniRNBToQKyXGLbJGvGA) 把我的字体渲染成标题，你牛逼
> > 给我自动加下划线和加粗，你牛逼 ![image](https://private-user-images.githubusercontent.com/96154468/354897258-75c40567-e4c4-4b01-829a-d9b47fc32c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDM5MDksIm5iZiI6MTcyMzgwMzYwOSwicGF0aCI6Ii85NjE1NDQ2OC8zNTQ4OTcyNTgtNzVjNDA1NjctZTRjNC00YjAxLTgyOWEtZDliNDdmYzMyYzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEwMjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzRmM2Y0ODBjMjgyNDU1MjY2OTkyMmE5MDM3Yzg3OTgwMTY3ODA2MjQ1NDQ1ZTMwZDYzMjQ1ODYyY2VkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-49wJxvnMQUYs57tTDHeXjAvIj7H7GLctm1F591TB7s)
> > 用gridea 越久，你会发现远离它不远了，没人维护就是这样的
> 
> 原来没人维护了吗？那么Hugo欢迎你🤣🤣🤣

已经找到原因，和 Gridea没有关系，但我还是决定不再使用，而是用hexo作为主题，并且使用 hexo-client，命令上传更快。感谢gridea的陪伴，但是主题真的少。
