### ISSUE TITLE
配置同步成功后看到的页面和预览的不一样

### ISSUE THREAD

**Issue by mzhtech** [getgridea/gridea#1174]

**Comment by mzhtech** [comment]
![image](https://github.com/user-attachments/assets/ba8eb0dc-7f60-4411-b44d-1c83fbc65c45)

**Comment by mzhtech** [comment]
![image](https://github.com/user-attachments/assets/1441bedc-b429-41de-b02c-07630f554350)

**Comment by EryouHao** [comment]
我看已经正常了哈。

https://mzhtech.github.io/

**Comment by xianmovo** [comment]
有延迟
