### ISSUE TITLE
markdown 解析报错了

### ISSUE THREAD

**Issue by arronf2e** [getgridea/gridea#124]
```
<Image source={{'uri': 'https://xxxxx'}} style={{width:193, height: 110}} />
```

报错信息： 

[Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    "<Image source="+_s('uri': 'https://xxxxx')+" style="+_s(width:193, height: 110)+" />"

  Raw expression: <Image source={{'uri': 'https://xxxxx'}} style={{width:193, height: 110}} />

79 |  </ul>
80 |  <blockquote>
81 |  <p>&lt;Image source={{'uri': 'https://xxxxx'}} style={{width:193, height: 110}} /&gt;</p>
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
82 |  </blockquote>
83 |  

(found in <Root>)

**Comment by EryouHao** [comment]
不太清楚是哪里看到的这个报错信息，我测试了下是渲染成这个 
![image](https://user-images.githubusercontent.com/17328747/58529807-e551b100-820e-11e9-9ff2-7eb726a20578.png)
另外，图片标签如果用 html 写是 `<img src="" >`

而且，Gridea 目前没有提供 `_s` 这种函数
