### ISSUE TITLE
同样的问题，总是显示连接错误。点击 Edit -> Toggle Develope tools  查看后错误提示是：no such remote 'origin'

### ISSUE THREAD

**Issue by maomao-ying** [getgridea/gridea#127]
同样的问题，总是显示连接错误。点击 Edit -> Toggle Develope tools  查看后错误提示是：no such remote 'origin'

_Originally posted by @Raphael95 in https://github.com/getgridea/gridea/issues/30#issuecomment-496053655_

**Comment by maomao-ying** [comment]
同样的问题
![image](https://user-images.githubusercontent.com/10151723/58681891-1a8e0880-83a1-11e9-85ce-02ea93d21e11.png)

**Comment by EryouHao** [comment]
可参考视频教程进行配置检查：https://gridea.dev/docs/

**Comment by maomao-ying** [comment]
就是跟着视频教程做的，然后就一直连不上，需要我提供什么补充信息能帮助你更好的分析？

**Comment by EryouHao** [comment]
![image](https://user-images.githubusercontent.com/17328747/58684522-24b50480-83ab-11e9-8b77-b913623ea45c.png)
我看了下，你应该把你的仓库名改为 `maomao-ying.github.io` 因为你的用户名是 `maomao-ying`，然后 Gridea 中的配置也相应进行修改试试

**Comment by maomao-ying** [comment]
不行唉。。
![image](https://user-images.githubusercontent.com/10151723/58685436-54b1d700-83ae-11e9-9949-6ce73e42469e.png)

**Comment by maomao-ying** [comment]
我现在还遇到一个奇怪的事情，我刚截图的时候，是直接改的仓库名称，然后连接不上，但是可以访问这个仓库网站https://maomao-ying.github.io。
然后我想是不是直接改名字不行，我就删了重新创建了一个仓库，这时连这个网站都访问不上去了。

**Comment by maomao-ying** [comment]
你需要的话我可以把Token给你

**Comment by EryouHao** [comment]
可通过 QQ 群，找我 QQ，或 Twitter、Telegram 私聊我，帮你测试下

**Comment by muhiank** [comment]
您好，我也遇到了和樓上一樣的問題。我的系統是Ubuntu 18.04。具體如下：
我按照教程里設置了各項參數：

---

這是設定的Gridea各個參數
![2019-06-02 13-16-57 的屏幕截图](https://user-images.githubusercontent.com/21037016/58757131-ff560100-8538-11e9-9b56-121fb0e2df3f.png)

---

這是我的用戶名還有倉庫名等
![2019-06-02 13-15-44屏幕截图](https://user-images.githubusercontent.com/21037016/58757138-29a7be80-8539-11e9-989a-da3592defe76.png)


![2019-06-02 13-16-46 的屏幕截图](https://user-images.githubusercontent.com/21037016/58757139-2ad8eb80-8539-11e9-8aae-ad869f43afb6.png)

![2019-06-02 13-21-26 的屏幕截图](https://user-images.githubusercontent.com/21037016/58757149-5f4ca780-8539-11e9-8d86-9ed3e6014f2d.png)

---

當我設定好上面的值後，总是显示连接错误。点击 Edit -> Toggle Develope tools 查看后错误提示是：
```
{message: "fatal: 不是一个 git 仓库（或者直至挂载点 / 的任何父目录）↵停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。↵", success: false}
```
然後我初始化了git

```
git init Gridea
```

保存配置後再次嘗試鏈接，這個時候給出的錯誤就和樓上一樣：

```
{message: "fatal: 没有此远程 'origin'↵", success: false}
```

請教這是為什麼？ 弄了好久沒搞明白。

**Comment by muhiank** [comment]
@EryouHao

**Comment by maomao-ying** [comment]
@muhiank 你可以先 cd 到你文档中的 output 目录【/Users/XXXX/Documents/Gridea/output】，然后输入命令【git remote -v】看看有没有信息，如果没有就跟我一样了。

我当时是通过工具把Git上的仓库（就是你自己建的那个仓库）Clone本地，只是做了一个这个动作，然后就好了。

再在那个目录数据命令确认是否有信息，有了就好了。

**Comment by muhiank** [comment]
抱歉，我依然沒有成功鏈接上，但是我把系統切換到windows。安裝了windows版本之後，發現可以正常上傳。:sad: 。
把我的在ubuntu的嘗試鏈接過程複製如下，也有可能是我哪一步做錯了。。。嗚嗚
```
~/文档/Gridea/output$ git remote -v
```
沒有信息輸出。我試着向您說的那樣將網絡上的倉庫克隆到本地。
```
~/文档/Gridea$ git clone git@github.com:muhiank/muhiank.github.io.git
```
然後嘗試了以下在 `output` 文件下繼續輸入 `git remote -v` ，
結果依然沒有任何輸出信息。我以為可能是我不應該clone到這個目錄下，我試着把倉庫克隆到 `Gridea` 的上級目錄，也就是 `文檔` 目錄下，結果依然沒有任何輸出。

---

我登錄GitHub，發現：
![2019-06-03 22-22-20 的屏幕截图](https://user-images.githubusercontent.com/21037016/58811128-ceb5ba80-8651-11e9-920c-ea748b7ba65a.png)
我以為是本地和遠程沒有建立任何鏈接，我有嘗試着在本地配置了 `git`，
```
git config user.name "muhiank"
git config user.email "ai2472206007@yeah.net"
```

然後生成了本地的 `SSH` 並保存到 `GitHub` 上，回去再嘗試着那個命令，發現依然不行。。。
 
---

莫不是只有我這一個個例嗎？那樣的話太悲傷了吧。。。

**Comment by maomao-ying** [comment]
我只能说肯定是Git配置上的问题，你试着用带用户的方式Clone仓库
```
https://maomao-ying@github.com/getgridea/gridea.git
```
纯命令行的方式我不是很懂，你看看ubuntu下面有没有`Tower`这个软件
![image](https://user-images.githubusercontent.com/10151723/58846778-14569f80-86b3-11e9-8ce8-89ee06141c9e.png)
