### ISSUE TITLE
期待Linux版本

### ISSUE THREAD

**Issue by SunYanCN** [getgridea/gridea#131]
期待Linux版本

**Comment by Suremotoo** [comment]
Linux 版本已经上线了， 可在官网首页下载：https://gridea.dev/
或者在 https://github.com/getgridea/gridea/releases 找对应的安装包进行下载

**Comment by SunYanCN** [comment]
非常棒!我已经在用了!

**Comment by chocozhao** [comment]
请问Ubuntu下下载的是哪个安装包，我只发现gridea-0.8.1.tar.gz这个文件，但是我解压出来只有源码，请问我应该怎么使用？

**Comment by xianzhu21** [comment]
> 请问Ubuntu下下载的是哪个安装包，我只发现gridea-0.8.1.tar.gz这个文件，但是我解压出来只有源码，请问我应该怎么使用？

下载 AppImage 版本就可以。然后给执行权限。

```shell
sudo chmod +x gridea.AppImage
./gridea.AppImage
```
