### ISSUE TITLE
封面图裁剪问题

### ISSUE THREAD

**Issue by chiperman** [getgridea/gridea#133]
设置了封面图后，在文章内看图片是被裁剪过后的图片，能不能保持一致。
这是文章封面的图片
![Snipaste_2019-06-03_08-09-34](https://user-images.githubusercontent.com/34889778/58769181-177c5d80-85d7-11e9-89d1-2f3c50925bf3.png)
 这是文章内部的图片
![Snipaste_2019-06-03_08-09-20](https://user-images.githubusercontent.com/34889778/58769185-1c411180-85d7-11e9-8404-14bf6598b446.png)

**Comment by Suremotoo** [comment]
我这里测试是正常的， 如果您不是最新版的 Gridea，请先下载最新版的 Gridea 。
或者您将使用的主题更新至最新版，我这里看到您使用的是 notes 主题，您也可以手动下载安装该主题：https://github.com/getgridea/gridea-theme-notes
也可以按照以下操作执行试试：
1. 打开 Gridea 的源文件夹，进入 **themes** 文件夹，找到您使用的主题文件夹
2. 关闭 Gridea 程序，删除您使用的主题文件夹，重启 Gridea
