### ISSUE TITLE
Linux 0.8.0版本，链接及表情不能显示

### ISSUE THREAD

**Issue by wilkice** [getgridea/gridea#139]
我的原文是这个样子：
![Screenshot_20190606_000210](https://user-images.githubusercontent.com/35746578/58971979-1aea3180-87ef-11e9-97f2-b8634c7c3878.png)

在预览界面可以显示链接，但不能显示表情
![Screenshot_20190606_000249](https://user-images.githubusercontent.com/35746578/58971823-d363a580-87ee-11e9-8e65-73cfd0cdd6ae.png)

在发布的文章那里，链接不能正常显示，排版也出错了，表情依然无法显示
![Screenshot_20190606_000349](https://user-images.githubusercontent.com/35746578/58971923-027a1700-87ef-11e9-8d7f-99963f08d4d6.png)

将该段片段复制到github能正常显示
Reference:
https://www.reddit.com/r/kde/comments/90xb3x/kde_connect_useful_commands_compilation/
https://userbase.kde.org/KDE_Connect/Tutorials/Useful_commands
:smiley:

**客户端是 Linux Manjaro aur 下载的**

**Comment by EryouHao** [comment]
目前没有提供链接的自动识别链接的功能，链接可通过：
`[链接文本](链接地址)` 这样来实现
表情的话，我看您是直接输入字符的？可以试试粘贴表情
