### ISSUE TITLE
检测远程连接失败

### ISSUE THREAD

**Issue by sondercc** [getgridea/gridea#142]
失败原因：fatal: remote origin already exists.
这种怎么解决呢？

**Comment by sondercc** [comment]
这种情况通过本地git清除remote可以吗？但是我本地检测不到已经远程连接过的remote..是否需要再手动连一下呢？

**Comment by sondercc** [comment]
@EryouHao 您好，可以帮忙看一下吗？

**Comment by Sondergm** [comment]
已解决：
1、卸载Gridea，删除相关配置文件夹，重新安装Gridea。
2、卸载Git（不确定需不需要进行这一步）。
3、重新配置，远程连接。

**Comment by EryouHao** [comment]
> 失败原因：fatal: remote origin already exists.
> 这种怎么解决呢？

可以试试将 output 文件夹中的 `.git/` 文件夹删除，然后重新进行远程连接检测试试呢

**Comment by Sondergm** [comment]
> > 失败原因：fatal: remote origin already exists.
> > 这种怎么解决呢？
> 
> 可以试试将 output 文件夹中的 `.git/` 文件夹删除，然后重新进行远程连接检测试试呢

已经解决了！多谢！
