### ISSUE TITLE
希望增加快速访问博客功能

### ISSUE THREAD

**Issue by UserNameZjw** [getgridea/gridea#147]
一般同步之后，大家可能都会去访问实际线上的站点，确认一下是否同步成功，而每一次，都需要打开浏览器，手输站点。
希望能增加一个快速打开线上站点的功能。
感谢这么好的产品

**Comment by EryouHao** [comment]
下个版本更新

**Comment by EryouHao** [comment]
已添加，请下载最新版享用

**Comment by UserNameZjw** [comment]
好像更新之后，本地的md文档丢失？
