### ISSUE TITLE
BUG-发布到网页上看不到表格

### ISSUE THREAD

**Issue by ottopan** [getgridea/gridea#149]
![image](https://user-images.githubusercontent.com/18224971/59434484-34f2c800-8e1e-11e9-8dc1-6e78929d92de.png)
![image](https://user-images.githubusercontent.com/18224971/59434493-3b813f80-8e1e-11e9-8b4d-bb22b80e5d62.png)
1.预览能看到表格,但是发布不是表格
2.链接不能点击

**Comment by ottopan** [comment]
网页链接:https://ottopan.github.io/post/bao-ke-meng-zi-liao-ku-chi-xu-geng-xin-ing/

**Comment by EryouHao** [comment]
我看您的另一篇文章已经显示正常了？请检查一下格式
![image](https://user-images.githubusercontent.com/17328747/59477872-b2075700-8e89-11e9-8864-576c70c12de2.png)

**Comment by ottopan** [comment]
那个可以的，我用的不是markdown语句，而是html的table标签，所以问题还是存在的，我在编辑器里面预览没问题，但是网页上出现问题，这过程发生了什么

**Comment by ottopan** [comment]
这么忙的吗,解决了吗?

**Comment by EryouHao** [comment]
很抱歉回复地过晚。因为之前版本的编辑器内预览和实际生成时的预览用的不是一个渲染引擎，所以会有差异，目前已统一，可以重新试试，感谢支持。🙏
