### ISSUE TITLE
无法同步进子目录

### ISSUE THREAD

**Issue by Errrneist** [getgridea/gridea#152]
（不知道是因为我没找到这个选项还是怎么的）我无法把它同步到github pages的一个子目录去（例如`https://errrneist.github.io/pages/`）第一次同步直接覆盖了我的repo……幸亏有备份不然心态就炸了。我在域名一栏写的是`https://errrneist.github.io/pages/`但是不仅没有生成子目录反而覆盖了原repo以及css加载不出来，必须要写`https://errrneist.github.io`才可以正确加载CSS。请问如何才能让它同步进一个子目录呢？

**Comment by EryouHao** [comment]
目前不支持同步到子目录，建议您可以另外建一个仓库用来放博客，比如 `blog`
