### ISSUE TITLE
【反馈】远程连接一直失败，因为本地端口原因

### ISSUE THREAD

**Issue by Hydra92** [getgridea/gridea#158]
### 在远程连接过程中，一直失败。如下：
![image](https://user-images.githubusercontent.com/36786159/59624042-575f4b00-9168-11e9-95b9-c6ef8e0be6be.png)
我注意到是本地端口12345的原因，这是我SSR的端口，当我开启SSR客户端时，远程连接成功，关闭则不成功。
Windows系统并未开启代理，Gridea为什么会使用这个端口？
后续我更改了SSR的端口，Gridea仍然报上述错误，所以我想请问这是什么原因

**Comment by EryouHao** [comment]
Gridea 目前未使用端口，估计是 SSR 配置导致连接 github 的网络不通的原因
