### ISSUE TITLE
mweb的文章如何导入？

### ISSUE THREAD

**Issue by andyhuai** [getgridea/gridea#162]
之前的博客使用mweb进行管理发布的，要转移到这里，貌似很麻烦
mweb的markdown文件没有头信息，不知道有什么办法没

**Comment by EryouHao** [comment]
目前的迁移需要手动加一下头信息，或复制粘贴到Gridea 中

**Comment by andyhuai** [comment]
@EryouHao 目前发现一个曲线路径，
mweb可以导入到 雀语，然后雀语导出到hexo，在拷贝到gridea，
当然，这是猜想，还没有实施，等有空了试试。

不然文章太多了，一个一个的复制，猴年马月去了

**Comment by EryouHao** [comment]
”道路千万条，安全第一条“ 记得备份 😂，不过能到 Hexo 了，就能到 Gridea 了
