### ISSUE TITLE
文章内链接没有正确渲染

### ISSUE THREAD

**Issue by liubiantao** [getgridea/gridea#166]
![image](https://user-images.githubusercontent.com/3268218/59825117-a9b98b00-9365-11e9-8748-64ca8dd2d1fe.png)

![image](https://user-images.githubusercontent.com/3268218/59825098-a1f9e680-9365-11e9-87ee-9db7da941c0f.png)

**Comment by joinmouse** [comment]
这个正确渲染了啊，编辑中最下面中括号的内容是显示内容[www.baidu.com]，小括号的内容是跳转地址呀。

**Comment by liubiantao** [comment]
@joinmouse 第二个是作为对比, 第一个没有正确渲染.

[]()这种语法一般都是为了改变链接名字的时候才用的, 比如

[百度](www.baidu.com)

一般情况只需要写链接就行, 比如

www.baidu.com

github issue 就可以正确渲染上面这句, 我用过的所有编辑器, 不管是mardkown还是非markdown的, 也都可以正确渲染

**Comment by joinmouse** [comment]
我理解你的意思了，你是想表达你输入`www.baidu.com` markdown语法会检测到这是一个a链接是吧

**Comment by joinmouse** [comment]
你好，请问你的版本是多少？我刚在最新的版本(v0.81)上测试了一下，你说的这种方式也是Ok的

![捕获](https://user-images.githubusercontent.com/18349016/59896049-8cde8f80-9419-11e9-98e0-951813830ffd.PNG)

![image](https://user-images.githubusercontent.com/18349016/59896035-7e907380-9419-11e9-9307-3798780d4643.png)

**Comment by liubiantao** [comment]
v0.81

![image](https://user-images.githubusercontent.com/3268218/59897137-dc26bf00-941d-11e9-967a-c221f6fefbe2.png)

看起来跟主题无关

![image](https://user-images.githubusercontent.com/3268218/59897222-3f185600-941e-11e9-854e-7a7c1aeec3cc.png)

**Comment by LiarrDev** [comment]
Gridea 似乎不是采用 Github 所使用的 [GFM](https://help.github.com/en/categories/writing-on-github)语法，可能因为这个原因有些出入

**Comment by liubiantao** [comment]
@LiarrDev 是个 bug, 你看楼上就正确渲染了
https://github.com/getgridea/gridea/issues/166#issuecomment-504277551
![](https://user-images.githubusercontent.com/18349016/59896035-7e907380-9419-11e9-9307-3798780d4643.png)

**Comment by EryouHao** [comment]
暂不支持链接的自动识别，可换用 `[]()` 来写
