### ISSUE TITLE
竖的图片会变成横的

### ISSUE THREAD

**Issue by lemonNoNioi** [getgridea/gridea#170]
使用的是simple主题
上传的图片如果是竖的会横过来，但是在新建标签页中打开图片是正常的
不知如何解决

**Comment by LiarrDev** [comment]
有可能是图片问题，以前在微信公众号上也遇到过相似的问题，可以通过使用图片编辑工具（如：Photoshop）把图片另存为副本解决

**Comment by EryouHao** [comment]
暂时没有遇到这种情况，可参考 @LiarrDev 提供的方法
