### ISSUE TITLE
所有数据和设置都消失

### ISSUE THREAD

**Issue by pipanyuwuqi** [getgridea/gridea#171]
设置源文件夹，点保存后就消失。以前写的文章都不能显示，配置等也不显示

**Comment by pipanyuwuqi** [comment]
文章和菜单都是No data，标签是空白，其他都是空，怎么查看错误信息，还请你指导

**Comment by Suremotoo** [comment]
> 设置源文件夹，点保存后就消失。以前写的文章都不能显示，配置等也不显示

新设置的源文件夹不要带有中文或者特殊字符。

**Comment by pipanyuwuqi** [comment]
> > 设置源文件夹，点保存后就消失。以前写的文章都不能显示，配置等也不显示
> 
> 新设置的源文件夹不要带有中文或者特殊字符。

无效，放在F:\blog，选取保存后没反应，不显示

**Comment by pipanyuwuqi** [comment]
换盘后，自动恢复到默认的文档文件夹，且更换保存后，切换到别的页面再切换回来，自动到默认的文件夹

**Comment by flybiubiu** [comment]
我也出现了同样的问题 mac崩了重启了下全空白  原路径无法选中

**Comment by Suremotoo** [comment]
出现问题的朋友，如果你们拷贝了其他的 md 文件，比如：从hugo、hexo 的文章源文件移动到gridea的目录汇总，这些md 文件，需要调整 title 字段。

如果是其他的操作，可以提供下自己在之前做了什么操作，方便大家快速定位问题根源。

**Comment by txSangyj** [comment]
posts下不能有文件夹

**Comment by Hicoder18** [comment]
昨天对主题作了修改，添加了回到顶部代码。添加了Adsense、百度统计脚本。昨天Gridea也反复关闭打开过好几次，没有任何问题。然后今天开机，放置文件的盘被系统修复了一下，然后打开Gridea 配置、文章等所有都不显示。换个盘新建，然后再复制原来的配置文件，依然空白。

**Comment by Hicoder18** [comment]
解决：不要直接拷贝配置文件，复制粘贴代码就能回复配置数据

**Comment by Hicoder18** [comment]
> 
> 
> 解决：不要直接拷贝配置文件，复制粘贴代码就能回复配置数据

其他配置文件也不能直接拷贝，文章可以直接拷贝
