### ISSUE TITLE
希望每一个板块有不一样的头像

### ISSUE THREAD

**Issue by FunkyPantsSa** [getgridea/gridea#174]
在不同的页面有不一样的头像，例如在首页有不一样的头像，当我切换到关于页面的时候也会拥有一个不一样的头像界面，这样可以方便自定义一些。或者增加一个可以自定义的选项。

**Comment by EryouHao** [comment]
这个可能不会加入到 Gridea 中，可以暂时通过写 HTML 在关于页面的文章正文处写单独的头像。将来可能会考虑区分 site avatar 和 author avatar 的区分。

**Comment by FunkyPantsSa** [comment]
我通过自定义每页的单独的头像，在我同步的时候还是会恢复的吗？这个有办法支持一下吗?

**Comment by EryouHao** [comment]
若是在主题文件（ejs）中修改的同步时不会恢复

**Comment by FunkyPantsSa** [comment]
好的，我试试
