### ISSUE TITLE
建议增加 文章分类 categories

### ISSUE THREAD

**Issue by deviljinc** [getgridea/gridea#175]
建议增加 文章分类 categories
比如 某几篇文章可以设置在同一个分类下
一级分类 二级分类 类似于 NexT 的 categories

**Comment by EryouHao** [comment]
这个可能暂时不会考虑，Gridea 有意将分类弱化，然后使用标签来进行分类，一般情况下够用了，若有两级的话，某些情况下会陷入“分类纠结”

**Comment by PaIn22152** [comment]
同建议增加 categoriese，毕竟tag和categories还是有一定区别的。
