### ISSUE TITLE
Markdown 插入链接不能在末尾注解？

### ISSUE THREAD

**Issue by LiarrDev** [getgridea/gridea#177]
我之前常用的写法是：

```Markdown
文章正文内容 1。
![图片1][1]
文章正文内容 2。
![图片2][2]
文章正文内容 3，[链接][3]。

  [1]: URL_1
  [2]: URL_2
  [3]: URL_3
```

但是该方法在 Gridea 客户端预览是没问题的，但是生成网站后会出现文末链接以文字形式展示出来，而文章内图片和链接都不能正常显示。

当前使用 Gridea 版本为 V0.8.1，主题为 Simple。

**Comment by EryouHao** [comment]
下个版本将支持

**Comment by EryouHao** [comment]
已更新，请下载最新版使用

**Comment by LiarrDev** [comment]
> 已更新，请下载最新版使用

刚试了一下，似乎依然不行。

Gridea V0.8.2，主题 Simple 1.0.0。
