### ISSUE TITLE
建议摘要不在正文显示或控制间距

### ISSUE THREAD

**Issue by LiarrDev** [getgridea/gridea#178]
个人认为摘要是对文章的综述或者对关键内容的提炼，当前摘要在正文中的样式与正文无异，感觉实际上就是正文的第一段，似乎并不符合摘要的本质，建议可以适当进行调整，或允许用户自己设定摘要是否在正文中显示。

**Comment by EryouHao** [comment]
这个可自行修改主题或提 PR 到对应的主题仓库，然后进行自定义配置支持，感谢支持🙏
