### ISSUE TITLE
使用markdown编写文档中有user、username、csrf_token渲染失败

### ISSUE THREAD

**Issue by mrpingan** [getgridea/gridea#179]
`Property or method "csrf_token" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.`

**Comment by mrpingan** [comment]
![image](https://user-images.githubusercontent.com/29201935/60116792-53a47780-97ab-11e9-9862-e2b7a33fd2ee.png)
在markdown中使用的是user、`{{ user.username }}`、`{{ csrf_token }}`

**Comment by EryouHao** [comment]
请提供一下在Markdown 中写的内容？看上去像是在 Markdown 文档中写了 Vue 代码？

**Comment by mrpingan** [comment]
# `context_processors`
从字面上理解为上下文，会将请求对象作为参数并以字典的方式合并到context中返回。比如，使用`render`函数的时候，就需要返回context，有了`context_processors`,就可以不用再去给模板传递过多的参数。在默认生成的配置文件`settings.py`中，默认模板引擎包含以下上下文处理器：
```python
[
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
]

```

除此之外，请求上下文默认开启`django.template.context_processors.csrf`，这是为了安全考虑，而且已经硬编码了，不能在`context_processors`中关闭。这就是为什么我们可以在模板中直接使用 `{{ csrf_token }}`的原因

每一个处理器有顺序。这意味着，如果一个处理器添加了一个变量到上下文，第二个处理器也添加了一个同名的变量到上下文，这样，第二个添加的变量的值会覆盖第一个。

## 内建的模板上下文处理器
### django.contrib.auth.context_processors.auth
如果这个处理器开启了，每一个请求上下文都将下面的变量：

- **user** 

当前登陆的user对象，或者一个匿名user对象。可以在模板中通过 **{{ user.username }}**调用
- `perms`

当前登陆用户的所有实例。可以在模板中通过`{{ perms.models_name.permission_name }}`调用

### django.template.context_processors.debug
如果这个选项开启了，每一个请求上下文都将包含下面两个变量。但是只有你的`DEBUG`设置为`True`,而且请求的IP地址（`request.META['REMOTE_ADDR']`）在`INTERNAL_IPS`设置的列表中：

- debug 

可以使用这个变量来测试是否你正处于`DEBUG`模式
- sql_queries

一个`{'sql': ..., 'time': ...}`的字典，展示了当前请求的每一个SQL以及执行时间，Django有一个swagger插件可以。


### django.template.context_processors.i18n
这个是国际化的一个组件。开启后，在模板中将可以使用一下变量

- LANGUAGES

当前的`LANGUAGES`设置
- LANGUAGE_BIDI
- LANGUAGE_CODE



### django.template.context_processors.media
开启后，每一个请求上下文将包含一个`MEDIA_URL`变量，可以在模板中提供`MEDIA_URL`的值
- MEDIA_URL

### django.template.context_processors.static
开启后，可以在模板中使用 `STATIC_URL`变量，可以在模板中提供`STATIC_URL`的在`setttings.py`中的值，
- STATIC_URL

### django.template.context_processors.csrf
这个处理器提供了**csrf_token**模板tag需要的token，用户避免跨站请求攻击

### django.template.context_processors.request
这个处理器开启后，每一个处理器上下文都将包含一个`request`变量，就是当前的`HttpRequest`
- request

### django.template.context_processors.tz
这个处理器开启后，每一个请求上下文都将包含一个`TIME_ZONE`变量，提供当前的时区

### django.contrib.messages.context_processors.messages
这个处理器开启后，每一个请求上下文都将包含下面两个变量
- messages 

通过django的消息框架设置的messages的列表

- DEFAULT_MESSAGE_LEVELS

一组消息级别名称到其数值的映射

Level Constant|Value
---|---
DEBUG|10
INFO	|20
SUCCESS	|25
WARNING	|30
ERROR|40

**Comment by mrpingan** [comment]
[md.txt](https://github.com/getgridea/gridea/files/3328752/md.txt)

**Comment by mrpingan** [comment]
> 请提供一下在Markdown 中写的内容？看上去像是在 Markdown 文档中写了 Vue 代码？

你好，是我的md写的格式不对么

**Comment by EryouHao** [comment]
很抱歉回复地较晚。

这是由于 simple 主题中使用了 vue.js，而  `{{ }}` 是 vue.js 中的语法，所以报错了，暂时可修改一下进行处理，或者换用其他主题
