### ISSUE TITLE
加入封面图床错误之后整个配置全部消失

### ISSUE THREAD

**Issue by ianchang0822** [getgridea/gridea#183]
![image](https://user-images.githubusercontent.com/44132083/60197467-017a5980-9872-11e9-94d2-c1e44461f6a0.png)
![image](https://user-images.githubusercontent.com/44132083/60197489-0b03c180-9872-11e9-96e0-6ebda7d63a41.png)
整个配置文件都找不到，我在封面图片那里想用图床，但是我加了是markdown格式的图床，上传之后，再次打开app整个所有文章，主题列表都消失了。既是我点击原来的保存也没有办法找到。

**Comment by EryouHao** [comment]
图床是怎么用的？点击源文件夹到博客的源文件夹，点保存，文章不会显示回来吗？

**Comment by ianchang0822** [comment]
图床使用腾讯云的cos生成链接后我把markdown格式的链接（也就是前面加了![]）点击同步按钮。然后导致整个软件无法找到文件配置。我在源文件重新点击保存之后，依然无法找到。重新退出软件，重新安装都无法找到目标文件夹。必须删除document文件夹内原有的gridea，才可以重新找到。

**Comment by ianchang0822** [comment]
我重新复现了一下问题，加入链接应该不是导致问题的原因，但是一但我将源文件夹修改为其他文件夹，再修改为原文件夹，就无法识别。mac系统。
![image](https://user-images.githubusercontent.com/44132083/60233542-4e424c80-98d3-11e9-9ef4-2f4ff8edc45b.png)
我修改为这样的文件夹地址是正确的么？

**Comment by EryouHao** [comment]
修改源文件夹通过点击右侧的文件夹图标来切换就可以
