### ISSUE TITLE
[bug]win版预览路径错误

### ISSUE THREAD

**Issue by HeartFireCN** [getgridea/gridea#185]
win版 预览-归档路径,应为`file:///C:/Users/95279/Documents/Gridea/output/archives/index.html`,实际上为`file:///C:/archives`

**Comment by hhy06** [comment]
ditto 

而且之前一直正常， 突然出现这个错误。 以后就再也无法改回去了 哪怕把post文件夹都删掉，重新生成的也是错误的预览路径

**Comment by EryouHao** [comment]
暂时可修改下菜单设置，下个版本预览功能会增强体验，敬请期待
