### ISSUE TITLE
[bug]多设备同步功能:逻辑错误 提示不完善

### ISSUE THREAD

**Issue by HeartFireCN** [getgridea/gridea#188]
在未使用onedrive的情况下,

公司电脑a发布一篇文章x,
回到家里电脑b 点"同步",文章x会自动从github上删除!
------------------------------------------------------
这是一个逻辑错误,没有进行本地和github不同对比,直接粗暴的将本地push到github,且无提示信息

**Comment by EryouHao** [comment]
同步是强制同步的，如果没有进行多设备同步，则会使用最新的同步。

请问同步之前，有在本地预览一下文章有没有吗？可以再用电脑 a 同步到 github 上即可。

> 提示信息确实是可以优化的点，非逻辑错误

**Comment by ScnuWang** [comment]
如何进行多设备之间的同步？

**Comment by EryouHao** [comment]
> 如何进行多设备之间的同步？

@ScnuWang https://gridea.dev/docs/faq.html
