### ISSUE TITLE
mac端点击同步，软件未响应

### ISSUE THREAD

**Issue by VincentJ1989** [getgridea/gridea#194]
版本：0.8.1
场景：按照bilibili的视频，在测试同步时，点击软件直接未响应了
bilibli的链接：https://www.bilibili.com/video/av54011033

**Comment by VincentJ1989** [comment]
放着不管，后面又可以了。

**Comment by zuotsi** [comment]
我的直接卡死

**Comment by VincentJ1989** [comment]
@zuotsi 点击同步，啥也不动，卡死也别管，我之前也是那样，直接未响应，mac的cpu直接满，等着就行啦

**Comment by zuotsi** [comment]
忘记说了，几次之后还是不行！
