### ISSUE TITLE
http转https后资源加载失败

### ISSUE THREAD

**Issue by McQueenMI4** [getgridea/gridea#196]
http转https后资源加载失败
http 页面资源加载正常
https 加载失败
但是在https下点击文章提示证书问题 然后会跳转到http页面
求解决

**Comment by McQueenMI4** [comment]
https://mcqueenmi4.top

**Comment by zjs1224522500** [comment]
问题+1.
https://blog.shunzi.tech

**Comment by EryouHao** [comment]
> 问题+1.
> https://blog.shunzi.tech

@McQueenMI4  @zjs1224522500 如果有自定义域名的话，可以将域名配置写成自己的自定义域名试试，比如：`https://blog.shunzi.tech`

**Comment by zjs1224522500** [comment]
@McQueenMI4  Fixed! Thanks a lot!

**Comment by McQueenMI4** [comment]
> @McQueenMI4 Fixed! Thanks a lot!

Fixed ？？？

**Comment by McQueenMI4** [comment]
> > 问题+1.
> > https://blog.shunzi.tech
> 
> @McQueenMI4 @zjs1224522500 如果有自定义域名的话，可以将域名配置写成自己的自定义域名试试，比如：`https://blog.shunzi.tech`

问题解决失败

**Comment by zjs1224522500** [comment]
> > @McQueenMI4 Fixed! Thanks a lot!
> 
> Fixed ？？？

你看我的发的地址，https的。我改的域名配置，没改CNAME

**Comment by McQueenMI4** [comment]
> > > @McQueenMI4 Fixed! Thanks a lot!
> > 
> > 
> > Fixed ？？？
> 
> 你看我的发的地址，https的。我改的域名配置，没改CNAME

改成什么样子 https

**Comment by zjs1224522500** [comment]
> > > > @McQueenMI4 Fixed! Thanks a lot!
> > > 
> > > 
> > > Fixed ？？？
> > 
> > 
> > 你看我的发的地址，https的。我改的域名配置，没改CNAME
> 
> 改成什么样子 https

把域名配置改成：    https://你的域名 
作者说的挺清楚了

**Comment by McQueenMI4** [comment]
> > > > > @McQueenMI4 Fixed! Thanks a lot!
> > > > 
> > > > 
> > > > Fixed ？？？
> > > 
> > > 
> > > 你看我的发的地址，https的。我改的域名配置，没改CNAME
> > 
> > 
> > 改成什么样子 https
> 
> 把域名配置改成： [https://你的域名](https://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D)
> 作者说的挺清楚了

更改本地目录中的 setting.json 中 domain 吗

**Comment by EryouHao** [comment]
@McQueenMI4  不是改json文件，是改你软件中的域名配置为：`https://mcqueenmi4.github.io` 即可

**Comment by McQueenMI4** [comment]
> @McQueenMI4 不是改json文件，是改你软件中的域名配置为：`https://mcqueenmi4.github.io` 即可

解决问题 感谢🙏

**Comment by McQueenMI4** [comment]
> > > > > @McQueenMI4 Fixed! Thanks a lot!
> > > > 
> > > > 
> > > > Fixed ？？？
> > > 
> > > 
> > > 你看我的发的地址，https的。我改的域名配置，没改CNAME
> > 
> > 
> > 改成什么样子 https
> 
> 把域名配置改成： [https://你的域名](https://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D)
> 作者说的挺清楚了

感谢🙏
