### ISSUE TITLE
Linux客户端同步后所有文件在output文件夹下，无法正常访问pages

### ISSUE THREAD

**Issue by lemonNoNioi** [getgridea/gridea#197]
使用Linux Appimage客户端同步后仓库首页只有一个output文件夹，所有文件都在output文件夹下
Github Pages页面无法正常访问
![image](https://user-images.githubusercontent.com/47310301/60938436-90718200-a306-11e9-8221-d777edff3e18.png)
![image](https://user-images.githubusercontent.com/47310301/60938452-9bc4ad80-a306-11e9-84c9-75f4191e6d71.png)
![image](https://user-images.githubusercontent.com/47310301/60938466-a8e19c80-a306-11e9-9b5e-74e00da13050.png)

**Comment by EryouHao** [comment]
是有手动执行什么 git 命令吗？理论上来讲应该会将 output 里面的内容同步上来的，而不是 output 文件夹

**Comment by lemonNoNioi** [comment]
> 是有手动执行什么 git 命令吗？理论上来讲应该会将 output 里面的内容同步上来的，而不是 output 文件夹

配置完成后测试连接失败，手动在源文件夹下初始化了git以及连接项目，然后测试连接成功了，但是同步后就这样了

**Comment by EryouHao** [comment]
你可能需要将外层的 `.git`文件夹删除，然后进入到 `output` 文件夹里面执行git命令就可以了

**Comment by lemonNoNioi** [comment]
> 你可能需要将外层的 `.git`文件夹删除，然后进入到 `output` 文件夹里面执行git命令就可以了

解决了，十分感谢！
