### ISSUE TITLE
同步失败的可能原因：邮件设置保密

### ISSUE THREAD

**Issue by uuunit** [getgridea/gridea#198]
测试远程连接成功，却一直同步失败。
用GitHub Desktop看了下提示的问题，修改设置后解决。
---
Cannot push these commits as they contain an email address marked as private on GitHub
上传代码时提示。

解决方法
登录github 将用户的setting中的emails选项中的 Keep my email address private 勾去掉就可以了。
--------------------- 
作者：足球中国 
来源：CSDN 
原文：https://blog.csdn.net/zanfeng/article/details/77334135 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by EryouHao** [comment]
感谢 🙏

**Comment by Walker68145** [comment]
如果是：
"fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
"
同步失败，求解决方案QAQ
