### ISSUE TITLE
Linux端存在问题，造成无法使用

### ISSUE THREAD

**Issue by qiaoxu123** [getgridea/gridea#199]
使用环境：Ubuntu 18.04
使用`AppImage`，初次使用可以，按照步骤可以预览，同步。但再次打开软件，整个软件之前的配置就全部清空了，并且无法使用任何功能，填入任何东西都无法保存。

当删除Document 下的Gridea文件夹后，再次打开软件就可以了。多次试验是这样，并且在软件打开的情况下从post文件夹下加入新的博文，无法在软件中显示。同时，关闭软件再次打开后又出现软件无法使用的情况。目前测试多次是这种情况。软件整体使用体验良好，但因为该原因无法继续使用，希望尽快解决！谢谢！

**Comment by EryouHao** [comment]
请问是不是手动增加 markdown 到 `posts` 文件夹了，如果是的话，多半是格式解析错误导致软件不显示文章。建议暂时通过直接在 Gridea 中增加文章

**Comment by qiaoxu123** [comment]
谢谢回复！按照您说的可以了。之前问题在于，我直接手动将markdown添加到文件夹中，之后打开软件就无法进行设置，一片空白了。现在从软件界面书写后，再次打开可以进行编辑了。

补充：很喜欢这个平台，希望能逐渐增加分类，访问次数统计等功能，谢谢！
