### ISSUE TITLE
无序列表中行内代码无法正常展示

### ISSUE THREAD

**Issue by LiarrDev** [getgridea/gridea#200]
在无序列表中如果使用了行内代码：

```Markdown
- 使用 `toString()` 方法进行转换……
```

不能够正常展示，会自动忽略了行内代码，直接展示成：

- 使用 toString() 方法进行转换……

但实际上应该展示为：

- 使用 `toString()` 方法进行转换……

当前使用 Gridea 版本为 V0.8.1，主题为 Simple。

**Comment by EryouHao** [comment]
暂时可自行修改主题的样式文件进行显示，或下载最新版的 [Simple](https://github.com/getgridea/gridea-theme-simple) 主题

**Comment by LiarrDev** [comment]
> 暂时可自行修改主题的样式文件进行显示，或下载最新版的 [Simple](https://github.com/getgridea/gridea-theme-simple) 主题

更新 Gridea 是否会自动更新 Simple 主题？

**Comment by EryouHao** [comment]
> > 暂时可自行修改主题的样式文件进行显示，或下载最新版的 [Simple](https://github.com/getgridea/gridea-theme-simple) 主题
> 
> 更新 Gridea 是否会自动更新 Simple 主题？

这版没有更新 simple 主题，下版会更新，一般主题更新后，如果软件也更新的话才会相对应的更新
