### ISSUE TITLE
同步遇到了错误，请联系作者

### ISSUE THREAD

**Issue by hb1001** [getgridea/gridea#202]
![image](https://user-images.githubusercontent.com/23623532/61168561-a2f7ef80-a582-11e9-8510-e0a12eae0733.png)
刚刚装上的，第一次同步没问题，写了一篇blog还可以同步成功，我写了第二篇再按同步就不行了。

**Comment by youngle316** [comment]
@hb1001 你可以试着先用Github Desktop把output文件夹试着push一下，看报什么错。我也碰到了这个问题，检测远程连接是成功的，但是就是同步失败。我用Github Desktop试着push一下，提示身份验证失败。我换了一个Token就好了。而且原来那个Token在setting中没有了。

**Comment by hb1001** [comment]
谢谢，解决了，就是在github网站上换了一个token，再回去gridea填写保存
