### ISSUE TITLE
版本更新到 0.8.2 后远程同步出现问题

### ISSUE THREAD

**Issue by dreamhomes** [getgridea/gridea#204]
从版本0.8.1更新到0.8.2后远程同步出现问题如下：
![Snipaste_2019-07-16_15-28-28](https://user-images.githubusercontent.com/35626972/61274623-c4551780-a7de-11e9-8bbc-c12da45233ad.png)

**Comment by JieSmart** [comment]
、。。。。

**Comment by oblivionverses** [comment]
+1

**Comment by dreamhomes** [comment]
解决方法：

- 手动更新主题（删除themes文件夹下所有文件）
- 重新安装应用
