### ISSUE TITLE
tag 不能删除

### ISSUE THREAD

**Issue by StandOutstar** [getgridea/gridea#206]
从 v0.8.1 升级到 v0.8.2 后，原有的 tag不能删除。见下图：
![Xnip2019-07-17_10-06-06](https://user-images.githubusercontent.com/17442044/61341834-a4733180-a87a-11e9-9e20-7bcb4ad223d6.jpg)

**Comment by EryouHao** [comment]
正在使用的 tag 不能删除，未使用的可以删除，若想删除，可先从文章中取消 tag 使用

**Comment by StandOutstar** [comment]
￣□￣｜｜，谢谢回复，不知道这个逻辑。
