### ISSUE TITLE
能不能详细说一下 0.8.2 中关于文章目录和阅读时间的设置？

### ISSUE THREAD

**Issue by YingYunlong** [getgridea/gridea#207]

**Comment by EryouHao** [comment]
目前新版的 Notes 主题已经内置了这两个的显示，其他主题若需要可能需要自行添加一下，

在主题的模版中，可使用 `post.stats.text` 来显示阅读时间
在主题的 `post.ejs` 中使用 `post.toc` 来显示文章目录

**Comment by YingYunlong** [comment]
> 目前新版的 Notes 主题已经内置了这两个的显示，其他主题若需要可能需要自行添加一下，
> 
> 在主题的模版中，可使用 `post.stats.text` 来显示阅读时间
> 在主题的 `post.ejs` 中使用 `post.toc` 来显示文章目录

我手动替换了本地 Notes 主题里和新版本 Notes 主题有差异的文件，再重新同步之后发现就有了，谢谢🙏

**Comment by EryouHao** [comment]
enjoy～
