### ISSUE TITLE
0.8.2版本，Manjaro18无法运行Gridea

### ISSUE THREAD

**Issue by JasonVenn** [getgridea/gridea#213]
我从releases上下载了0.8.2版本的Appimage，赋予执行权限后尝试打开，并没有反应。
与Electron有关否？我安装的是5.0.6

相反地，运行0.8.1版本却能够十分顺利

**Comment by EryouHao** [comment]
执行一下
```
$ sudo chmod a+x Gridea.0.8.2.AppImage
$ ./Gridea.0.8.2.AppImage
```
然后以后就可以双击打开了

我在 Ubuntu 18.04.2 上测试成功，试一下呢？

**Comment by JasonVenn** [comment]
> 执行一下
> 
>  ```
> $ sudo chmod a+x Gridea.0.8.2.AppImage
> $ ./Gridea.0.8.2.AppImage
> ```
> 
> 然后以后就可以双击打开了
> 
> 我在 Ubuntu 18.04.2 上测试成功，试一下呢？

不行，奇怪，依然不行

**Comment by BruceZhang1993** [comment]
Manjaro 可以尝试下 https://aur.archlinux.org/packages/gridea/ 是否可以使用 :rofl:

**Comment by JasonVenn** [comment]
> Manjaro 可以尝试下 https://aur.archlinux.org/packages/gridea/ 是否可以使用 
> 
> 直接使用 Pamac 开启 AUR 支持并搜索 gridea 也可

这个我也已经试过，不过在编译的时候提示「SIGBART」错误
我不是很懂这个，希望您能帮助我

**Comment by BruceZhang1993** [comment]
> > Manjaro 可以尝试下 https://aur.archlinux.org/packages/gridea/ 是否可以使用
> > 直接使用 Pamac 开启 AUR 支持并搜索 gridea 也可
> 
> 这个我也已经试过，不过在编译的时候提示「SIGBART」错误
> 我不是很懂这个，希望您能帮助我

不太清楚，不能编译可以尝试下面这个已编译的包
https://repo.brucezhang.cf/x86_64/gridea-0.8.2-1-x86_64.pkg.tar.xz

**Comment by JasonVenn** [comment]
> > > Manjaro 可以尝试下 https://aur.archlinux.org/packages/gridea/ 是否可以使用
> > > 直接使用 Pamac 开启 AUR 支持并搜索 gridea 也可
> > 
> > 
> > 这个我也已经试过，不过在编译的时候提示「SIGBART」错误
> > 我不是很懂这个，希望您能帮助我
> 
> 不太清楚，不能编译可以尝试下面这个已编译的包
> https://repo.brucezhang.cf/x86_64/gridea-0.8.2-1-x86_64.pkg.tar.xz

嗯，可以用了
万般感谢
