### ISSUE TITLE
为什么我每次同步博客之后自定义的域名都被清了呢

### ISSUE THREAD

**Issue by IYABAO** [getgridea/gridea#215]
每次更新完，都得手动设置。。

**Comment by IYABAO** [comment]
> 每次更新完，都得手动设置。。

**Comment by IYABAO** [comment]
软件设置 CNAME

**Comment by lzyblog** [comment]
肯定设置了cname的啊……就是因为不知道哪里出错了才来请教大佬。设置都没问题

**Comment by EryouHao** [comment]
@lzyblog 如果是在软件内设置的 cname，而不是手动建的 cname 文件，那应该是没有问题的

**Comment by lzyblog** [comment]
会不会是保存配置那里出错了呢？即使未修改任何内容，只要重新保存了，就会重新生成一个cname文件？所以，即使cname的内容是一样的，原来的自定义域名也会失效？

**Comment by EryouHao** [comment]
![image](https://user-images.githubusercontent.com/17328747/65217081-9ee9d000-dae5-11e9-87bc-71b00275c7bc.png)
你这个 CNAME 是自己改的吧？直接在软件中设置就好了，不需要自己提交。
![image](https://user-images.githubusercontent.com/17328747/65217126-bcb73500-dae5-11e9-908c-9f11459b708b.png)

**Comment by lzyblog** [comment]
不是自己改的哦，直接在软件中设置的。但是每次同步，他就会提交一下
