### ISSUE TITLE
在Gridea中配置好Coding后，如果远程连接成功但是同步失败，可以尝试将token改为coidng的登录密码

### ISSUE THREAD

**Issue by qianlizhe** [getgridea/gridea#218]
在Gridea中配置好Coding后，如果远程连接成功但是同步失败，可以尝试将token改为coidng的登录密码。
我在搭建博客时，遇到了这个问题，折腾了半天一直报:
```
"remote: Coding 提示: Authentication failed.
remote: 认证失败，请确认您输入了正确的账号密码。
fatal: Authentication failed for 'https://username:token@git.coding.net/username/username.coding.me.git/'
"
```
后来在Gridea交流群里经群友指点，把token改为登录密码，可以了。
在这里说一下，方便和我一样的新用户使用Gridea。
另外，我是看Gridea网站里面的B站视频教程配置的Coding 参数。

**Comment by cloudLiu** [comment]
谢谢，搞定了。
有个小插曲：我的密码最后一位是@。就报错。。去掉就可以了
