### ISSUE TITLE
换了一台电脑，然后我同步了一下，然后悲剧了。。

### ISSUE THREAD

**Issue by cclomin** [getgridea/gridea#219]
我还故意把GITHUB上的仓库克隆到本地了。然后在软件中设置了源文件夹为克隆下来的那个文件目录。。然后很悲剧。。还好刚开始用。写的东西不多。。。

**Comment by EryouHao** [comment]
同步到 GitHub 上的文件为构建后的静态文件，并非博客源文件夹，源文件夹可参考应用中的：系统-> 源文件夹查看
