### ISSUE TITLE
文章内编写一键另存

### ISSUE THREAD

**Issue by chiperman** [getgridea/gridea#221]
有时候写一篇文章，可能有不同排版要对比，那么如果每次自己复制开心文章重新排版很麻烦，能不能在第一篇文章内部一键克隆一份test，这样就可以快速修改，还可以在发布前预览进行对比

**Comment by EryouHao** [comment]
这个我们可能不太考虑加到 Gridea 中。我们相信在您写过十几篇文章之后在排版布局上会有丰富的经验，而且无需过多考虑这部分，而这也是 Markdown 所倡导的。大部分时候只要合理使用 Markdown 语法就可以得到一个相对漂亮的排版
