### ISSUE TITLE
请问侧边栏目录如何配置

### ISSUE THREAD

**Issue by slowlog** [getgridea/gridea#222]
我已经更新到 V0.8.2 但是没找到这个侧边栏目录，如下图：

![WX20190723-114600](https://user-images.githubusercontent.com/16852041/61681322-9e2ffa00-ad3f-11e9-9623-9b575f1d04f3.png)

**Comment by EryouHao** [comment]
最新版本的 Notes 主题自带目录显示，你截图中的这个目录，是 Walker 主题中的

**Comment by slowlog** [comment]
但我把 Gridea 从 0.8.1 更新到 0.8.2 ， 发现 Notes 主题是没有的，是需要配置什么吗

**Comment by EryouHao** [comment]
需要删除 themes 文件夹中的 notes 文件夹，然后重启应用即可

**Comment by slowlog** [comment]
@EryouHao ok，生效了，非常感谢

**Comment by cloudLiu** [comment]
侧边菜单有了，但是文章过长菜单过多的时候 菜单就不能滚了，需要滑到文章到底部然后菜单才会跟着滑动。

**Comment by EryouHao** [comment]
首先我们推荐精简目录层级，毕竟一篇文章目录过多，可以想下使用其他的标签替换例如列表
另外，目录滚动目前实现的不太好导致的滚动问题，可提 PR 到主题仓库或等待更新
