### ISSUE TITLE
预览成功但是同步之后没有样式

### ISSUE THREAD

**Issue by Colaman0** [getgridea/gridea#223]
具体文章能显示出来，但是CSS样式失效了，基础配置中的域名也是有添加https的

**Comment by webszy** [comment]
我是今天突然同步不了，也没个日志

**Comment by EryouHao** [comment]
@Colaman0 我看了下你的站点，是因为你的域名配置错了，应该写 `https://colaman0.github.io/kylelin.io/`

**Comment by EryouHao** [comment]
@webszy https://gridea.dev/docs/faq.html

**Comment by Colaman0** [comment]
> @Colaman0 我看了下你的站点，是因为你的域名配置错了，应该写 `https://colaman0.github.io/kylelin.io/`

问题已解决谢谢
