### ISSUE TITLE
【Bug】Mac上同步成功，但是打开主页报404

### ISSUE THREAD

**Issue by HeLuchao** [getgridea/gridea#224]
多设备管理的情况，windows系统下可以同步成功也可以访问到博客，切换到Mac系统之后，博客可以同步成功，但是打开主页直接报404，使用的是coding.me的主页。

**Comment by EryouHao** [comment]
我现在访问你的站点好像是可以访问的？同步之后可能需要稍微等一下。我先关 issue 了，若有问题可继续回复

**Comment by HeLuchao** [comment]
<img width="1171" alt="WeChat94b7f9ae680d2498c2386b5dabd809e2" src="https://user-images.githubusercontent.com/26295760/61806330-1561ad00-ae6a-11e9-8cf5-07412ae545e4.png">

**Comment by EryouHao** [comment]
多半是你的域名配置错误，为什么不是 `https://chaochao940215.coding.me/` ?

**Comment by HeLuchao** [comment]
后面那是默认的首页，可有可无的跟https://chaochao940215.coding.me/效果是一样的~

**Comment by HeLuchao** [comment]
@EryouHao 还有个bug，就是博文里面的代码块含有{{变量名}}的时候，博文就直接报错了，控制台会直接报找不到该变量的错

**Comment by HeLuchao** [comment]
@EryouHao 晚上回来用Mac试了试，把域名配置改成了https://chaochao940215.coding.me，同步上去，显示同步成功，但是打开主页还是404～
