### ISSUE TITLE
为什么本地预览样式没问题，但是上传后打开网页有问题，已经清除缓存了

### ISSUE THREAD

**Issue by ottopan** [getgridea/gridea#227]
![image](https://user-images.githubusercontent.com/18224971/61890534-37c2fb80-af3a-11e9-84af-f694c9d4db11.png)
如图

**Comment by ottopan** [comment]
![image](https://user-images.githubusercontent.com/18224971/61913495-ea618100-af6f-11e9-9044-1572d2c91421.png)
补充一下

**Comment by EryouHao** [comment]
域名配置写https
