### ISSUE TITLE
预览双重纵向滚动条

### ISSUE THREAD

**Issue by gaoliang** [getgridea/gridea#228]
使用下面的markdown新建文章，编辑器预览会出现双重滚动条
https://gist.github.com/gaoliang/5f386120ad75d74ba53af08ec9ff2f0b
![image](https://user-images.githubusercontent.com/18087875/61921319-59020700-af8f-11e9-8a1f-5f21b65f603d.png)

**Comment by cmmei** [comment]
我的也会出现双重滚动条。

**Comment by EryouHao** [comment]
fixed
