### ISSUE TITLE
0.8.2远程链接成功，同步错误

### ISSUE THREAD

**Issue by xingshengji** [getgridea/gridea#231]

**Comment by infiWang** [comment]
<img width="894" alt="2019-07-28 (1)" src="https://user-images.githubusercontent.com/23418176/62008822-36880d80-b18a-11e9-84b8-8396dea60f35.png">
Same issue here.

**Comment by infiWang** [comment]
通过开发者终端发现是由于打开了GitHub的私人邮件地址保护, 取消/切换后已正常

**Comment by xingshengji** [comment]
感谢解答，我的貌似不是邮件保护问题！切换了一下，依然不可以！

**Comment by xingshengji** [comment]
> 通过开发者终端发现是由于打开了GitHub的私人邮件地址保护, 取消/切换后已正常

感谢解答，我的貌似不是邮件保护问题！切换了一下，依然不可以！

**Comment by xingshengji** [comment]
![](http://ww1.sinaimg.cn/large/006r8x4Hgy1g5gtwpfxkvj30tw085mxd.jpg)

**Comment by ci0n** [comment]
重新生成一个key
