### ISSUE TITLE
我的文件怎么全打不开了，我重新选源文件也不行，好挫败

### ISSUE THREAD

**Issue by ottopan** [getgridea/gridea#232]
如图，文章、菜单、标签都是空的，啥原因？ATOM 编辑器毁文件？十万火急呀
![image](https://user-images.githubusercontent.com/18224971/62003453-b17d0400-b149-11e9-92d7-64e1d9ca3b27.png)
![image](https://user-images.githubusercontent.com/18224971/62003455-bd68c600-b149-11e9-9df9-5e7b3f5efbc8.png)

**Comment by ottopan** [comment]
我测试了一下，是因为我使用 atom 的这个插件，修改了主题文件，导致不可用
[插件地址](https://atom.io/packages/atom-ternjs)
接着，我想请教一下，为什么使用了这个插件就不可用了，如何调整为可用？
下方是我的博客文件，你可以帮忙看看吗？
[mysite.zip](https://github.com/getgridea/gridea/files/3439004/mysite.zip)

**Comment by guyeu** [comment]
同样的问题，我只是从别的地方粘了几篇文章过来就挂了。。

**Comment by guyeu** [comment]
是因为我原来的文件头部有一些东西不符合gridea的格式要求，我手动改了一遍就好了

**Comment by iXiAo9** [comment]
![捕获.PNG](https://i.loli.net/2019/08/05/IUNRFBsHe9EX17u.png)
每个文章都有自己的，头文件用于gridea读取
