### ISSUE TITLE
一些链接的地址的缓存问题

### ISSUE THREAD

**Issue by yangweijie** [getgridea/gridea#24]
像icon avatar 目前地址是写死路径，客户端更新后同步后 如果不强制刷新 页面 永远看的是旧效果，能否改为加上获取出来的最后一次commit id 作为版本号。

还有simple 主题打开背景很慢，希望大部分资源都用国内的cdn 图片能换一些简单的 或者渐进式jpeg 加快加载速度

**Comment by EryouHao** [comment]
缓存问题，在最新版（>v0.8.0）已解决
