### ISSUE TITLE
v0.8.2版本无法进行同步，一直Loading

### ISSUE THREAD

**Issue by huopochuan** [getgridea/gridea#241]
![image](https://user-images.githubusercontent.com/7405212/62676813-a98d5180-b9de-11e9-969b-965264bd4541.png)

## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  mac    |
| 软件版本 |    v0.8.2  |
| 主题名称 |      |

---

**Comment by EryouHao** [comment]
请检查一下您的网络状况，我看您之前同步成功过？或者去 FAQ 看下具体原因 https://gridea.dev/docs/faq.html

**Comment by huopochuan** [comment]
"xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
" 检测远程连接报这个错

**Comment by huopochuan** [comment]
环境问题忽略
