### ISSUE TITLE
未保存的文章在点击返回按钮后，不会提醒保存，会导致草稿丢失

### ISSUE THREAD

**Issue by imane0897** [getgridea/gridea#243]
## 概述
新建文章草稿，未保存的情况下，在点击“返回”按钮时，增加一个提醒保存的功能。

## 动机
如果用户新建了文章草稿，在保存之前错误地点击了返回，会导致草稿内容丢失。

**Comment by pazyork** [comment]
这个问题我也碰到了两次，很让人糟心，希望能增加提醒保存的特性

**Comment by EryouHao** [comment]
v0.8.3 版本已经添加了，可使用看看
