### ISSUE TITLE
文章的URL与其他文章重复

### ISSUE THREAD

**Issue by LiarrDev** [getgridea/gridea#244]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  macOS    |
| 软件版本 |   0.8.2   |
| 主题名称 |   Simple 1.0.0   |

---

## 期望行为

正常保存

## 当前行为

编辑文章点击保存时偶尔会出现「文章的 URL 与其他文章重复」的提示，但实际上并没有冲突的 URL，所以可以肯定只是编辑的文章与未修改时的文章冲突了。

![弹窗](https://s2.ax1x.com/2019/08/08/eHpv8O.png)

我暂时的解决方法是先复制全文，然后退出文章编辑，再次进入粘贴，再保存。

**Comment by mylifelog** [comment]
同样遇到了，白写了半天 ==。

**Comment by LoveCoati** [comment]
这个可以在文章设置里面重新修改url
