### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by Hanyuyu** [getgridea/gridea#249]
## 概述

  建议添加可以自定义404页面的情况，当访问域名的错误地址时，显示的404很难看，
，希望可以给出添加404页面的选择。

## 动机
github的404好丑的，不个性，希望推出404页面的配置功能

## 详细解释
提供选择或者用户自定义都不错，如果可以使用腾讯的公益404，也算是为社会做出贡献了

**Comment by EryouHao** [comment]
新版已经有默认的 404 页面了，同时，主题可自定义 404 页面，详情可见文档
