### ISSUE TITLE
Gridea同步到GitHub的文件出错

### ISSUE THREAD

**Issue by figthin** [getgridea/gridea#251]
同步到GitHub的文件多出两级文件夹/Document/Gridea，所以访问GitHub页面的就404，希望能得到解答，谢谢

**Comment by EryouHao** [comment]
这是因为你的 Documents 外层有 `.git` 文件夹，或者说有 git 使用记录，看了一眼你的仓库好像有个 learngit 的文件夹，把.ssh 目录下的.git 删除一下试试？或者更换源文件夹目录试试

**Comment by figthin** [comment]
删了.git可以了，万分感谢




------------------ 原始邮件 ------------------
发件人: "Eryou Hao"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 中午11:22
收件人: "getgridea/gridea"<gridea@noreply.github.com>;
抄送: "小可"<1452720285@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [getgridea/gridea] Gridea同步到GitHub的文件出错 (#251)




这是因为你的 Documents 外层有 .git 文件夹，或者说有 git 使用记录，看了一眼你的仓库好像有个 learngit 的文件夹，把.ssh 目录下的.git 删除一下试试？或者更换源文件夹目录试试

**Comment by EryouHao** [comment]
Enjoy~
