### ISSUE TITLE
怎么在<head> ...</head>添加其他的js文件或样式文件？

### ISSUE THREAD

**Issue by wuweijian1997** [getgridea/gridea#252]
我想添加一个网页背景动画类似的第三方库，只要把它的js文件在head里定义一下就可以。那么我在哪里可以添加呢？我看过官方文档，好像没找到这个功能

**Comment by EryouHao** [comment]
在主题文件中，一般是 `head.ejs`，然后添加就可以了
若是本地的 js 文件，可放在 `主题/assets/media` 文件夹就可以了
例如：
`notes/assets/media/js/jquery.js`
使用时是
`<script src="/media/js/jquery.js"></script>`

**Comment by wuweijian1997** [comment]
感谢
