### ISSUE TITLE
同步到 Github 时 css 样式丢失

### ISSUE THREAD

**Issue by Hulenkius** [getgridea/gridea#255]
上个星期开始的。
在本地“预览”下，一切正常。
但是“同步”之后刷新预览网页，css样式丢失。此时在已同步的网站上，css样式也丢失。
导致我只能使用 Git 同步仓库到云端来更新博客。

**Comment by EryouHao** [comment]
我看了下博客已经恢复正常？

**Comment by Hulenkius** [comment]
> 我看了下博客已经恢复正常？

嗯对，刚刚提完这个问题就恢复正常了……
