### ISSUE TITLE
发布的文章创建时间输入体验

### ISSUE THREAD

**Issue by yangweijie** [getgridea/gridea#26]
应该可以复制 粘贴进去，方便迁移时修改为之前的发布时间。应该博客里只又按发布时间排序。没有单独的排序字段，最好在列表里单独修改

**Comment by EryouHao** [comment]
> 应该可以复制 粘贴进去，方便迁移时修改为之前的发布时间。应该博客里只又按发布时间排序。没有单独的排序字段，最好在列表里单独修改

例如什么排序字段呢？
