### ISSUE TITLE
再请教大佬一个问题，radio如何设置为垂直显示呢？

### ISSUE THREAD

**Issue by GanZhiXiong** [getgridea/gridea#267]
radio现在是水平横向显示，我想设置为垂直显示
![image](https://user-images.githubusercontent.com/27394631/64139093-4c948800-ce32-11e9-9e86-9b27e0ad6dde.png)

**Comment by EryouHao** [comment]
建议你去看下 Vue.js 的文档和对应组件库的 API 开发下，这些是与 Gridea 无关的内容。
