### ISSUE TITLE
大神，radio选中事件的代码怎么写？

### ISSUE THREAD

**Issue by GanZhiXiong** [getgridea/gridea#268]
小白问个再问个问题哈！😀
![image](https://user-images.githubusercontent.com/27394631/64140082-c7ab6d80-ce35-11e9-9531-52a459775677.png)
我不知道知道radio选中事件的代码怎么写，然后我想转到a-radio-group定义，查看里面是否有selected这个事件，在vscode中光标定位到a-radio-group，然后Go to definition,提示如下图所示
![image](https://user-images.githubusercontent.com/27394631/64140044-a6e31800-ce35-11e9-99b2-7f613e5b1340.png)

**Comment by EryouHao** [comment]
学习下 Vue.js 就会了哈
