### ISSUE TITLE
代码的排版问题

### ISSUE THREAD

**Issue by Yoxode** [getgridea/gridea#27]
在leetcode写的代码复制到代码块里面之后预览时代码格式不太对（Python代码），缩进有问题。

**Comment by EryouHao** [comment]
能提供一个示例或截图吗？是应用中编辑器菜单中的预览吗？

**Comment by iondex** [comment]
Tab在编辑器中显示的只有一个空格，但渲染出来却有四个空格的长度
![image](https://user-images.githubusercontent.com/4617752/56188787-f5e00a80-6058-11e9-856c-a469adfa5195.png)
![image](https://user-images.githubusercontent.com/4617752/56188811-04c6bd00-6059-11e9-89eb-838257b487be.png)

**Comment by EryouHao** [comment]
😯，或许是渲染引擎渲染逻辑问题，让我检查它

**Comment by JokerLbz** [comment]
你好，可否在预览的时候渲染小代码块儿，像图中第三行一样（第二行为预览）
<img width="150" alt="Snipaste_2019-04-20_21-30-52" src="https://user-images.githubusercontent.com/31786962/56457917-032c2a80-63b4-11e9-8a9b-033f018d2fa4.png">

**Comment by EryouHao** [comment]
@JokerLbz 已经支持
