### ISSUE TITLE
希望标签能居中显示

### ISSUE THREAD

**Issue by GanZhiXiong** [getgridea/gridea#270]
![image](https://user-images.githubusercontent.com/27394631/64231474-51d10000-cf22-11e9-9f28-60546b683ca2.png)

大佬的项目给了我很多的参考，现在我想要上图红框的标签居中，代码该怎么写呢，试了很久都不行。

**Comment by EryouHao** [comment]
这个是主题问题，可自行修改主题

**Comment by EryouHao** [comment]
学习一下 css，就都会了

**Comment by GanZhiXiong** [comment]
搞了好久，还是不行呀！ 大佬求助呀🙏😭
