### ISSUE TITLE
feat: 希望能支持同步到Ftp空间

### ISSUE THREAD

**Issue by alterfang** [getgridea/gridea#280]
## 概述

 希望能够多一个同步到Ftp空间上面的功能

## 动机

  因为以目前的Github和Coding的情况都不是特别的稳定，时常有打不开，或者还完的情况！但是FTP空间对于只是建立博客的我们来说是非常实惠的！而且性价比也高！操作也简单！相比于服务器来说对于我们这种小白，学生来说是更好的选择！

**Comment by EryouHao** [comment]
新版已增加 sftp 同步支持
