### ISSUE TITLE
切换tab后，页面回到顶部

### ISSUE THREAD

**Issue by GanZhiXiong** [getgridea/gridea#281]
点击“配置”，滚动条滚动到页面底部
![image](https://user-images.githubusercontent.com/27394631/64664707-88f36400-d482-11e9-875b-1b8a1828f092.png)

点击“系统”，再点击“配置”，会发现“配置”页面的回到了顶部了，能不能保留页面位置的状态呢？
![image](https://user-images.githubusercontent.com/27394631/64664774-ca840f00-d482-11e9-8969-ebbd679c3336.png)

**Comment by EryouHao** [comment]
这个不这样去处理
