### ISSUE TITLE
修改了ts文件，是不是需要重新编译代码才能生效？

### ISSUE THREAD

**Issue by GanZhiXiong** [getgridea/gridea#282]
我的操作步骤如下：
1、yarn electron:serve
2、修改ts文件的代码
3、ctrl+z终端停止，
4、yarn electron:serve

每次yarn electron:serve都很慢，大佬有没有更快的调试方法吗？
![image](https://user-images.githubusercontent.com/27394631/64763453-97b94400-d572-11e9-85d2-dde2357f8cf5.png)

**Comment by EryouHao** [comment]
不用停止，服务端可保存一下 background.ts 即可重新编译

**Comment by GanZhiXiong** [comment]
我发现只要我再background.ts这个文件中按下Ctrl+s就会重新编译，但是在其他的ts文件中保存，却不会重新编译。
比如我修改了a.ts文件，如果要重新编译，我需要在a.ts中按下Ctrl+s，然后再background.ts中按下Ctrl+s，才会重新编译。
这样也挺麻烦的呀，大佬有其他更好的快的方法吗？

**Comment by EryouHao** [comment]
你可以看下 vue-cli-plugin-electron-builder + ts 有没有办法设置一下监听 ts 文件重新编译

**Comment by GanZhiXiong** [comment]
嗯嗯，好的，多谢大佬。

**Comment by GanZhiXiong** [comment]
请问大佬，每次保存后，进行编译都很慢，这个是什么原因导致慢的呢？
