### ISSUE TITLE
关于github授权登录问题

### ISSUE THREAD

**Issue by kkxiaoa** [getgridea/gridea#283]
在某个文章模块下进行github授权登录，回调地址填什么？我如果把回调地址填成和home地址一样的话每次点击登录就唤不醒第三方授权登录页，但是如果我填写该文章的回调路径虽然可以唤起授权页但是这是只针对该文章，所以我不清楚里面具体请求逻辑是怎样的，github授权回调地址填什么

**Comment by EryouHao** [comment]
我猜你说的是 Gitalk 的配置，可以看下 Gitalk 的文档 https://github.com/gitalk/gitalk
