### ISSUE TITLE
Chrome 无法自动加载脚本

### ISSUE THREAD

**Issue by 2512821228** [getgridea/gridea#284]
我的博客是部署在 Coding , Chrome 无法自动加载脚本 , Chrome版本: 77.0.3865.75 (9.13 最新稳定版) 

![图示](https://cdn.luogu.com.cn/upload/image_hosting/dmak9qmt.png)

**Comment by 2512821228** [comment]
主题是 Fly

**Comment by EryouHao** [comment]
我看了下你的博客，并没有报这个错误，是不是之前把域名写成了 http 的了？

**Comment by 2512821228** [comment]
是我之前搭建在Coding （https://thanchzhao.coding.me/） 上的，在github上没有这个问题

**Comment by EryouHao** [comment]
> 是我之前搭建在Coding https://thanchzhao.coding.me 上的，在github上没有这个问题

域名写错了，写成你上面写的这个就可以，需要使用 `https`
