### ISSUE TITLE
想请问一下下一篇文章的函数是什么？

### ISSUE THREAD

**Issue by lzyblog** [getgridea/gridea#288]
比如目前在文章页的下一篇文章代码是：
`          <div class="next-post">
            <a class="purple-link" href="<%= post.nextPost.link %>">
              <h3 class="post-title">
                下一篇：<%= post.nextPost.title %>
              </h3>
            </a>
          </div>`
想问一下上一篇文章的代码是什么，方便美化

**Comment by EryouHao** [comment]
[目录结构与页面变量 | Gridea](https://gridea.dev/docs/theme-structure.html#post)
