### ISSUE TITLE
[bug] url中含有 '/' 导致新建文章保存失败

### ISSUE THREAD

**Issue by qin-nz** [getgridea/gridea#29]
重现步骤：
新文章，URL设置为"a/b"，标题、正文随意，保存.

效果：
提示保存成功，实际无文件。

版本：
Windows 0.7.7

**Comment by EryouHao** [comment]
因为 '/' 是路径特殊标识符，你可以换用其他的字符，它是将这个识别成目录分隔符了，所以创建失败了，

提示保存成功这个是 bug，下版本修复，感谢支持

**Comment by qin-nz** [comment]
@EryouHao 我就是想要把它当作目录分隔符来用的 :hap

**Comment by EryouHao** [comment]
目前的机制不支持多层级目录文章结构，抱歉了
