### ISSUE TITLE
github远程连接不上

### ISSUE THREAD

**Issue by lzyblog** [getgridea/gridea#290]
基本配置那里完全填的是对的，但是一直提示仓库名、用户名和token有问题，我试了很多次，甚至换过token试，还是报错。查看报错信息是："fatal: No such remote 'origin'
"
实在解决不了，今天下午都还是好的，晚上打算更新下结果一直报错。。。下午到晚上唯一做的就是用家里的windows和mac同步了一下，导致配置信息重新填写了，按照原配置信息填的，但是就连接不上了。求助大佬帮助啊

**Comment by EryouHao** [comment]
是外层有 `.git/` 文件夹的原因，已协助解决。

**Comment by JoanneTsai1208** [comment]
> 是外层有 `.git/` 文件夹的原因，已协助解决。

請問是如何解決的? 我也有這個問題

**Comment by EryouHao** [comment]
需要把源文件夹 `output` 外层的 `.git/` 文件夹删除。看你的路径好像是 C:\Users\Joanne Tsai.git

**Comment by MovLe** [comment]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/52394033/72121002-abe04700-3394-11ea-9341-fc8b1a71b860.png">

然而我并没有看到.git/ 文件夹，请问如何解决

**Comment by yz0812** [comment]
> <img alt="image" width="819" src="https://user-images.githubusercontent.com/52394033/72121002-abe04700-3394-11ea-9341-fc8b1a71b860.png">
> 
> 然而我并没有看到.git/ 文件夹，请问如何解决

本人的解决办法找到 C:\Users\yz_08\Documents\Gridea\output\.git 直接修改config文件,即可

**Comment by beicheng-maker** [comment]
chunk-vendors.785f1d04.js:313 Error: unable to verify the first certificate
