### ISSUE TITLE
同一段落中链接过多会缺失

### ISSUE THREAD

**Issue by SakuraXIII** [getgridea/gridea#292]
如果在同一段中有多条链接，在保存之后，再次打开，这一段就会删除大量内容，只留下一条连接，同步之后链接的图片也无法显示

**Comment by EryouHao** [comment]
请提供复现 DEMO 或文本

**Comment by SakuraXIII** [comment]
> 请提供复现 DEMO 或文本
如果按这样的形式进行保存：
![before](https://user-images.githubusercontent.com/48901736/65369065-32083e80-dc7b-11e9-95d3-5cba215c0942.png)，
在返回之后，再次进入就会变成这样：
![after](https://user-images.githubusercontent.com/48901736/65369068-3af91000-dc7b-11e9-9fd8-a3f96ff001a9.png)
如果将最后一段话进行换行，就没有问题

**Comment by LiarrDev** [comment]
> > 请提供复现 DEMO 或文本
> > 如果按这样的形式进行保存：
> > ![before](https://user-images.githubusercontent.com/48901736/65369065-32083e80-dc7b-11e9-95d3-5cba215c0942.png)，
> > 在返回之后，再次进入就会变成这样：
> > ![after](https://user-images.githubusercontent.com/48901736/65369068-3af91000-dc7b-11e9-9fd8-a3f96ff001a9.png)
> > 如果将最后一段话进行换行，就没有问题

好奇怪的写法，图片本来就该单独一行吧

**Comment by SakuraXIII** [comment]
> > > 请提供复现 DEMO 或文本
> > > 如果按这样的形式进行保存：
> > > ![before](https://user-images.githubusercontent.com/48901736/65369065-32083e80-dc7b-11e9-95d3-5cba215c0942.png)，
> > > 在返回之后，再次进入就会变成这样：
> > > ![after](https://user-images.githubusercontent.com/48901736/65369068-3af91000-dc7b-11e9-9fd8-a3f96ff001a9.png)
> > > 如果将最后一段话进行换行，就没有问题
> 
> 好奇怪的写法，图片本来就该单独一行吧

是这样吗。。我在网上并没有看到这样的规范。那也不至于把中间的文本全部删除了吧。可能是typora、CSDN这些用多了，我不知道。。。

**Comment by LiarrDev** [comment]
规范的写法可以避免很多不必要的问题哦，因为每个网站甚至同一网站上不同主题使用的渲染方式都不尽相同，采用规范统一的写法可以尽到最大的兼容。

不熟悉可以使用 Gridea 上的工具条辅助书写，也可以去一些 Markdown 相关的网站了解以下语法，我刚开始接触 Markdown 的时候是使用 [CMD Markdown](https://www.zybuluo.com/mdeditor)，它上面除了实时预览，还提供了相对标准的语法示例，你可以参考一下。

**Comment by SakuraXIII** [comment]
好的，我知道了，感谢指导。谢谢啦
