### ISSUE TITLE
gridea 因为认证问题无法在mac系统上启动

### ISSUE THREAD

**Issue by csrgxtu** [getgridea/gridea#294]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |    majavo  |
| 软件版本 |   0.8.3   |
| 主题名称 |   default   |

---

## 当前行为
![image](https://user-images.githubusercontent.com/5053620/65407658-d920dd80-de15-11e9-8027-45ffe0434ac4.png)

**Comment by EryouHao** [comment]
![image](https://user-images.githubusercontent.com/17328747/65410562-45530f80-de1d-11e9-96db-ec2bc51d32bd.png)
在应用程序中右键打开即可。
