### ISSUE TITLE
无法渲染带有 {{ ... }} 的代码块

### ISSUE THREAD

**Issue by bofeng** [getgridea/gridea#298]
Gridea版本0.8.3 for Mac OS，主题是Fly。

我写的内容是：

<pre>
use `autoescape` block:
```html
{% autoescape false %}
    autoescaping is disabled here
    {{ will_not_be_escaped }}
{% endautoescape %}
```
</pre>

正常应该是把三个撇号内的代码块渲染出来，但是里面的{{ will_not_be_escaped }}会被渲染成空白。

在写作模式下，点击右侧栏的预览时，显示没有问题；但是当点整站预览，然后点击这边文章时，{{}}就被渲染成空白了。

我猜测是这部分代码 {{}} 和vue的语法冲突，然后vue想渲染一个变量值进去，而没有把它当成用户的代码块？

**Comment by EryouHao** [comment]
是的，这应该是那个主题的特有问题

**Comment by bofeng** [comment]
确实，发现内置的四个主题中，Fly和Simple都有这个问题，Notes和Paper没有

**Comment by EryouHao** [comment]
可在 对应的主题文件中，添加一下 `v-pre` 标签，具体可参照 https://cn.vuejs.org/v2/api/#v-pre

加到 post.ejs 中即可
