### ISSUE TITLE
始终 远程连接失败，请检查仓库、用户名和 Token 设置

### ISSUE THREAD

**Issue by foxair** [getgridea/gridea#30]
![image](https://user-images.githubusercontent.com/517589/54477174-29ecc380-4840-11e9-8f83-4b6dbb093ae5.png)

按照示例填写配置, 一直提示失败, token重新生成了很多次

**Comment by EryouHao** [comment]
您可以打开 Edit -> Toggle Develope tools 然后再点击检测远程链接查看详细的错误原因

**Comment by owenbearPython** [comment]
> 抱歉回复的不及时。
> 您可以打开 Edit -> Toggle Develope tools 然后再点击检测远程链接查看详细的错误原因

检测远程连接是ok的，但是同步不了。提示：抱歉，同步遇到了错误，请联系开发者

**Comment by EryouHao** [comment]
@owenbearPython 不知现在是否同步成功，若还是相同的报错，可打开 Edit -> Toggle Develope tools 然后再点击同步，插件详细的错误原因，或加群解决，感谢支持

**Comment by hiie** [comment]
怎么解决呢

**Comment by Raphael95** [comment]
同样的问题，总是显示连接错误。点击 Edit -> Toggle Develope tools  查看后错误提示是：no such remote 'origin'

**Comment by chudanqin** [comment]
系统-源文件夹
查看下 git 配置

**Comment by EpitomM** [comment]
第一次配置成功后，第二次打开gridea软件，所有输入框内配置信息都消失了，且再次填入信息后点击“保存”显示保存成功，点击“检测远程连接”无反应，查看console也不输入任何信息
