### ISSUE TITLE
一夜醒来,软件的所有配置全都没了~包括文章,配置

### ISSUE THREAD

**Issue by 1042970366** [getgridea/gridea#301]
文章:显示 No datas
配置的codingpages没了~菜单,标签,几乎我所有的设置都清空了~
但是源文件里的文章都还有,配置也还在,该怎么恢复呢~
我怀疑是因为我在没联网的情况下打开软件导致软件崩溃的~
望回复~望恢复~

**Comment by EryouHao** [comment]
有没有在软件导入过 markdown 文件？（手动拷贝到 posts）文件夹

**Comment by 1042970366** [comment]
> 有没有在软件导入过 markdown 文件？（手动拷贝到 posts 文件夹）

哇哦,谢谢大佬,已经正常打开了,昨天导入的时候没反应,没在意,结果今天一打开就凉凉,原来是昨天导入md的锅...不过说到这了,希望大佬可以开发一下导入功能,毕竟以前写的很多md文件图片很多,一个个导入实在太麻烦了~

**Comment by hayschan** [comment]
所以请问是怎样解决的呢？我在macOS也遇到同一个问题

**Comment by fangsii** [comment]
> 
> 
> 所以请问是怎样解决的呢？我在macOS也遇到同一个问题

删掉你手动导入的那个md文件就ok了

**Comment by 1042970366** [comment]
> 所以请问是怎样解决的呢？我在macOS也遇到同一个问题

删掉你自己导入的md就好了~不知道mac的是不是这样子..
