### ISSUE TITLE
feat: 新增 Valine 评论系统，PR 请求

### ISSUE THREAD

**Issue by zgm4z** [getgridea/gridea#302]
# PR
#303 
# 动机
想要一个不需要登录即可评论的评论系统
# 影响范围
除了内置的四款主题，新开发的主题均需要添加新代码适配。
# 引入的依赖
[Valine](https://valine.js.org/) - 一款快速、简洁且高效的无后端评论系统。
Valine 诞生于2017年8月7日，是一款基于LeanCloud的快速、简洁且高效的无后端评论系统。
理论上支持但不限于静态博客，目前已有Hexo、Jekyll、Typecho、Hugo、Ghost 等博客程序在使用Valine。
# 效果预览
<img width="912" alt="屏幕快照 2019-09-25 下午3 17 38" src="https://user-images.githubusercontent.com/8686411/65578072-b1617f00-dfa7-11e9-8621-75eb40a3b4f7.png">
<img width="912" alt="屏幕快照 2019-09-25 下午3 17 59" src="https://user-images.githubusercontent.com/8686411/65578084-b6263300-dfa7-11e9-9f2a-dfc8b417d452.png">

**Comment by EryouHao** [comment]
其实评论部分感觉该搞到主题中去的，因为无法保证每个主题都适配多个评论系统。这个当初将两个评论系统放到了 Gridea 中其实也是感觉有待考虑的。

**Comment by zgm4z** [comment]
> 其实评论部分感觉该搞到主题中去的，因为无法保证每个主题都适配多个评论系统。这个当初将两个评论系统放到了 Gridea 中其实也是感觉有待考虑的。

我在做的时候也考虑到这个问题，如果以后评论系统变动每个主题都要改，我认为应该把评论的部分放到渲染的时候根据配置文件直接渲染评论系统的相关文件，主题只需使用一个统一的指令就可以输出评论模代码嵌入带页面中，参考 Hexo 那样的模式

**Comment by Alicyu1024** [comment]
> > 其实评论部分感觉该搞到主题中去的，因为无法保证每个主题都适配多个评论系统。这个当初将两个评论系统放到了 Gridea 中其实也是感觉有待考虑的。
> 
> 我在做的时候也考虑到这个问题，如果以后评论系统变动每个主题都要改，我认为应该把评论的部分放到渲染的时候根据配置文件直接渲染评论系统的相关文件，主题只需使用一个统一的指令就可以输出评论模代码嵌入带页面中，参考 Hexo 那样的模式 @EryouHao

你做的这个PR有合并到主分支吗? 一直很想用Valine评论系统. 如果能集成到配置选项里面那就很方便了.

**Comment by zgm4z** [comment]
> > > 其实评论部分感觉该搞到主题中去的，因为无法保证每个主题都适配多个评论系统。这个当初将两个评论系统放到了 Gridea 中其实也是感觉有待考虑的。
> > 
> > 
> > 我在做的时候也考虑到这个问题，如果以后评论系统变动每个主题都要改，我认为应该把评论的部分放到渲染的时候根据配置文件直接渲染评论系统的相关文件，主题只需使用一个统一的指令就可以输出评论模代码嵌入带页面中，参考 Hexo 那样的模式 @EryouHao
> 
> 你做的这个PR有合并到主分支吗? 一直很想用Valine评论系统. 如果能集成到配置选项里面那就很方便了.

目前还没有，如果需要你可以直接使用我的 fork 自行构建
