### ISSUE TITLE
检测远程连接失败

### ISSUE THREAD

**Issue by menggus** [getgridea/gridea#305]
提示信息:
      远程连接失败,请检查仓库,用户名和Token的设置;
      我检测好些遍了, 还是失败

**Comment by EryouHao** [comment]
https://gridea.dev/docs/faq.html

**Comment by taoL2018** [comment]
查看了开发者提示错误信息:
{message: "fatal: 不是一个 git 仓库（或者直至挂载点 / 的任何父目录）↵停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）

**Comment by EryouHao** [comment]
output 文件夹外层是不是有 `.git/` 文件夹？

**Comment by taoL2018** [comment]
Gridea文件夹下是没有的, 但是我之前用过git, 所以在其他目录下有

**Comment by taoL2018** [comment]
这个是不是涉及到git管理多个仓库情况?

**Comment by EryouHao** [comment]
不是，不太清楚你的这个情况，之前有遇到过外层有 .git/ 目录的，删除即可。 `output/` 文件夹父文件夹，直至根文件夹

**Comment by taoL2018** [comment]
恩, 谢谢啦!!! 我去另外环境试一试

**Comment by tianhao98** [comment]
配置好git环境变量后，windows用管理员打开软件就可以了
