### ISSUE TITLE
标题为纯字符时 URL 自动生成失败

### ISSUE THREAD

**Issue by ouluqiang** [getgridea/gridea#308]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   w10   |
| 软件版本 |   0.8.3   |
| 主题名称 |   Simple   |

---

## 期望行为

编辑文章界面显示正常
## 当前行为

我因为没想好标题，就随便输入了。。。      3个句号，然后写完文章保存，预览跟同步都是没问题的，可以正常显示，但是我再打开这个文章编辑的时候标题跟内容都没有了
![image](https://user-images.githubusercontent.com/12438398/65751628-b48e7380-e13d-11e9-8d10-8acbb171a462.png)

**Comment by EryouHao** [comment]
这是一个 bug，目前用纯符号的标题生成的 URL 为空，可暂时通过手动设置 URL 解决，或不使用纯字符的标题名称

![image](https://user-images.githubusercontent.com/17328747/65752900-5f079600-e140-11e9-8b80-3d7572958363.png)

**Comment by EryouHao** [comment]
想了一下还是手动设置 URL 或采用 shortId 形式来进行文章 URL 生成，纯标点字符无法生成 URL，Gridea 是基于文件来做的文章存储与读取操作。
