### ISSUE TITLE
feat: 添加文章密码保护

### ISSUE THREAD

**Issue by qyxtim** [getgridea/gridea#309]
## 添加文章密码保护

在Gridea编辑器里设置密码，访问文章需要输入密码

## 动机

有时候一些文章不方便所有人都看到，所以想要设置密码保护

觉得可以像这样设计一下：
https://www.jianshu.com/p/a2330937de6c

**Comment by EryouHao** [comment]
纯静态博客无法实现。

**Comment by EryouHao** [comment]
可能没有计划加入这个 feature

**Comment by zgm4z** [comment]
> ## 添加文章密码保护
> 在Gridea编辑器里设置密码，访问文章需要输入密码
> 
> ## 动机
> 有时候一些文章不方便所有人都看到，所以想要设置密码保护
> 
> 觉得可以像这样设计一下：
> https://www.jianshu.com/p/a2330937de6c

我正在我的分支上做这个功能

**Comment by lsl013** [comment]
mark一下，有后续进展，请@我

**Comment by dhyNightWind0311** [comment]
有进展了吗？

**Comment by via-labs** [comment]
有进展了嘛？
