### ISSUE TITLE
katex.min.css加载一分钟

### ISSUE THREAD

**Issue by senup** [getgridea/gridea#310]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   windows   |
| 软件版本 |  0.8.3    |
| 主题名称 |    simple  |

---

## 当前行为

![mark](http://img.xuetao.co/blog/20191001/cKiSaR3EiqeP.jpg?imageslim)
https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css
这个css电脑加载十分缓慢，请问如何解决？

**Comment by YuukoIchihara** [comment]
我也是这个问题 国内加载失败 必须要挂梯子才行

**Comment by EryouHao** [comment]
可以把 css 搞到主题中去，若是用不到 KaTeX 语法，可以删除。

**Comment by xyoung10** [comment]
> 可以把 css 搞到主题中去，若是用不到 KaTeX 语法，可以删除。

还是不太懂该怎么解决呢
有没有具体一点的操作方法？

**Comment by xyoung10** [comment]
> 可以把 css 搞到主题中去，若是用不到 KaTeX 语法，可以删除。

还是不太懂该怎么解决呢
有没有具体一点的操作方法？

**Comment by xyoung10** [comment]
> > 可以把 css 搞到主题中去，若是用不到 KaTeX 语法，可以删除。
> 
> 还是不太懂该怎么解决呢
> 有没有具体一点的操作方法？

自问自答（
可以到Gridea\themes\simple\templates\_blocks\head.ejs里把这句话注释掉
