### ISSUE TITLE
请问如何更改编辑器的显示字体，改编标签的排序

### ISSUE THREAD

**Issue by moonaileen** [getgridea/gridea#313]
您好，
最近尝试了下gridea，感觉非常不错。
但是有一点点疑问，请问该怎么更改内置文章编辑器的显示字体呢？
在我的windows上显示的效果不是很好，想请教一下是否支持修改😂

**Comment by EryouHao** [comment]
目前不支持修改，争取下个版本优化一下 windows 显示

**Comment by moonaileen** [comment]
好的好的，感谢作者大大！
怪不得我还尝试着在win上安装了苹方字体，结果并没有什么效果🤣

**Comment by EryouHao** [comment]
新版本已经优化了 windows 字体显示
