### ISSUE TITLE
URL改为小写后文章消失

### ISSUE THREAD

**Issue by xxxuuu** [getgridea/gridea#325]
## 重现步骤
1. 新建文章，URL为TEST
2. 修改文章URL为test
3. 文章消失

## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 | macOS 10.14.6     |
| 软件版本 |   v0.8.3   |
| 主题名称 |  所有主题均有此问题    |

---

## 期望行为
URL被成功更改

## 当前行为
文章消失

**Comment by EryouHao** [comment]
fixed
