### ISSUE TITLE
require.extensions is not supported by webpack. Use a loader instead.

### ISSUE THREAD

**Issue by 1166544** [getgridea/gridea#329]
WARNING  Compiled with 7 warnings                                                                                                                                                       20:04:47

 warning  in ./node_modules/less/lib/less-node/plugin-loader.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/less/lib/less-node/plugin-loader.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/less/lib/less-node/file-manager.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/less/lib/less-node/file-manager.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/express/lib/view.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/ejs/lib/ejs.js

require.extensions is not supported by webpack. Use a loader instead.

 @ ./src/server/renderer.ts 5:0-22 327:18-21 377:12-15 424:12-15 457:14-17 521:16-19
 @ ./src/server/app.ts
 @ ./src/background.ts
 @ multi ./src/background.ts

 warning  in ./node_modules/ejs/lib/ejs.js

require.extensions is not supported by webpack. Use a loader instead.

 @ ./src/server/renderer.ts 5:0-22 327:18-21 377:12-15 424:12-15 457:14-17 521:16-19
 @ ./src/server/app.ts
 @ ./src/background.ts
 @ multi ./src/background.ts

**Comment by EryouHao** [comment]
你这是在本地开发模式看到的吧，可忽略，不影响开发调试
