### ISSUE TITLE
未找到相关的 Issues 进行评论 请联系******* 初始化创建

### ISSUE THREAD

**Issue by desti-nation** [getgridea/gridea#33]
用Gittalk评论，每次发布文章后就会出现这个，显示不出来评论框

**Comment by EryouHao** [comment]
是的，这个是 Gitalk 的机制，必须初始化创建一下才行，所以，目前发新文章还是需要初始化一下。

**Comment by caosbad** [comment]
使用组织类型的 repo 进行网站搭建，创建了组织的应用并配置了 Gitalk 但显示无法 找到 Issues 。


抓了一下包发现有个配置后的请求，能够获得响应，但返回空值，不知道是不是配置生成的时候出现的问题，求教~

`https://api.github.com/repos/PolkaFans/polkafans.github.io/issues?client_id=+Iv1.d0acc4xxxxxxx&client_secret=&labels=Gitalk,%2Fpost%2Ftest%2F&t=1559867432666`

**Comment by web-kubor** [comment]
怎么初始化创建

**Comment by EryouHao** [comment]
> 怎么初始化创建

登录即可
