### ISSUE TITLE
同步成功但是博客网站浏览毫无变化

### ISSUE THREAD

**Issue by Zfqwb** [getgridea/gridea#337]

**Comment by Mytoolsblog** [comment]
![1](https://user-images.githubusercontent.com/57204618/67921039-60196080-fbe1-11e9-9b0f-32e9d4e948c5.png)
![2](https://user-images.githubusercontent.com/57204618/67921040-60b1f700-fbe1-11e9-8448-b7d8f0c9b826.png)
![3](https://user-images.githubusercontent.com/57204618/67921041-60b1f700-fbe1-11e9-954b-1408b4bb5aa3.png)

**Comment by Eternal0527** [comment]
显然你需要刷新你的浏览器，如果预览没有问题，那么你需要养成清除浏览器缓存的习惯。

**Comment by x956606865** [comment]
大概率是缓存问题，因为全是静态页面，优先击中缓存后就会直接渲染缓存的页面，我之前也经常遇到这个问题
