### ISSUE TITLE
markdown 强调 不明显

### ISSUE THREAD

**Issue by desti-nation** [getgridea/gridea#34]
主题：notes
markdown代码：
![](http://ww1.sinaimg.cn/large/005RSrWrly1g1uh5d09rij30i607amyb.jpg)
实际效果：
![](http://ww1.sinaimg.cn/large/005RSrWrly1g1uh4pl13lj30ib07rjsp.jpg)

**Comment by EryouHao** [comment]
notes 主题这部分的渲染已经优化
