### ISSUE TITLE
emoji 显示不全，怎么配置？

### ISSUE THREAD

**Issue by mikusjelly** [getgridea/gridea#341]
使用Gridea-0.8.3.AppImage，emoji好多都是一个长方形，请问怎么配置？

![Screenshot](https://user-images.githubusercontent.com/2801072/68104958-003ff400-ff18-11e9-9580-f165ef5581a0.png)

**Comment by EryouHao** [comment]
不太清楚你这是什么系统，如果不显示的话，就是系统不支持了

**Comment by mikusjelly** [comment]
OK，了解。我这个是MX Linux。
