### ISSUE TITLE
markdown 解析出来的 table 没有格子

### ISSUE THREAD

**Issue by pkwenda** [getgridea/gridea#343]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   macos   |
| 软件版本 |    0.8.3  |
| 主题名称 |    space  |

---

## 期望行为

期望有格子

## 当前行为

![image](https://user-images.githubusercontent.com/14212375/68134646-6733cc00-ff5d-11e9-8cda-5102fda225ef.png)

没有  border ，用的  space 这个第三方主题

**Comment by EryouHao** [comment]
这个是主题的原因 [Gridea Theme Space](https://github.com/GalaxySuze/gridea-theme-space)
