### ISSUE TITLE
预览的时候正常，上传之后就不正常了

### ISSUE THREAD

**Issue by wangkai9799** [getgridea/gridea#349]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 | mac os 10.15 |
| 软件版本 | 0.8.3 |
| 主题名称 | Simple |

---

## 当前行为

预览正常
![image](https://user-images.githubusercontent.com/34116538/68540116-0de9f380-03c8-11ea-8306-b9c349fd9294.png)

上传之后不正常
![image](https://user-images.githubusercontent.com/34116538/68540120-307c0c80-03c8-11ea-998e-417fae8a7f87.png)

上传之后我也等了好久，还是没有变
域名也是设置的HTTPS

**Comment by EryouHao** [comment]
域名配置写 `https://wangkai9799.github.io`
