### ISSUE TITLE
每次同步的时候能否不清空CNAME

### ISSUE THREAD

**Issue by desti-nation** [getgridea/gridea#35]
自己做了域名解析，创建了CNAME文件，每次用Hve同步之后，CNAME文件就没有了~
![](http://ww1.sinaimg.cn/large/005RSrWrly1g1w7z4bhogj30im0c90ud.jpg)

**Comment by EryouHao** [comment]
可以在应用中设置CNAME😂

**Comment by desti-nation** [comment]
> 可以在应用中设置CNAME😂

谢谢，考虑的真周到，我疏忽了
