### ISSUE TITLE
feat: 能不能做一个安卓版本呢，这样会更方便

### ISSUE THREAD

**Issue by ghost** [getgridea/gridea#350]

**Comment by EryouHao** [comment]
目前可能没有这个精力做移动端，欢迎贡献代码或想法 😂

**Comment by LiarrDev** [comment]
文章都存储在本地的话做移动端还是不太合适，如果作者将博客做成云存储并开放 API 相信会孵化出一大批移动客户端。

**Comment by imgradeone** [comment]
> 文章都存储在本地的话做移动端还是不太合适，如果作者将博客做成云存储并开放 API 相信会孵化出一大批移动客户端。

@LiarrDev 我觉得可以用坚果云

**Comment by LiarrDev** [comment]
> 文章都存储在本地的话做移动端还是不太合适，如果作者将博客做成云存储并开放 API 相信会孵化出一大批移动客户端。
> 
> @LiarrDev 我觉得可以用坚果云

尽管如此，在 Desktop 下跨平台同步都已觉繁琐  😂
