### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by wx0716** [getgridea/gridea#352]
打开开发者工具显示如下错误
```json
Error: getaddrinfo ENOTFOUND  www.google-analytics.com analytics.ts:53
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60)
```
截图如下：
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/42382254/68653727-4c69e480-0567-11ea-8c5b-a118344323a5.png">

**Comment by EryouHao** [comment]
`www.google-analytics.com analytics.ts:5` 这个错误没关系，这是应用的错误。

你的错误是配置错了，先检查远程链接成功再同步，若不成功，去官网看 faq 解决
