### ISSUE TITLE
【疑惑】客户端-主题-自定义配置右上方的“重置”是对所有自定义配置的重置？

### ISSUE THREAD

**Issue by baobaodz** [getgridea/gridea#353]
希望作者大佬可以增加只是对于当前配置如“颜色”的重置，不然点重置后所有都重置了，我只想重置“颜色”啊

**Comment by EryouHao** [comment]
是对当前所用主题的所有自定义配置重置了，想重置某个颜色，只需要清空对应的输入框即可。
