### ISSUE TITLE
feat: 多站点支持

### ISSUE THREAD

**Issue by imgradeone** [getgridea/gridea#354]
## 概述

一处切换到多个站点。

## 动机

之前我是在 WordPress.com 进行建站的，WordPress.com 提供了多站点支持，让我可以创建多个站点并在一处管理。

## 详细解释

多站点意味着可以使用 Gridea 配置多个网站，网站可以使用不同的配置，但可以在 Gridea 内快速管理。

对于 Gridea 的多站点实现方式，我觉得可以使用多 repo 和多 posts、output 文件夹进行实现，在应用里提供直观的切换。

**Comment by EryouHao** [comment]
目前可以通过切换源文件夹来管理多个网站
