### ISSUE TITLE
关于文章内容显示问题

### ISSUE THREAD

**Issue by xiejiangtian** [getgridea/gridea#355]

**Comment by xiejiangtian** [comment]
您好，我在使用Gridea时碰到如下问题：在用某些主题（主题允许在主页文章标题下显示一部分文章内容）时，在主页文章标题下，显示了文章的所有内容，我对比了相关主题的示例页面，未确定是否是我写的markdown不符合规范，更换多个主题都存在这个问题，整个主页显示了文章所有的内容，而不是一部分，非常不美观，只有在某些主页只显示文章标题的主题下才会美观一些，不知道是哪里的问题。

希望您能解答我的疑问，谢谢~

**Comment by lmm214** [comment]
文章内手动添加 `<!-- more -->`

**Comment by xiejiangtian** [comment]
感谢！
