### ISSUE TITLE
来自Deepin用户的反馈

### ISSUE THREAD

**Issue by Eternal0527** [getgridea/gridea#356]
## 一个奇怪的问题
你好，打扰您了。

我使用的操作系统是`Deepin 15.11`，下载安装的是`Ubuntu/Debian`版本的deb包，安装很顺利，启动之后一切都很棒。在这感谢您的工作，让我这样的懒人也可以实现专注自己的内容。

但这一切都在准备`预览`以及准备`同步`的时候出现了问题。

## 简单排除
  我已经做了下面这些事情，目前仍然不确定这是否个bug。

  - 我已经安装了最新版的 Gridea
  - 我已经搜索了已有的 Issues列表
  - 我已经阅读了 Gridea 的 FAQ：https://gridea.dev/docs/faq.html
  - 我已经查看了上手教程（视频或文字）：https://gridea.dev/docs

## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |Deepin 15.11 |
| 软件版本 |Unbuntu/Debian 0.83x64.deb|
| 主题名称 | Jia |

![image](https://user-images.githubusercontent.com/52904481/69002255-76842380-0926-11ea-9ddf-f4155e5874a3.png)

## 期望行为

  点击`预览`按钮和`同步`按钮期望出现预览界面，及顺利推送。

## 当前行为及故障确认

  - 点击`预览`后，不能自动打开默认浏览器。

  - 点击`同步`后，无法完成推送同步，一直转圈。
![image](https://user-images.githubusercontent.com/52904481/69002197-31132680-0925-11ea-9556-eea051700005.png)

  - 清除浏览器缓存后输入域名查看，网站内容无改变，说明确实未完成推送。

  - 远程连接测试是成功的，token重新生成过，无区别。
![image](https://user-images.githubusercontent.com/52904481/69002204-3f614280-0925-11ea-9ee0-cb5a912e4f8e.png)

  - 存在网络链接，网易云音乐正常工作。
![image](https://user-images.githubusercontent.com/52904481/69002206-4ee08b80-0925-11ea-9ac7-3261313cdbc5.png)

## 为此感到抱歉

  - 作为一个`网络大白`，我深切明白，适配`Linux`是多么繁杂的事情。Windows以及macOS才是主流操作系统，尤其当使用的Linux还不是大多数人用的版本时。

  - 但作为一个经常安装使用各种Linux的小小白，在这里向您推荐Deepin操作系统（如果需要用到Deepin）。它比Ubuntu好在一个点，可以完美使用wine的QQ，官方的Linux版本QQ太老，Ubuntu/Manjaro上移植deepin-wine应用存在各种bug。

  - 作为一个非主流用户恳求您，是否可以处理Deepin上的这个bug，感谢您的付出。

**Comment by superFatDu** [comment]
同为Deepin操作系统，使用0.8.3时可以预览，但是无法同步内容，显示“同步遇到了错误，请查阅FAQ或Issues来寻找解决方案”，望解决。

**Comment by EryouHao** [comment]
新版本已修复，请更新版本使用

**Comment by AlexChan2020** [comment]
Windows用户，显示“同步遇到了错误，请查阅FAQ或Issues来寻找解决方案”，望解决。
感谢您的付出~
