### ISSUE TITLE
无法新建菜单

### ISSUE THREAD

**Issue by zhanpenng** [getgridea/gridea#357]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  mac    |
| 软件版本 |   0.8.3   |
| 主题名称 |   notes   |

---

## 期望行为

添加新的菜单,并能正确的关联路径

## 当前行为

我新增了一个新的菜单`笔记`,并输入了路径`/post/book-note`,也新建了这个文件夹和`index.html`文件.但是我点击预览会把我新建的文件夹删掉,也无法同步
也就是等于我无法建新的菜单

请问是我的姿势不对还是bug

**Comment by zhanpenng** [comment]
而且菜单怎么排序

**Comment by EryouHao** [comment]
不要手动创建文件夹和 index.html 文件。可以将菜单指向谋篇文章，有提供下拉选择使用。

目前排序只能依靠创建顺序
