### ISSUE TITLE
coding同步之后内容没有变化

### ISSUE THREAD

**Issue by ZHANGJICHUAN** [getgridea/gridea#359]
#62  我的环境
| 名称     | 值   |
| 操作系统 |  windows7    |
| 软件版本 |   0.8.3   |
| 主题名称 |  Fly  |

使用的coding
##
之前正常的，自从上次换个主体Tech 修改主体皮肤颜色之后同步一次成功之后，之后再修改主题颜色或者换别的主题显示更新成功，但是网站刷新内容就不会更新，检查了仓库等都是正确的，在coding仓库后台查代码更新了，但是强制刷新网站内容还是没有变化的。
-->
使用github没有出现过此情况

**Comment by liuxu0720** [comment]
同遇到此情况。。。

**Comment by lmm214** [comment]
是coding pages 的问题，把pages删了重开就好了

**Comment by ZHANGJICHUAN** [comment]
是的，删除了重建可以了，不过每次更新都要删除重建头好大。
这个问题好像最近几天才有的，之前没有
