### ISSUE TITLE
文章中插入的图片无法删除

### ISSUE THREAD

**Issue by YangSX21** [getgridea/gridea#36]
文章中插入图片之后，点击预览出现在post-image文件夹下面，如何我就算在文章中去掉了这个文件的引用，post-image里面的图片也不会删掉。

**Comment by EryouHao** [comment]
目前图片只能通过手动删除的方式，后面会考虑优化

**Comment by YangSX21** [comment]
手动删除之后还会重新出现。
另外我想问目前是不是不支持本地图片。

**Comment by EryouHao** [comment]
支持本地图片，手动删除图片是指删除 post-image 文件夹中的图片
