### ISSUE TITLE
大佬，您发布到github release里面的文件名是build后的文件名吗？

### ISSUE THREAD

**Issue by GanZhiXiong** [getgridea/gridea#360]
![image](https://user-images.githubusercontent.com/27394631/69842492-72e58a80-129e-11ea-9ca7-30d3238477d7.png)
大佬，您发布到github release的程序文件名是您build后生成的文件名吗？
如果是，那么怎么配置build后生成的文件名呢？我看您vue.config.js里面也没有配置build生成文件名的规则啊。

还是build后生成的文件，重新手动修改文件名后再上传到github release呢？

**Comment by EryouHao** [comment]
会自动根据 package.json 里面的 name 和 version 进行生成

**Comment by GanZhiXiong** [comment]
明白了，Thanks！
