### ISSUE TITLE
是不是软件没用了，链接不了了

### ISSUE THREAD

**Issue by alenzou** [getgridea/gridea#363]
是不是软件没用了，链接不了了

**Comment by EryouHao** [comment]
没太理解什么意思，梦详细描述一下吗？

**Comment by alenzou** [comment]
跟着教程走，一下子同步网页不对。重建库，有链接不了
![QQ截图20191202194609](https://user-images.githubusercontent.com/58419874/69956934-68e0b780-153c-11ea-9b45-acda159136c5.jpg)

**Comment by alenzou** [comment]
跟着教程走的，建库但是打开***.github.io是404
然后设置开了分支，又能连接你的客户端了
但是同步后网页是乱码的。

从建一个库，换账号了，
跟着教程走的，建库但是打开***.github.io是404
然后设置开了分支，然后就没用，链接不上了

**Comment by EryouHao** [comment]
看 faq 根据具体报错解决下吧 https://gridea.dev/docs/faq.html
