### ISSUE TITLE
logo请求非加密

### ISSUE THREAD

**Issue by wennothing** [getgridea/gridea#366]
在请求logo图片时请求的链接为http非加密的，导致浏览器拦截不安全请求，进而导致整个版面排版有问题。换过一个新主题之后出现，是否为新主题少写个s导致覆盖了正确的配置，换回旧主题也无效。Windows10

**Comment by EryouHao** [comment]
域名配置时写上 https 就可以了？

**Comment by 7xyzing** [comment]
好了，谢谢
