### ISSUE TITLE
检测远程连接正常，点击同步失败

### ISSUE THREAD

**Issue by chensu92** [getgridea/gridea#371]

**Comment by chensu92** [comment]
data: {…}, localBranchs: {…}, message: "remote: Coding 提示: Authentication failed.↵remote: …s://git.coding.net/chensu/chensu.coding.me.git/'
这是开发者工具里的提示，但是我现在连接的github，没有用coding

**Comment by AWhiteMouse** [comment]
我也有同样的问题，请问你是怎么解决的
