### ISSUE TITLE
菜单是干嘛用的？我能把不同的文章放在不同的菜单里吗？

### ISSUE THREAD

**Issue by Freejourney** [getgridea/gridea#378]
菜单是干嘛用的？我能把不同的文章放在不同的菜单里吗？可以的话在哪里设置？(没有看到可以设置的地方)

默认的是全部都放在了archives下面，这个可以调整吗？

**Comment by EryouHao** [comment]
可以通过菜单使用 某个 tag 的链接即可，或者使用自定义页面的功能，通过自定义配置，使用文章数组来管理
