### ISSUE TITLE
Ubuntu 19.10 配置 Coding 报错

### ISSUE THREAD

**Issue by eallion** [getgridea/gridea#379]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   Ubuntu 19.10   |
| 软件版本 |  Gridea 0.8.3    |
| 主题名称 |    Notes  |

---

## 期望行为

期望配置成功。

## 当前行为

Ubuntu 19.10, 配置 Coding 仓库报错：
```
{message: "fatal: 不是一个 git 仓库（或者直至挂载点 /home 的任何父目录）↵停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。↵", success: false}
```

**Comment by eallion** [comment]
### 我讲讲我手动配置的过程

`Ubuntu 19.10` 中 `Gridea` 默认安装在 `/home/YourUserName/Documents/Gridea` 中。
先关闭 Gridea APP，再运行下面的命令。
请勿照搬，其中的`目录`或者 `ID` 或者 `Username` 什么的要改为自己的。
```
cd ~/Documents
mv Gridea Gridea.bak # 把 Gridea 目录备份
```
克隆线上仓库：
```
git clone https://git.dev.tencent.com/[YourCodingID]/[YourCodingID].coding.me.git Gridea 
```
恢复文件：
```
cd Gridea.bak
mv * ../Gridea/
```
然后就是常规 `git` 操作：
```
git add --all
git commit -m "update or something"
git push
```

### 总结

出现这个错误的大概原因是没有初始化或者无法初始化本地`git`仓库吧。
可以直接初始化试试：
```
cd ~/Documents/Gridea
git init
```

**Comment by eallion** [comment]
### Gridea 手动配置 Coding 的过程

`Ubuntu 19.10` 中 `Gridea` 默认安装在 `/home/YourUserName/Documents/Gridea` 中。
先关闭 Gridea APP，再运行下面的命令。
请勿照搬，其中的`目录`或者 `ID` 或者 `Username` 什么的要改为自己的。

```
cd ~/Documents/Gridea
mv output output.bak
```
克隆线上仓库：
```
git clone https://git.dev.tencent.com/[YourCodingID]/[YourCodingID].coding.me.git output
cd output.bak
mv * ../output/
```

然后就是常规 `git` 操作：
```
git add --all
git commit -m "update or something"
git push
```

### 总结

出现这个错误的大概原因是没有初始化或者无法初始化本地`git`仓库吧。
可以直接初始化试试：
```
cd ~/Documents/Gridea/output
git init
```

**Comment by eallion** [comment]
### Gridea 手动配置 Coding 的过程

`Ubuntu 19.10` 中 `Gridea` 默认安装在 `/home/YourUserName/Documents/Gridea` 中。
先关闭 Gridea APP，再运行下面的命令。
请勿照搬，其中的`目录`或者 `ID` 或者 `Username` 什么的要改为自己的。

```
cd ~/Documents/Gridea
mv output output.bak
```
克隆线上仓库：
```
git clone https://git.dev.tencent.com/[YourCodingID]/[YourCodingID].coding.me.git output
cd output.bak
mv * ../output/
```

然后就是常规 `git` 操作：
```
git add --all
git commit -m "update or something"
git push
```

### 总结

出现这个错误的大概原因是没有初始化或者无法初始化本地`git`仓库吧。
可以直接初始化试试：
```
cd ~/Documents/Gridea/output
git init
```

**Comment by eallion** [comment]
[https://blog.eallion.com](https://blog.eallion.com)

**Comment by EryouHao** [comment]
知道问题了，下个版本会修复

**Comment by EryouHao** [comment]
已修复，请使用新版本
