### ISSUE TITLE
在MACOS下不显示文章的

### ISSUE THREAD

**Issue by ted1ore1ee** [getgridea/gridea#38]
已经配置好github的连接，测试部署都没有问题，在新建文章的时候写完了保存也提示保存成功了但是文章这个页面就显示空白了，如图
![image](https://user-images.githubusercontent.com/43397442/56106796-70cff500-5f75-11e9-9ffa-a4377ce42e13.png)
配置连接界面
![image](https://user-images.githubusercontent.com/43397442/56106812-880ee280-5f75-11e9-9951-cdb05c7bde64.png)
点击同步之后，进入xxx.github.io之后只能看到默认文章，刚才写的都没有保存下来，请问这个是什么问题。

**Comment by ted1ore1ee** [comment]
找到原因了，在预览图那里外链多打了一个括号，然后就崩了😂

**Comment by EryouHao** [comment]
ok，解决就好。

我关 issue了，若需要继续解决可重新打开此 issue
