### ISSUE TITLE
Ubuntu 19.10 不能导入文章

### ISSUE THREAD

**Issue by eallion** [getgridea/gridea#381]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   Ubuntu 19.10   |
| 软件版本 |    0.8.3  |
| 主题名称 |    Notes  |

---

## 期望行为

期望导入文章

## 当前行为

 [https://gridea.dev/docs/faq.html#%E5%A6%82%E4%BD%95%E5%B0%86-hexo-%E6%96%87%E7%AB%A0%E5%AF%BC%E5%85%A5-gridea](https://gridea.dev/docs/faq.html#%E5%A6%82%E4%BD%95%E5%B0%86-hexo-%E6%96%87%E7%AB%A0%E5%AF%BC%E5%85%A5-gridea)

手动把 markdown 文章复制到 `~/Gridea/notes`文章夹下，APP 打开没有数据，配置数据也不见了。如图：

- 排除了中文文件名这一原因。
- 排除权限原因。

![FlameShot_2019-12-17_175711](https://user-images.githubusercontent.com/1698841/70985640-644cff00-20f7-11ea-94e8-deb5774bf7f3.png)

**Comment by EryouHao** [comment]
目前只支持 Hexo 类型的（即带有 markdown 头信息的）文件导入
