### ISSUE TITLE
url 设置不按预期

### ISSUE THREAD

**Issue by zema1** [getgridea/gridea#384]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |    MacOS  |
| 软件版本 |    0.8.3  |
| 主题名称 |   Simple   |

---

## 描述

设置 url 为 test.html 后，访问的链接 path 为 `/post/test.html/` 而不是  `/port/test.html`。我看了眼生成的文件，是以  `test.html` 为名称生成了目录，然后下面建立了 `index.html`。

这个行为感觉有点奇怪，导致每篇文章访问时都会造成一次跳转，为何不直接创建 `test.html`?

**Comment by EryouHao** [comment]
因为 path 设置的只是路径，生成时会对应生成对应文件夹，里面有 `index.html`

**Comment by zema1** [comment]
嗯嗯 感谢回复，我个人目前在使用这个来写一点随笔。如果能解决下这个问题最好啦

**Comment by EryouHao** [comment]
新版已支持精简 URL 模式，但是没有支持 ugly url 模式（xxx.html）
