### ISSUE TITLE
源文件没备份，重装系统了，如何同步以前的文章？

### ISSUE THREAD

**Issue by oscar-mx** [getgridea/gridea#387]

**Comment by EryouHao** [comment]
目前没啥好办法了，需要重新 copy 一下网页上的文字了

**Comment by ieeve** [comment]
页面上虽然有一个同步按钮，居然是本地提交覆盖，原先的博客瞬间就被清空，只想给差评

**Comment by wyu0725** [comment]
> 
> 
> 页面上虽然有一个同步按钮，居然是本地提交覆盖，原先的博客瞬间就被清空，只想给差评

这个Issue下面已经有解释，本地的工作区是Geidea的工作区，再不同设备上编辑要同步工作区，而不是github.io这个文件夹。https://github.com/getgridea/gridea/issues/338
