### ISSUE TITLE
部署最新版0.9.0时无法执行同步

### ISSUE THREAD

**Issue by diylifepro** [getgridea/gridea#390]
1、使用最新版 V0.9.0，测试远程连接成功，但是同步时一直转圈，console没有日志输出。
2、更改使用V 0.8.3，成功同步。

**Comment by diylifepro** [comment]
3、V0.9.0点击预览没有反应，V0.8.3点击正常打开本地渲染文件。

**Comment by whzecomjm** [comment]
tg上有人问过, 我让他把output 文件夹内文件全部删除,重新渲染后成功. 你可以试试. (如果要保留git记录不要删 .git 文件夹)

**Comment by diylifepro** [comment]
> tg上有人问过, 我让他把output 文件夹内文件全部删除,重新渲染后成功. 你可以试试. (如果要保留git记录不要删 .git 文件夹)

**Comment by diylifepro** [comment]
> tg上有人问过, 我让他把output 文件夹内文件全部删除,重新渲染后成功. 你可以试试. (如果要保留git记录不要删 .git 文件夹)
现在在用上一个版本，等下一次升级再试试  ；)
