### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by wx0716** [getgridea/gridea#393]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  Mac os    |
| 软件版本 |  0.9.0    |
| 主题名称 |     宋 |

---

## 期望行为
能够连接成功

## 当前行为
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/42382254/71584256-d6d4ca80-2b4c-11ea-8fcb-9daaeefc44f2.png">
出现无法连接到GitHub page，确认所有选项都没有填写错误，最新版本和0.8x版本都无法连接上，忘快速解答！谢谢

**Comment by EryouHao** [comment]
你没有创建仓库

**Comment by wx0716** [comment]
我创建了仓库，而且我不止一次创建了仓库，每次都先删掉然后创建，还是连接不上，token我也是先删了然后再创建，还是无法连接，总是报这个错误！


| |
王鑫
|
|
wx071611@163.com
|
签名由网易邮箱大师定制


在2019年12月30日 23:33，Eryou Hao<notifications@github.com> 写道：

你没有创建仓库

**Comment by EryouHao** [comment]
创建的私有仓库？我看你的 github 上只有 4个仓库，并没有 `wx0716.github.io` 这个仓库？

另外，可以参考 faq 看下具体报错进行解决 https://gridea.dev/docs/faq.html

**Comment by wx0716** [comment]
这是我重新操作了一遍的截图，还是无法连接！




|



|












王鑫
|
|
wx071611@163.com
|
签名由网易邮箱大师定制


在2019年12月31日 09:41，Eryou Hao<notifications@github.com> 写道：

创建的私有仓库？我看你的 github 上只有 4个仓库，并没有 wx0716.github.io 这个仓库？

另外，可以参考 faq 看下具体报错进行解决 https://gridea.dev/docs/faq.html
