### ISSUE TITLE
在标签页点击标签,会把含有同样标签的隐藏的文章也显示出来

### ISSUE THREAD

**Issue by chenimin** [getgridea/gridea#402]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   win10   |
| 软件版本 |   0.9.1   |
| 主题名称 |   Notes   |

---

**Comment by EryouHao** [comment]
是的，新版本会将设置过标签的隐藏文章也显示在标签页，若想彻底隐藏，可移除文章的标签设置
