### ISSUE TITLE
mas系统检测远程连接失败。提示no such remote 'origin'。

### ISSUE THREAD

**Issue by mikumikulch** [getgridea/gridea#403]
检查了所有的配置，和 github 上都是一致的。但是就是报 no such remote 'origin'。

我的仓库：
https://github.com/mikumikulch/ChuckLin.github.io

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/15964712/71955833-600e9000-3224-11ea-8ee2-8d21a1aa90d7.png">

**Comment by hsxyhao** [comment]
no remote一般都是output文件夹的git远程地址没有设置成功，自己手动添加上就行了，具体的操作可以看[这篇博客](https://hsxyhao.github.io/post/gridea-setup/#%E8%B8%A9%E5%9D%91)，在[源码这里](https://github.com/getgridea/gridea/blob/master/src/server/deploy.ts) 可以看见部署的时候会给output设置远程仓库，有兴趣的了解下
希望对你有帮助

**Comment by bnqwxhdmz** [comment]
Mac安装完```gridea```之后是有一个站点源文件路径, 切换到```output```文件夹下, 删除```.git```文件夹, 解决问题

**Comment by mikumikulch** [comment]
> Mac安装完`gridea`之后是有一个站点源文件路径, 切换到`output`文件夹下, 删除`.git`文件夹, 解决问题

按照这个方式解决了问题。非常感谢。

**Comment by fengxtao** [comment]
我试着并不行  ，，放弃了 哎。。

**Comment by xueqian-chen** [comment]
> 
> 
> 我试着并不行 ，，放弃了 哎。。

可以试试以下方案：

**出错原因：**
Gridea\output\.git\config 文件了缺失内容。

**解决方案，在该文件末尾增加以下内容：**
```
[remote "origin"]
	url = https://GitHub用户名:你的Token@github.com/GitHub用户名/GitHub用户名.github.io.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```
其中，把「GitHub用户名」和「你的Token」做相应的替换。

**Comment by qxkbwl** [comment]
win10修改路径：C:\Users\xxxx\Documents\Gridea\output
其中xxx是你的用户名，
删除.git即可

**Comment by Holy-Glory-Alex** [comment]
为什么我的.git删不掉呢？

**Comment by xzy090626** [comment]
为什么每次「检测远程连接」的时候都会更新一次 .git 文件呢？
