### ISSUE TITLE
同步异常提示账号或者密码错误

### ISSUE THREAD

**Issue by yz0812** [getgridea/gridea#405]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  windows 10 专业版    |
| 软件版本 | 最新版本 |
| 主题名称 |    默认主题  |

---

## 期望行为

同步成功

## 当前行为

第一次同步成功,后想更新域名,阿里云解析,再进行远程设置失败.
然后远程设置改回之前配置,正常
然后再同步就控制台提示  remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/yz0812/yz0812.github.io.git/'
再删除阿里云域名解析还是一样同步失败,但是远程设置提示正常

**Comment by yz0812** [comment]
已解决,解决办法刷新github token.虽然我不知道为什么我的token为什么会失效.但是这样还是解决了

**Comment by MNoodle44** [comment]
我也遇到了同样的问题，刷新令牌后解决了！非常感谢~
