### ISSUE TITLE
0.9.0版本置顶功能可以弄两个，按道理置顶的话只能一个

### ISSUE THREAD

**Issue by ITJoker233** [getgridea/gridea#406]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |      |
| 软件版本 |      |
| 主题名称 |      |

---

## 当前行为

![图片](https://user-images.githubusercontent.com/39162691/72221703-072e5700-3598-11ea-935a-defc51deba57.png)

**Comment by EryouHao** [comment]
可以多个置顶
