### ISSUE TITLE
请问可以保留markdown源文件吗

### ISSUE THREAD

**Issue by XboxYan** [getgridea/gridea#41]
如题。

目前都被转换成`html`了

**Comment by EryouHao** [comment]
Markdown 源文件都在你的本地哦，可以看看博客源文件夹`～/Documents/Gridea`（默认）里的 `posts`文件夹

若不知道目录在哪儿，可以看下应用中的 **系统 ->源文件夹**

**Comment by XboxYan** [comment]
哦，本地我倒是知道，之前用github page搭建过，`markdown`是保留在原项目中的。

再问一下，如果换一台电脑，可以从github同步到本地吗

**Comment by EryouHao** [comment]
markdown目前不会同步到仓库，多设备管理博客的话，可参考 https://gridea.dev/docs/faq.html
