### ISSUE TITLE
coding改了新建项目的默认仓库地址

### ISSUE THREAD

**Issue by xuxuzhaozhao2015** [getgridea/gridea#412]
## coding改了新建项目的默认仓库地址
原来默认的地址为：git.coding.net
现在新建仓库的地址为：e.coding.net

绑定到coding会出错。

希望可以将coding的地址做成配置项。
![image](https://user-images.githubusercontent.com/57246874/72318870-7612c980-36d8-11ea-9ed4-118cea7a1a88.png)

**Comment by 850552586** [comment]
所以目前Coding Pages 无法同步...

**Comment by abigmiu** [comment]
原来是这样。

**Comment by Crj0b** [comment]
还有就是coding的密匙用户名是coding随机生成的，与仓库用户名不一致

**Comment by EryouHao** [comment]
#429
