### ISSUE TITLE
Mac 最新版 不能保存配置

### ISSUE THREAD

**Issue by maxmofeng** [getgridea/gridea#428]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   MacOS 10.15.3   |
| 软件版本 |     0.9.1 |
| 主题名称 |      |

---

## 期望行为

github pages 的配置信息不能保存

## 当前行为

配置信息都确认输入了，save 的时候提示保存了，但是重新启动软件后没有任何配置信息，需要重新配置。

![image](https://user-images.githubusercontent.com/9856815/74082666-2933d000-4a97-11ea-9c1a-49dfe770beff.png)

**Comment by EryouHao** [comment]
配置信息没有在这里，在 博客狱源文件夹里呢

**Comment by maxmofeng** [comment]
明白了，选择源文件夹后就可以保存信息了。这个最好说明下，在配置信息之前先设置文件夹。

关闭了
