### ISSUE TITLE
coding 近期改版，个人版自动跳转团队，仓库地址更改，同步失败

### ISSUE THREAD

**Issue by deicol** [getgridea/gridea#429]
| 操作系统 |   w10   |
| 软件版本 |   0.9.1  |
| 主题名称 |    默认  |

---

## 当前行为

coding 近期好像更新了，个人版自动跳转团队，仓库地址更改，同步失败
开发者工具查看 请求地址为 git.coding.net/xxxx 
而团队版地址为 e.coding.net/xxxx

**Comment by deicol** [comment]
https://pic.imgdb.cn/item/5e401beb2fb38b8c3c59f560.png
https://pic.imgdb.cn/item/5e401c0f2fb38b8c3c59fabf.png

**Comment by EryouHao** [comment]
即将到来的新版本会修复

**Comment by Tinsing** [comment]
请问作者，新版本什么时候到来，我迫不及待的想要用coding连接gridea

**Comment by deicol** [comment]
> 请问作者，新版本什么时候到来，我迫不及待的想要用编码连接gridea
可以下载测试版
Gridea（v0.9.2） 测试版
Windows 版：https://c-t.work/s/00209c6db94044
分流: https://www.lanzous.com/i97e0vg
Mac 版：https://c-t.work/s/a2d52b07bcfe49
分流: https://www.lanzous.com/i97g7ba

版本号还是0.9.1 为了后续版本升级提醒 .

**Comment by deicol** [comment]
> 请问作者，新版本什么时候到来，我迫不及待的想要用coding连接gridea

你不加群吗!
QQ群:923131213

**Comment by Tinsing** [comment]
> > 请问作者，新版本什么时候到来，我迫不及待的想要用coding连接gridea
> 
> 你不加群吗!
> QQ群:923131213

ok谢谢你的回复，我这就去试试

**Comment by EryouHao** [comment]
v0.9.2 已修复
