### ISSUE TITLE
客户端添加新文章，文章列表就空白了

### ISSUE THREAD

**Issue by nbuu** [getgridea/gridea#43]
post目录复制比如about.md，然后修改，确可以在文章列表中显示

**Comment by EryouHao** [comment]
可以加群详细看下是什么情况吗？看描述没有看出是什么操作导致的

**Comment by EryouHao** [comment]
当前版本文章标题如果是纯数字的话，会有 BUG，下个版本修复一下，感谢反馈

**Comment by udzhou** [comment]
我写的文章标题为   [小花瓶] 鲜花做成干花，美到爆炸   ，也会出现这种情况，把  [小花瓶]  去掉就好了

**Comment by EryouHao** [comment]
ok, 我需要更多地测试来修复这个问题，抱歉。

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
