### ISSUE TITLE
检测远程连接失败

### ISSUE THREAD

**Issue by AndyZhuAZ** [getgridea/gridea#431]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   MacOS10.15.3 (19D76)   |
| 软件版本 |   0.9.1   |
| 主题名称 |    Minima  |

---

## 期望行为
正常使用

## 当前行为
我的仓库不是新建的，原本是通过webstorm管理正常使用，想试试看gridea。
我确认我的输入没有问题，token也尝试重新生成过，我使用了自定义域名，且开启了https，在域名和仓库中尝试填写了自定义域名和仓库名的所有组合，都不行，在cname中填写仓库的cname内容也没有变化，控制台一直显示如下。
{message: "fatal: No such remote 'origin'↵", success: false}
我在faq的评论区也发现了相同情况的评论，不知道是哪里有问题

我尝试删掉了我的库，重新按照流程创建了新的库，我仅仅为新的仓库创建了readme和cname，甚至重新安装了gridea，问题依旧：{message: "fatal: No such remote 'origin'↵", success: false}，

**Comment by heiybb** [comment]
https://yeming.site/post/gridea-setup/#%E8%B8%A9%E5%9D%91
参考这个试试

**Comment by AndyZhuAZ** [comment]
> https://yeming.site/post/gridea-setup/#%E8%B8%A9%E5%9D%91
> 参考这个试试

谢谢，我尝试了在output目录下git init，还是没有效果，看到文件结构我才意识到问题可能是我用的是jekyll，看来我要新建仓库了。

**Comment by AndyZhuAZ** [comment]
我尝试删掉了我的库，重新按照流程创建了新的库，我仅仅为新的仓库创建了readme和cname，甚至重新安装了gridea，问题依旧，抓狂😫

**Comment by zcybupt** [comment]
> 我尝试删掉了我的库，重新按照流程创建了新的库，我仅仅为新的仓库创建了readme和cname，甚至重新安装了gridea，问题依旧，抓狂😫

可能是代理设置的问题? 我是开着系统代理, 代理模式也是全局, 倒腾了半天以为是git配置有问题, 后来直接切到了 /Applications/Gridea.app/Contents/MacOS 里, 通过proxychains代理Gridea, proxychains4 ./Gridea, 一次性就同步成功了

**Comment by AndyZhuAZ** [comment]
> > 我尝试删掉了我的库，重新按照流程创建了新的库，我仅仅为新的仓库创建了readme和cname，甚至重新安装了gridea，问题依旧，抓狂😫
> 
> 可能是代理设置的问题? 我是开着系统代理, 代理模式也是全局, 倒腾了半天以为是git配置有问题, 后来直接切到了 /Applications/Gridea.app/Contents/MacOS 里, 通过proxychains代理Gridea, proxychains4 ./Gridea, 一次性就同步成功了

proxychains配置好也是一样的效果：{message: "[proxychains] DLL init: proxychains-ng 4.14↵fatal: 没有此远程 'origin'↵", success: false}，倒是返回fatal变成中文了😓

**Comment by EpitomM** [comment]
查看 gridea 文件存储目录：C:\Users\Only\Documents\Gridea\output.git 下的 config 文件，看是否有 [remote "origin"] 信息，如果没有自行添加
[remote "origin"]
	url = https://你的github用户名:Token@github.com/你的github用户/仓库名
	fetch = +refs/heads/*:refs/remotes/origin/*

**Comment by AndyZhuAZ** [comment]
> 查看 gridea 文件存储目录：C:\Users\Only\Documents\Gridea\output.git 下的 config 文件，看是否有 [remote "origin"] 信息，如果没有自行添加
> [remote "origin"]
> url = [https://你的github用户名:Token@github.com/你的github用户/仓库名](https://%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7%E5%90%8D:Token@github.com/%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7/%E4%BB%93%E5%BA%93%E5%90%8D)
> fetch = +refs/heads/_:refs/remotes/origin/_

这样尝试后，控制台提示为：{message: "fatal: invalid refspec '+refs/heads/:refs/remotes/origin/'↵", success: false}

**Comment by EpitomM** [comment]
> > 查看 gridea 文件存储目录：C:\Users\Only\Documents\Gridea\output.git 下的 config 文件，看是否有 [remote "origin"] 信息，如果没有自行添加
> > [remote "origin"]
> > url = [https://你的github用户名:Token@github.com/你的github用户/仓库名](https://%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7%E5%90%8D:Token@github.com/%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7/%E4%BB%93%E5%BA%93%E5%90%8D)
> > fetch = +refs/heads/_:refs/remotes/origin/_
> 
> 这样尝试后，控制台提示为：{message: "fatal: invalid refspec '+refs/heads/:refs/remotes/origin/'↵", success: false}

请检测一下您上面填写的 url 是否可以访问，如果不可访问的话请仔细核对 Token 、github 用户名、仓库名 等信息

**Comment by EpitomM** [comment]
> > 查看 gridea 文件存储目录：C:\Users\Only\Documents\Gridea\output.git 下的 config 文件，看是否有 [remote "origin"] 信息，如果没有自行添加
> > [remote "origin"]
> > url = [https://你的github用户名:Token@github.com/你的github用户/仓库名](https://%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7%E5%90%8D:Token@github.com/%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7/%E4%BB%93%E5%BA%93%E5%90%8D)
> > fetch = +refs/heads/_:refs/remotes/origin/_
> 
> 这样尝试后，控制台提示为：{message: "fatal: invalid refspec '+refs/heads/:refs/remotes/origin/'↵", success: false}

[remote "origin"]
	url = https://EpitomM:fa5ac34bb21acc3b864a4c4fd53474f03619cdbf@github.com/EpitomM/EpitomM.github.io.git
	fetch = +refs/heads/*:refs/remotes/origin/*
fetch 再重新尝试复制粘贴一下，中间有个 *

**Comment by EpitomM** [comment]
> > 查看 gridea 文件存储目录：C:\Users\Only\Documents\Gridea\output.git 下的 config 文件，看是否有 [remote "origin"] 信息，如果没有自行添加
> > [remote "origin"]
> > url = [https://你的github用户名:Token@github.com/你的github用户/仓库名](https://%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7%E5%90%8D:Token@github.com/%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7/%E4%BB%93%E5%BA%93%E5%90%8D)
> > fetch = +refs/heads/_:refs/remotes/origin/_
> 
> 这样尝试后，控制台提示为：{message: "fatal: invalid refspec '+refs/heads/:refs/remotes/origin/'↵", success: false}

重新尝试复制粘贴一下下面这个：
	fetch = +refs/heads/*:refs/remotes/origin/*

**Comment by AndyZhuAZ** [comment]
> > > 查看 gridea 文件存储目录：C:\Users\Only\Documents\Gridea\output.git 下的 config 文件，看是否有 [remote "origin"] 信息，如果没有自行添加
> > > [remote "origin"]
> > > url = [https://你的github用户名:Token@github.com/你的github用户/仓库名](https://%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7%E5%90%8D:Token@github.com/%E4%BD%A0%E7%9A%84github%E7%94%A8%E6%88%B7/%E4%BB%93%E5%BA%93%E5%90%8D)
> > > fetch = +refs/heads/_:refs/remotes/origin/_
> > 
> > 
> > 这样尝试后，控制台提示为：{message: "fatal: invalid refspec '+refs/heads/:refs/remotes/origin/'↵", success: false}
> 
> fetch 部分请按照下面书写，复制回答后 * 丢失了
> ![image](https://user-images.githubusercontent.com/36062843/75599509-847a4080-5ae0-11ea-8714-551a877b749e.png)

成功了，感谢，上面的回复token泄漏了，记得修改😂
