### ISSUE TITLE
点击“检测远程连接”无反应

### ISSUE THREAD

**Issue by EpitomM** [getgridea/gridea#439]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  Windows    |
| 软件版本 |  0.9.1   |
| 主题名称 |  Notes    |

---

## 期望：“检测远程连接” 有响应，站点源文件路径可以保存

1. 第一次配置成功后，第二次打开gridea软件，所有输入框内配置信息都消失了，且再次填入信息后点击“保存”显示保存成功，点击“检测远程连接”无反应，查看console也不输入任何信息。
![image](https://user-images.githubusercontent.com/36062843/74598565-8985cb80-50ae-11ea-8322-a7e8fddaf222.png)
2. 设置站点源文件路径时，每次选择好文件夹后，点击保存后 gridea 会重启
![image](https://user-images.githubusercontent.com/36062843/74598586-c18d0e80-50ae-11ea-834f-011ef425a9c4.png)

gridea 重启后设置好的站点路径又会消失。
![image](https://user-images.githubusercontent.com/36062843/74598588-c94cb300-50ae-11ea-9275-51772a1bb791.png)

曾尝试卸载 gridea 后重装，以上问题仍然存在。

**Comment by sdannyzfr** [comment]
之前我也遇到这个问题，后来下载0.9.2版本解决了
Gridea（v0.9.2） 测试版
Windows 版：https://c-t.work/s/00209c6db94044
分流: https://www.lanzous.com/i97e0vg
Mac 版：https://c-t.work/s/a2d52b07bcfe49
分流: https://www.lanzous.com/i97g7ba

**Comment by EryouHao** [comment]
新版本（v0.9.2）已发布，可使用新版本试一下

**Comment by EpitomM** [comment]
新版本试用，问题已解决。
