### ISSUE TITLE
为什么git clone 的Chic新主题在设置中一直出不来呢？

### ISSUE THREAD

**Issue by StevenJokes** [getgridea/gridea#444]
为什么git clone 的Chic新主题在设置中一直出不来呢？重启软件好多次了，也不见效
![image](https://user-images.githubusercontent.com/25657787/74718246-cb5c7080-526c-11ea-8b62-cd2625b58bed.png)
![image](https://user-images.githubusercontent.com/25657787/74718320-f34bd400-526c-11ea-8562-30eeca711baa.png)

**Comment by wxufei** [comment]
同问

**Comment by wxufei** [comment]
回去试了Mac端客户端，问题解决了

**Comment by StevenJokes** [comment]
哈哈哈，我放OneDrive里，结果变成这个路径了，C:\Users\XXX\OneDrive\文档\Gridea\
