### ISSUE TITLE
数学公式无法正确渲染

### ISSUE THREAD

**Issue by iondex** [getgridea/gridea#45]
发布到Github Pages的博客公式无法正确渲染

![image](https://user-images.githubusercontent.com/4617752/56188988-7141bc00-6059-11e9-94b3-6f5d0ae89c22.png)

**Comment by EryouHao** [comment]
我看了一下你的博客，好像公式渲染出来了？是格式不太对吗？

**Comment by iondex** [comment]
这个不是MathJax渲染的结果吧？还是现在还没有支持MathJax？

另外yuan'wen'jian源文件中第二个公式是下标，而不是上标。如下图所示：

![image](https://user-images.githubusercontent.com/4617752/56195758-21b6bc80-6068-11e9-85f5-9b61491b6b91.png)

**Comment by EryouHao** [comment]
目前提供的公式渲染引擎是 [Katex](https://katex.org/)

**Comment by dreamhomes** [comment]
公式渲染效果不太好， 希望作者能够再美化一下哦。加油！

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)

**Comment by Luoyayu** [comment]
Katex 部分渲染与预期不符
`$\ne$` 或者 `$\neq$` 会被错误解析成 `<span class="mrel"></span>`
预期应该为 `≠`
