### ISSUE TITLE
feat:希望可以增加对markdown格式总toc目录的支持 

### ISSUE THREAD

**Issue by zdylzdyl** [getgridea/gridea#452]
## 概述
  对这个新功能的一段描述：希望想一般typora一样，添加[toc]即可看见文件目录

## 动机

一般文档都需要目录的支持，github有开源的项目，集成较为方便
https://github.com/ekalinin/github-markdown-toc
https://github.com/houbb/markdown-toc
## 详细解释

为文档添加目录的支持，至少可以在添加[toc]时自动生成目录的结构

**Comment by yyl125** [comment]
试试 @[TOC]
