### ISSUE TITLE
mac os 安装客户端失败

### ISSUE THREAD

**Issue by fanmucc** [getgridea/gridea#464]
mac os 安装客户端失败

**Comment by FuNian788** [comment]
同上，未验证的开发者，故安装后无法打开应用

**Comment by EryouHao** [comment]
进入到系统「应用程序」，然后右键打开即可
![image](https://user-images.githubusercontent.com/17328747/102850377-52154780-4454-11eb-87b7-0d44f807e7a6.png)

**Comment by YangQing-Lin** [comment]
> 进入到系统「应用程序」，然后右键打开即可 ![image](https://user-images.githubusercontent.com/17328747/102850377-52154780-4454-11eb-87b7-0d44f807e7a6.png)

问题依然存在
<img width="400" alt="image" src="https://github.com/user-attachments/assets/b6e3e6b9-b82b-49a7-aeb0-526388e88ed4" />
