### ISSUE TITLE
升级 vue-cli-plugin-electron-builder 到 v1.2.0，可以减小打包文件体积

### ISSUE THREAD

**Issue by chhpt** [getgridea/gridea#47]
避免打包 node_modules 内容，参考 https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/223

个人测试结果，Mac 下打包 DMG 大小为 63M ：

![Xnip2019-04-16_16-36-09](https://user-images.githubusercontent.com/19288423/56194519-c388da00-6065-11e9-95f4-29eddc7273ec.jpg)

**Comment by EryouHao** [comment]
cool, 下个版本试试，感谢建议

**Comment by EryouHao** [comment]
[v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
