### ISSUE TITLE
Mac端上

### ISSUE THREAD

**Issue by objcxiaobai** [getgridea/gridea#49]
按文档把所有配置都弄了，
但是报：远程连接失败，请检查仓库、用户名和 Token 设置

**Comment by EryouHao** [comment]
https://gridea.dev/docs/faq.html 可以参照 windows 的那个查看报错方法，看下详细报错信息。若还是未解决，可加群解决下。

**Comment by EryouHao** [comment]
先关闭了，若有需要可重新打开
