### ISSUE TITLE
gittalk一直出错，没找到Gridea相关文档

### ISSUE THREAD

**Issue by ruxia-TJY** [getgridea/gridea#494]
配置gittalk一直出错，请问有什么文档吗？百度没找到答案，Gridea真是个好软件

**Comment by ruxia-TJY** [comment]
真的希望有一个傻瓜教程，毕竟，我在这方面就是一个傻瓜😂

**Comment by EryouHao** [comment]
https://github.com/gitalk/gitalk

**Comment by S9527** [comment]
> https://github.com/gitalk/gitalk

感谢😂

**Comment by ruxia-TJY** [comment]
> https://github.com/gitalk/gitalk

感谢😂
