### ISSUE TITLE
feat: 代码高亮

### ISSUE THREAD

**Issue by ruxia-TJY** [getgridea/gridea#495]
## 概述
文章内包含的代码高亮显示

写文章经常包含一些代码，使用Gridea时候```c之下没有代码高亮
## 动机
写的文章包含代码，然后一直使用的Typora导出为html是有代码高亮的

我感觉这个功能很有用，虽然可以在一些编辑器编写在截图贴到gridea上，如果很难很麻烦的话就算了

**Comment by nchuxw** [comment]
可以给主题添加highlightjs来实现
官网：<https://highlightjs.org/>
使用方法：<https://github.com/highlightjs/highlight.js>

**Comment by ruxia-TJY** [comment]
> 可以给主题添加highlightjs来实现
> 官网：https://highlightjs.org/
> 使用方法：https://github.com/highlightjs/highlight.js

感谢😂
