### ISSUE TITLE
大佬，我今天弄了一下，文章也是404，我这是第一次用这个软件，没有之前版本的主题软件主题，等了好久都是404

### ISSUE THREAD

**Issue by Houweix** [getgridea/gridea#50]
大佬，我今天弄了一下，文章也是404，我这是第一次用这个软件，没有之前版本的主题软件主题，等了好久都是404

_Originally posted by @Houweix in https://github.com/getgridea/gridea/issues/12#issuecomment-484018673_

我找到问题了，我的文章标题最后加了一个中文的 ‘~’，导致的404，我去掉就好了

**Comment by EryouHao** [comment]
下个版本会增加一下 title 的兼容性
