### ISSUE TITLE
发掘一个bug-类型错误

### ISSUE THREAD

**Issue by Shenxiaoy** [getgridea/gridea#51]
![image](https://user-images.githubusercontent.com/24645974/56282786-8a726780-6142-11e9-834b-357f22098f52.png)

- 标题为number时， 整个应用死掉了

**Comment by EryouHao** [comment]
Duplicate of #43 

感谢反馈

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
