### ISSUE TITLE
feat: 多设备/更换设备后文章同步

### ISSUE THREAD

**Issue by TheKingOfDuck** [getgridea/gridea#526]
## 概述

希望在新版中中考虑一下多设备或者换设备了的同步问题。

## 动机

比如我有两台设备，经常在mac上写东西，但是最近mac坏了我不得不使用win来代替，重新安装再配置一下，同步后文章全没了，能够考虑将将本地的文章配置也同步到github，换新设备时再自动同步下来？

## 详细解释

1.建议在插入图片之后就将图片自动同步到github，以后生成的html文件以及原文件的图片也只使用github上的图片，这样在最终同步文章时速度也会有质的提升。
2.将posts目录下的所有md文件自动同步到github的特定目录，如/markdown/。
3.将正在使用的主题文件同步到github的指定目录。如/theme/
4.将config目录下的除了setting.json之外的json同步到github保存
5.为上述同步到github的除了图片外的文件生成一个hash列表 如posts.json xxxThis-Is-A-Hashxxx 每次同步文章前先下载这个hash列表与本地的进行对比有变动的就同步覆盖上去

工作流程：新安装Gridea后配置完token后自动检测一下目标rep里面是否有这些配置文件，如果有就提示是否下载过来覆盖掉没有内容的。

**Comment by JobsLeeCN** [comment]
> ## 概述
> 希望在新版中中考虑一下多设备或者换设备了的同步问题。
> 
> ## 动机
> 比如我有两台设备，经常在mac上写东西，但是最近mac坏了我不得不使用win来代替，重新安装再配置一下，同步后文章全没了，能够考虑将将本地的文章配置也同步到github，换新设备时再自动同步下来？
> 
> ## 详细解释
> 1.建议在插入图片之后就将图片自动同步到github，以后生成的html文件以及原文件的图片也只使用github上的图片，这样在最终同步文章时速度也会有质的提升。
> 2.将posts目录下的所有md文件自动同步到github的特定目录，如/markdown/。
> 3.将正在使用的主题文件同步到github的指定目录。如/theme/
> 4.将config目录下的除了setting.json之外的json同步到github保存
> 5.为上述同步到github的除了图片外的文件生成一个hash列表 如posts.json xxxThis-Is-A-Hashxxx 每次同步文章前先下载这个hash列表与本地的进行对比有变动的就同步覆盖上去
> 
> 工作流程：新安装Gridea后配置完token后自动检测一下目标rep里面是否有这些配置文件，如果有就提示是否下载过来覆盖掉没有内容的。

非常同意，现在我还没找到从线上同步本地的方法，只能本地同步线上吗？

**Comment by o1f** [comment]
onedrive 
坚果云
百度云盘 
了解一下

**Comment by izumi-sora** [comment]
完了额晚了,呜呜呜
