### ISSUE TITLE
feat: font-awesome 加载过慢

### ISSUE THREAD

**Issue by jinzhijie** [getgridea/gridea#527]
## 概述
希望能自行选择加载来源，或将 `https://use.fontawesome.com/releases/v5.7.2/css/all.css` 替换为 `https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome/css/all.min.css`

此 Issues 与 #525 相似

## 动机
`https://use.fontawesome.com/releases/v5.7.2/css/all.css` 加载极其缓慢，甚至需要 1.5min，拖慢了整个站点的响应速度。

**Comment by jinzhijie** [comment]
也许我应该发到 Simple 主题

**Comment by SteamFinder** [comment]
直接去head.ejs替换即可

**Comment by jinzhijie** [comment]
> 直接去head.ejs替换即可

是的，我已经那么做了
