### ISSUE TITLE
主题Pure main.css 404

### ISSUE THREAD

**Issue by itczh** [getgridea/gridea#532]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  macos 10.15    |
| 软件版本 |  0.9.2    |
| 主题名称 |   Pure   |

---

同步后样式错乱，控制台 main.css 404，查看本地 output/styles 文件夹为空

**Comment by o1f** [comment]
去主题仓库那边反馈 
![](https://file.5ewin.com/forum/20200418/d09ed6b8ce21518322fa0140c833c17a.jpg)
