### ISSUE TITLE
feat: 一堆建议

### ISSUE THREAD

**Issue by LittleSheep2Code** [getgridea/gridea#534]
### 集成 TOC

**希望集成 TOC(自动生成目录)**

### 支持 HTML 模式

**希望推出一个 HTML 的专门模式，因为 Markdown 有一些不支持的地方**

### 优化提升

**希望提升动画优化**

### 双击全屏 (Mac)

**希望增加双击 名称栏 自动全屏**

### 集成 TOC

**有一次我在写一片长文章的时候，没有 TOC ， 要让我手作目录时，有点想骂人**

### 增加 HTML 模式

**有亿此我在写文章时，想动用 CSS，但 Markdown 不支持**

### 提升优化

**有一此我在写文章时，它，卡崩了。还有就是动画太卡了**

### 双击全屏 (Mac)

**有亿此我在写文章时，想半全屏一下，但我只能去上方状态栏点 Zoom 才行**

### 集成 TOC

***-***

### 增加 HTML 模式

**在写作时增加一个按钮，能转化到 HTML 源代码模式**

### 提升优化

***-***

### 双击全屏 (Mac)

**双击名称栏(虽然没有名称)，能自动全屏(是指窗口模式下布满成个屏幕)**

**Comment by EryouHao** [comment]
TOC 可以通过输入 `@[TOC]` 生成
