### ISSUE TITLE
写文章的时候时候可以直接添加tag

### ISSUE THREAD

**Issue by Lucahan** [getgridea/gridea#54]
不然的话，遇到没有的tag，还要专门跑到tag的页面去添加一下，太麻烦了。

**Comment by handbye** [comment]
标签页里面的标签不支持删除吗？

**Comment by EryouHao** [comment]
> 标签页里面的标签不支持删除吗？

@handbye 正在使用的标签不能删除，未使用过的标签可以删除

**Comment by EryouHao** [comment]
@Lucahan 已支持，请下载最新版本进行享用
