### ISSUE TITLE
main.css有问题

### ISSUE THREAD

**Issue by BlackDog-HaHaHa** [getgridea/gridea#555]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   win10   |
| 软件版本 |   0.9.2   |
| 主题名称 |  simple    |

---

## 期望行为

网页显示正常

## 当前行为

网页无法加载main.css
![](https://boyisdead.oss-cn-shanghai.aliyuncs.com/20200504152804.png)
![](https://boyisdead.oss-cn-shanghai.aliyuncs.com/20200504153011.png)

我在GitHub中启用了https，然后他就无法正常显示了，如果我取消掉https，他就能正常显示

我尝试过修改index.html中的红线部分
![](https://boyisdead.oss-cn-shanghai.aliyuncs.com/20200504153251.png)
修改后也能正常访问

如果我想要开启https，正确的做法是什么？

**Comment by 2Jiao** [comment]
@Victor-1999 请问你后来怎么解决的？
