### ISSUE TITLE
部分链接跳转错误

### ISSUE THREAD

**Issue by gaoliang** [getgridea/gridea#56]
本地预览时或 https://xxx.github.io/blog 这样的地址部署时，因为菜单栏链接为 "/" 开头,  会导致跳转失败。

**Comment by EryouHao** [comment]
> 本地预览时或 https://xxx.github.io/blog 这样的地址部署时，因为菜单栏链接为 "/" 开头, 会导致跳转失败。

若是域名为 ` https://xxx.github.io/blog `，则需手动修改菜单对应链接（若是首页、归档页、标签页，重新选则一下就可以了）

**Comment by gaoliang** [comment]
本地预览呢？ 现在是直接打开文件，是不是开一个本地的临时服务器更好一些？

**Comment by gaoliang** [comment]
另外，感觉Pages配置项有些冗余了
![image](https://user-images.githubusercontent.com/18087875/56338245-dde4c400-61db-11e9-8d64-2c2b44b46111.png)
红框里的参数应该可以用两个参数代替吧， 1. GitHub仓库地址, 2. 可选的自定义域名

**Comment by EryouHao** [comment]
> 本地预览呢？ 现在是直接打开文件，是不是开一个本地的临时服务器更好一些？

这个目前没有这个打算，如果有比较好的方案，欢迎 PR 或交流

配置项那个只是把配置粒度拆分了一下，理论上确实可以通过减少参数来实现，不过这个还需要考虑一下。
