### ISSUE TITLE
希望可以增加自定义代码的功能

### ISSUE THREAD

**Issue by xhemj** [getgridea/gridea#560]
## 概述
我希望在我的博客里可以加入自定义代码，方便做一些统计
## 动机
我想在我的博客里加入别的统计代码，如：百度统计，CNZZ，不算子，还有一些我自己写的代码
## 详细解释
希望可以有一个面板可以编辑网页的源代码或者是可以方便自己在主文件里插入外部代码
像百度统计可以设置一个窗口让我们可以填写统计代码然后自动插入网页
但像不算子没有统计编号的就可能要自定义html的功能了，谢谢。

**Comment by o1f** [comment]
这个需要主题支持 .

**Comment by yyl125** [comment]
其实相比等待主题支持，不如直接编辑对应部分的 HTML
