### ISSUE TITLE
关于从源代码编译安装

### ISSUE THREAD

**Issue by AFGXF** [getgridea/gridea#562]
由于网络问题,Github Release下载速度慢

本着Geek精神和中等Typescript水平,粗略看了下代码

然后跑了`yarn;yarn electron:build`

结果提示错误如下
```
...
-  Building modern bundle for production...  
   ⚠️  Tailwind is not purging unused styles because no template paths have been provided.
      If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
      removing unused styles, set `purge: false` in your Tailwind config file to silence
      this warning.
   
      https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
....
ERROR in D:/gridea/src/server/renderer.ts
509:57 Argument of type '(err: any, cssString: Less.RenderOutput) => Promise<void>' is not assignable to parameter of type '(error: RenderError, output: RenderOutput | undefined) => void'.
  Types of parameters 'cssString' and 'output' are incompatible.
    Type 'RenderOutput | undefined' is not assignable to type 'RenderOutput'.
      Type 'undefined' is not assignable to type 'RenderOutput'. 参数类型错误,callback的第二个参数是RenderOutput|undefined
    507 | 
    508 |     const lessString = fs.readFileSync(lessFilePath, 'utf8')
  > 509 |     less.render(lessString, { filename: lessFilePath }, async (err: any, cssString: Less.RenderOutput) => {
        |                                                         ^ 类型错误
    510 |       if (err) {
    511 |         console.log(err)
    512 |       }
...
```
另外建议您升级一下TS版本

官方支持版本为>= 3.3.0 <3.6.0

还是转VScode吧

您的TS技术实在是...有点扎心

类型都不匹配,真的很难看下去

最后,一句忠告:能不用TS就不要用TS,写类型+编译 __不一定会减少多少Debug时间,有可能会造成更多耗费__

**Comment by EryouHao** [comment]
欢迎 PR 来解决这个问题..

**Comment by AFGXF** [comment]
那我就 **直言不讳** 了
1. 用Typescript之前要想想编译和写类型(`any`**不配**做类型)
2. 这种项目用Node不是很合适. C/C++&QT/GTK+可以做到多平台适配,基本上Linux全系,Windows用Cygwin或MSYS2编译完放安装包,Mac OS也可以适配.
3. 我只是个学OI(信息学竞赛)的学生,主力C++,Typescript&Node只是我的兴趣爱好,平时用typescript写写算法伪代码找下C++的感觉.

~~以上大多数都是胡言乱语~~

**Comment by EryouHao** [comment]
先来解决一下你的这个报错问题吧，我猜你是没有执行 `yarn` 命令来安装依赖。如果使用了的话，依赖的版本会按照 yarn.lock 里面锁定的版本进行安装，即 `@types/less` 的版本是 `3.0.0`，而你安装的是 `3.0.1` 所以会报这个错误，详细变更可见：

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/86095c295c12293e763da73c4279743323fb334e

另外关于你说的前两点，回复一下：

1. 是的，使用 TypeScript 尽量不要写 `any`, 原因想必不用多说。不过对于一些特殊场景还是可以考虑放宽 lint 的，比如某些 JS 项目的迁移，在时间紧、部分模块分批迁移的时候，可以酌情考虑使用，以减小影响与 Code Review 的成本（不过待完全迁移之后还是要移除）

2. 实现项目的方法有多种，至于选择哪种技术因素也很多。由于开发者是前端为主，若想实现一个跨平台的客户端，当前来看无疑 Electron 相对合适（无论是从实现成本、社区资源丰富度等）。至于 Electron 平台本身的劣势当然也有。是否合适我觉得是一个综合考虑的事情，开发者技术栈、做这个项目的目的、所选技术的成熟度与社区的活跃度等等。（如果觉得有其他技术实现方式从时间、体验、开发效率等都优于此，欢迎讨论，也欢迎提供 Demo）

另外，关于第一条留言中的「能不用TS就不要用TS,写类型+编译 不一定会减少多少Debug时间,有可能会造成更多耗费」，个人认为和开发者的使用姿势也有关系，如果是一个大型重 JS 的项目，使用 TS 的优势还是很明显的，可能在初期写业务的时候会增加一些定义成本，但是在项目可维护性与多人协作时更有优势。当然也不乏一些直接使用 JS 也可以写的很好的开发者。和不是所有用 jQuery 的人都只写面条代码一个道理

**Comment by AFGXF** [comment]
> 先来解决一下你的这个报错问题吧，我猜你是没有执行 `yarn` 命令来安装依赖。如果使用了的话，依赖的版本会按照 yarn.lock 里面锁定的版本进行安装，即 `@types/less` 的版本是 `3.0.0`，而你安装的是 `3.0.1` 所以会报这个错误，详细变更可见：

没错.我又不听话了.

我把`yarn.lock`删了.

建议您重新生成一遍lockfile,因为有些包的registry定位在npm官网,国内访问速度较慢.

另外`package-lock.json`里的registry都是在npm官网,如果使用`npm install`速度会极慢.

其实那个函数的类型定义可以写成这样:
```typescript
//3.0.0
    render(input: string, callback: (error: Less.RenderError, output: Less.RenderOutput) => void): void;
    render(input: string, options: Less.Options, callback: (error: Less.RenderError, output: Less.RenderOutput) => void): void;
//3.0.1
    render(input: string, callback: (error: Less.RenderError, output: Less.RenderOutput | undefined) => void): void;
    render(input: string, options: Less.Options, callback: (error: Less.RenderError, output: Less.RenderOutput | undefined) => void): void;
//我推荐的方法
    render(input: string, callback: (error: Less.RenderError, output:? Less.RenderOutput ) => void): void;
    render(input: string, options: Less.Options, callback: (error: Less.RenderError, output:? Less.RenderOutput ) => void): void;
```
可选参数和`|`类型运算符很容易混.一般来讲,可选参数会造成undefined未能捕获,而`|`取的是两个类型的共同方法和属性.

不说了我去提PR.

至于您的项目...我也无能为力了.

**Comment by EryouHao** [comment]
项目用的 `yarn`，至于 `package-lock.json` 是由于前几天合并的一个 PR 中提交过来的，我没及时处理，今天刚删了。

另外，目前没太多经历来做依赖更新，故锁版本“保命”，从 commit 的时间看的出来，好久没更了...

佛系更新.

**Comment by AFGXF** [comment]
我又来了.

写了个Demo
```typescript
//index.ts
export default function (a: number, b: number,
    cb: (res?: number, err?: Error) => void) {
    if (b === 0) {
        cb(NaN, Error("Divisor can't be 0"));
    }
    else {
        cb(a / b, undefined);
    }

}
```
```typescript
//test/index.test.ts
import divide from "../";
let global: number = NaN;
divide(1, 1,
    (res, err) => {
        if (err) {
            throw err;
        }
        global = res;
    });
console.log(global);
divide(1, 0,
    (res, err) => {
        if (err) {
            throw err;
        }
        global = res;
    });
console.log(global);
```
在开启`--strictNullChecks`时会编译错误.

那个提交时PR合并过来的

所以我放弃PR了.

这review质量堪忧啊.
