### ISSUE TITLE
能否使用hexo的主题

### ISSUE THREAD

**Issue by Shitong-Cai** [getgridea/gridea#564]
RT
主题是否可以使用hexo的主题呢 非常喜欢这个软件但是已经习惯hexo下的一个主题了 突然改掉不适应 麻烦您了

**Comment by o1f** [comment]
不可以直接使用 ,
需要自己适配修改

**Comment by Shitong-Cai** [comment]
好的

> 不可以直接使用 ,
> 需要自己修改

好的感谢
