### ISSUE TITLE
本地页面渲染没有问题，但是云端页面错误

### ISSUE THREAD

**Issue by rongxinzh** [getgridea/gridea#568]
尊敬的开发者你们好。
我在windows10上正确配置了Geidea，然后尝试着写了第一篇文章，点击同步后，又预览了本地版本，本地版本没有任何问题。
![image](https://user-images.githubusercontent.com/57667010/81695416-2cbf6480-9495-11ea-951c-bc2f677eab84.png)
但是，点击同步后，似乎网站的css没有被正确解析，页面变成这样了。
![image](https://user-images.githubusercontent.com/57667010/81695478-4496e880-9495-11ea-8084-a31b32334905.png)
我查看了网站源代码，那两个关键的CSS都没问题，可以被load，请问是什么原因？很奇怪。。。

**Comment by EryouHao** [comment]
域名配置选择 `https`

**Comment by SaulJWu** [comment]
> 域名配置选择 `https`

是https啊，但是还是异常。
