### ISSUE TITLE
如何添加文章到/archives目录下呢，一脸蒙逼啊

### ISSUE THREAD

**Issue by coooliang** [getgridea/gridea#57]
如何添加文章到/archives目录下，且不显示在首页呢？这个URL搞得我用起来有一点儿蒙逼。。

**Comment by EryouHao** [comment]
`/archives` 是文章归档，会将所有非隐藏在列表的文章按时间顺序进行汇总。

目前机制若想在 `/archives`(归档页)显示的话，则必须在列表（首页）展示

**Comment by gaoliang** [comment]
感觉还是需要个不显示在首页的功能 😂
