### ISSUE TITLE
如何给文章分类

### ISSUE THREAD

**Issue by sduwfc** [getgridea/gridea#572]

**Comment by sduwfc** [comment]
比如说,我想在顶部菜单栏添加一个叫作笔记的选项,点击它就进入分类到笔记这一类的文章

**Comment by yyl125** [comment]
> 比如说,我想在顶部菜单栏添加一个叫作笔记的选项,点击它就进入分类到笔记这一类的文章

可以在「菜单」选项中，添加链接诸如 `/tag/标签id`这样的新菜单来实现

**Comment by SteamFinder** [comment]
在菜单选项中添加标签，然后将文章分类到标签下
