### ISSUE TITLE
CNAME填写多个

### ISSUE THREAD

**Issue by ACZMUX** [getgridea/gridea#579]
RT，如niamia.xyz和www.niamia.xyz应该用何分隔符填入远程选项卡中的CNAME？还是说尚未实现？

之前同步一次删一次我CNAME文件我傻了，看了其它issue才想起来还有这一栏=

**Comment by yyl125** [comment]
你需要一个仓库绑定两个域名？

**Comment by iceytea** [comment]
请参考 Github 文档，你提到的问题和 gridea 无关。。。

印象中是一行一个域名，如：
```
niamia.xyz
www.niamia.xyz
```
