### ISSUE TITLE
能否在Gridea中删除网页图标？

### ISSUE THREAD

**Issue by lutarioriparia** [getgridea/gridea#580]
更改头像时误将图片上传至网页图标处，但我不打算给博客设置图标。在Gridea客户端中没有找到删除网页图标的功能，而直接删除网站目录下的favicon.ico并同步后打开博客仍有图标出现，请问有删除网页图标的方法吗？

**Comment by EryouHao** [comment]
去主题中把用到网页图标的地方删除即可
