### ISSUE TITLE
feat: 多人协作来建设博客

### ISSUE THREAD

**Issue by SteamFinder** [getgridea/gridea#582]
## 概述
添加协同创作功能（类似于Github仓库团队合作）

## 动机
我们有一个小博客，想和朋友一起编辑，已经设置仓库协同，但是Gridea没有协同功能，很麻烦
每次要发给我再上传

## 详细解释
类似于Gihub仓库团队协同，另外的用户使用Gridea也可以独立post文章，原主可以获取他的post同步到本地

**Comment by guugg** [comment]
`Gridea` 相当于是个可视化的"脚本" ;  生成静态的 HTML 文件然后上传的.

👍用类似OneDrive同步 , 应该可以简单实现你的要求;

**Comment by SteamFinder** [comment]
> `Gridea` 相当于是个可视化的"脚本" ; 生成静态的 HTML 文件然后上传的.
> 
> 👍用类似OneDrive同步 , 应该可以简单实现你的要求;

谢谢您的回答！可是如果我把我的Gridea分享给其他人会不会有安全性问题（Gridea的token是我的）

**Comment by guugg** [comment]
> > `Gridea`相当于是个可视化的“脚本”; 生成静态的HTML文件然后上传的。
> > 👍用类似OneDrive同步，应该可以简单实现你的要求;
> 
> 谢谢您的回答！可是如果我把我的Gridea分享给其他人会不会有安全性问题（Gridea的token是我的）

如果还考虑安全性问题那就很难办了阿,直接上服务器吧.

**Comment by EryouHao** [comment]
可以期待一下 Gridea Web～

**Comment by SteamFinder** [comment]
> 可以期待一下 Gridea Web～

好的~感谢dalao辛苦付出！那我就关闭问题了:)
