### ISSUE TITLE
feat: 增加一个按钮，查看博客。

### ISSUE THREAD

**Issue by StevenJokes** [getgridea/gridea#591]
## 概述
增加一个按钮，直接查看博客。

## 动机
方便！省的自己输入地址

**Comment by EryouHao** [comment]
如果有配置了域名的话，左下角有一个 icon 可以跳转的
![image](https://user-images.githubusercontent.com/17328747/84244461-43111c80-ab36-11ea-9986-0a72c79e3c3f.png)

**Comment by qq923340082** [comment]
图片是否可以做一个多选操作，如果图片很多情况下，单选会麻烦。【跪求】
