### ISSUE TITLE
第一次尝试安装后，关联了github已有的项目，结果同步将原项目覆盖了，无法还原

### ISSUE THREAD

**Issue by aipenmanship** [getgridea/gridea#592]
新手，刚下载安装，点同步，提示配置，关联了一个github已有的项目，一同步结果将原来的项目给覆盖了，本地也没有原来的记录，请问有备份或者恢复方法吗

**Comment by EryouHao** [comment]
很抱歉给你造成了损失，目前是无法恢复的。

我们下个版本会在配置页加上提醒⚠️

**Comment by aipenmanship** [comment]
好吧，完蛋～

**Comment by Yuxiaoy1** [comment]
> 好吧，完蛋～

翻前一个commit啊
