### ISSUE TITLE
gridea不支持https访问

### ISSUE THREAD

**Issue by maodou38** [getgridea/gridea#594]
使用CNAME，源CDN使用https访问后，所有静态资源显示使用http，导致无法访问，请修复生成网页头，加上允许https网页中请求http的头。

**Comment by EryouHao** [comment]
域名配置那里选择 https 就可以了

**Comment by maodou38** [comment]
选的就是https，没啥用。自己修改模版加了个头才搞定。github page 被cname访问 https就是不行的，simple主题。



------------------ 原始邮件 ------------------
发件人: Eryou Hao <notifications@github.com&gt;
发送时间: 2020年6月13日 09:54
收件人: getgridea/gridea <gridea@noreply.github.com&gt;
抄送: maodou38 <maodoulove19950815@vip.qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[getgridea/gridea] gridea不支持https访问 (#594)






域名配置那里选择 https 就可以了

**Comment by G-H-Li** [comment]
@maodou38 想请问一下您是怎么修改模板的？
