### ISSUE TITLE
feat: 希望客户端增加“仅push文章”功能

### ISSUE THREAD

**Issue by DomeenoH** [getgridea/gridea#604]
## 概述
希望能够增加客户端中同步的个性化选项，如***仅同步主题设置***，***仅同步posts***等

## 动机
由于我的博客托管在pages，试着在仓库中添加readme.md以及个性化404页后，每次使用客户端同步文章后都会覆盖我的修改，因此希望个性化一下客户端中的上传功能。

**Comment by EryouHao** [comment]
可以把文件放在 static 文件夹就可以了 [release 0.9.0](https://github.com/getgridea/gridea/releases/tag/v0.9.0)

**Comment by DomeenoH** [comment]
> 可以把文件放在 static 文件夹就可以了 [release 0.9.0](https://github.com/getgridea/gridea/releases/tag/v0.9.0)

感谢！
