### ISSUE TITLE
feat: 希望增加 sitemap 功能

### ISSUE THREAD

**Issue by renbaoshuo** [getgridea/gridea#606]
## 概述

希望加入 `sitemap` 功能。

## 动机

方便搜索引擎收录。

## 详细解释

这个就不用解释了吧...

**Comment by yyl125** [comment]
你可以直接将网站的 `域名/atom.xml` 文件提交至 Google 等搜索引擎

**Comment by renbaoshuo** [comment]
> 你可以直接将网站的 `域名/atom.xml` 文件提交至 Google 等搜索引擎

好的，感谢

**Comment by zj1123581321** [comment]
atom.xml 里面的域名没有根据用户的自定义域名来，而是使用了 xxx.github.io。
如果用户自定义了域名，但是 sitemap 提交里的是另外的域名，Google Search Console 会报错。(此位置的 Sitemap 不允许此网址。)
