### ISSUE TITLE
有一些功能上的疑问

### ISSUE THREAD

**Issue by voidspiral** [getgridea/gridea#608]
1.假如我换了一台电脑，接下来想恢复保存的markdown 文件。想接着上一篇文章继续写，该怎么做呢。
 2.如果我在其他电脑上安装配置完gridea后，点了同步，我仓库里的东西就直接被初始化了？这是不是有点不合理呢？
 3.目前来说是否无法做到数据迁移呢。

**Comment by voidspiral** [comment]
1.假如我换了一台电脑，接下来想恢复保存的markdown 文件。想接着上一篇文章继续写，该怎么做呢。
 2.如果我在其他电脑上安装配置完gridea后，点了同步，我仓库里的东西就直接被初始化了？这是不是有点不合理呢？
 3.目前来说是否无法做到数据迁移呢。

**Comment by ganzhilin** [comment]
https://gridea.dev/faq/
我使用的是 坚果云

**Comment by StevenJokes** [comment]
OneDrive同步！参考https://blog.dltech.xyz/post/helloeverybody/
已经PR了：
https://github.com/getgridea/gridea/pull/610/commits/d821f72b233c276136e574424a131c643ca7b607
