### ISSUE TITLE
gitalk  报错

### ISSUE THREAD

**Issue by jianpantx** [getgridea/gridea#61]
编辑文章标题保存后，浏览器打开文章，底下gitalk报错，可能是编辑是改变了url，过长导致

**Comment by EryouHao** [comment]
Gitalk 相关 Issue: [文章标题名不能太长（已解决）](https://github.com/gitalk/gitalk/issues/124)

后面主题会做相关优化

**Comment by jianpantx** [comment]
文章编辑，对url进行了编辑保存，再次编辑文章标题，会修该之前保存的url，这样不好吧，每次重新编辑标题，都要对url重新编辑

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
