### ISSUE TITLE
渲染KaTeX公式不正常

### ISSUE THREAD

**Issue by xyf007** [getgridea/gridea#634]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |Windows 10|
| 软件版本 |0.9.2|
| 主题名称 |Simple|

---

## 期望行为
正常渲染 KaTeX 公式

## 当前行为
KaTeX 源码和渲染后的结果同时出现
![1.png](https://i.loli.net/2020/07/19/Gm7dcfLH6RUz24n.png)
![2.png](https://i.loli.net/2020/07/19/nVaTu9FHQMZmJEG.png)

**Comment by ZhiqiWang** [comment]
我也遇到过这个问题. 应该是特定的theme有问题, 我发现的simple是这样的. 可以用notes或者fly试一下.

**Comment by xyf007** [comment]
> 我也遇到过这个问题. 应该是特定的theme有问题, 我发现的simple是这样的. 可以用notes或者fly试一下.

后来我换了 theme 也好了

**Comment by Gabriel-1023** [comment]
在 C:\Users\{你的用户名}\Documents\Gridea\themes\simple\templates\post.ejs 的<head></head>内加入：
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css">
之后再同步就解决这个问题了
