### ISSUE TITLE
Mac 与 Windows 换行符问题

### ISSUE THREAD

**Issue by truistic** [getgridea/gridea#637]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   Windows 7   |
| 软件版本 |   0.9.2   |
| 主题名称 |   Simple   |

---

## 期望行为

使用 Git 仓库同步博客文件，在 Mac 和 Windows 下同步文件后，config/posts.json 等文件的换行符保持统一。

## 当前行为

使用 Git 仓库同步博客文件，在 Mac 下 push 到仓库，在 Windows 7 下 clone 仓库，打开 Gridea 后，运行 git status，提示 config/posts.json 文件做了修改，查看 diff，"content" 字段内的换行符 "\n" 被替换成了 "\r\n"。

![image](https://user-images.githubusercontent.com/66214997/88179510-a1193f80-cc5e-11ea-8f40-2638ed742522.png)

**Comment by KylinLee** [comment]
这个是Git自动转换换行符的问题，和代码无关，仓库中的代码是lf风格换行符，查看你的git设置，`git config --global core.autocrlf`，结果应该为`true`，执行`git config --global core.autocrlf input`，这样拉取仓库时就不会自动转换了。

**Comment by truistic** [comment]
> 这个是Git自动转换换行符的问题，和代码无关，仓库中的代码是lf风格换行符，clone到Windows上是crlf，说明Git帮你做了转换，查看你的Windows git设置，`git config --global core.autocrlf`，结果应该为`true`，执行`git config --global core.autocrlf input`，这样拉取仓库时就不会自动转换了。

好的，明天我试下
