### ISSUE TITLE
客户端文章列表为空时，无法添加新文章

### ISSUE THREAD

**Issue by tiantsing** [getgridea/gridea#64]
下载客户端后，配置了一番。
1.文章列表中，只保留的隐藏的`关于`文章。
2.使用md编辑软件，编辑`关于`页面后，文章列表中就变成空的了。
3.然后，点击`新文章`按钮，就没有反应了。

**Comment by tiantsing** [comment]
过一段时间后，就又可以使用了。

**Comment by EryouHao** [comment]
我这边按照你说的步骤，走到第二条没有发生变空的现象，不知道现在还有问题吗？

**Comment by tiantsing** [comment]
现在没有了



------------------ 原始邮件 ------------------
发件人: "fehey"<notifications@github.com>; 
发送时间: 2019年4月19日(星期五) 中午12:23
收件人: "getgridea/gridea"<gridea@noreply.github.com>; 
抄送: "田庆"<1015236187@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [getgridea/gridea] 客户端文章列表为空时，无法添加新文章 (#64)




我这边按照你说的步骤，走到第二条没有发生变空的现象，不知道现在还有问题吗？
