### ISSUE TITLE
如何配置第三方主题

### ISSUE THREAD

**Issue by startaprl** [getgridea/gridea#65]
比如我想使用hexo的相关主题

**Comment by EryouHao** [comment]
目前不支持 Hexo 主题，简介中说的第三方主题是说其他开发者开发的主题。未来会考虑做主题转换兼容

**Comment by startaprl** [comment]
> 目前不支持 Hexo 主题，简介中说的第三方主题是说其他开发者开发的主题。未来会考虑做主题转换兼容

好的，谢谢
