### ISSUE TITLE
.git 文件夹变得很大怎么处理?

### ISSUE THREAD

**Issue by xyf007** [getgridea/gridea#653]
现在 .git 文件夹已经有30多 MB 了,博文只有几 MB

**Comment by xyf007** [comment]
已解决

**Comment by lex-1919** [comment]
@xyf007 你好，请问是怎么解决这个问题的？

**Comment by xyf007** [comment]
@lex-1919 我之前删掉图片这一行为始终留在 git 的个历史版本中（就是那个图片没有从 git 里面删除），然后我是用 VSCode 改博客的时候从源代码管理里发现问题，然后删了就好
