### ISSUE TITLE
gridea 是否能导入其他 markdown 文件

### ISSUE THREAD

**Issue by WinMin** [getgridea/gridea#654]
似乎没找到导入其他 写作文档的入口？

**Comment by LiarrDev** [comment]
[如何将 Hexo 文章导入 Gridea](https://gridea.dev/faq/#如何将-hexo-文章导入-gridea)

**Comment by yyl125** [comment]
你可以将 .md 文件移动到 Gridea 源文件的 posts 文件中，文件开头的信息中需要按照下面的形式修改，否则将无法识别：

```
---
title: '演示 Demo'
date: 2019-09-07 00:00:00
tags: [About]
published: true
hideInList: true
feature: 
isTop: false
---
```

`title` 是文章标题，`date` 是文章的创作时间，`tags` 是文章标签（不能用 Hexo 的「分类」），`published` 是文章是否发布，`hideInList` 是文章是否在列表中隐藏，`feature` 是文章的封面图，`isTop` 是文章是否置顶
