### ISSUE TITLE
https 链接会变成 http，从而造成 gitalk 401 (Unauthorized)

### ISSUE THREAD

**Issue by jing2si** [getgridea/gridea#67]
* `https://jing2si.github.io/post/test` 跳转后就变成了 `http://jing2si.github.io/post/test/`
* `https://jing2si.github.io/post/test/` 末尾多一个 **\/** 就不会有这个问题
* http 链接会造成这个错误：`GET https://api.github.com/user 401 (Unauthorized)`，从而引起 gitalk 初始化不成功
* 默认生成的文章链接末尾都没有 **\/**

**Comment by EryouHao** [comment]
我这边用谷歌浏览器测试是没问题的 ，请问您是什么系统和浏览器呢，现在还有这个问题吗

**Comment by jing2si** [comment]
* 系统：`Windows 10 企业版`
* 浏览器：Chrome 73.0.3683.103，Firefox 65.0.1 都有这个问题
* 你生成的链接后面有斜杠 **\/** 么？我这没有斜杠，跳转后就变成 http 了
* 能否链接后面可以再配一个斜杠 **\/**，目前不支持
![GIF](https://user-images.githubusercontent.com/2288824/56458350-16d99000-63b8-11e9-8645-f6b86a709bea.gif)

**Comment by edwardzjl** [comment]
我之前遇到一样的问题，点击文章跳转成了 http
后来在 GitHub 对应的的博客 repository，settings 里勾上 enforce https，然后清除了一下 chrome 缓存就好了。
