### ISSUE TITLE
feat: 可否自定义首页模板

### ISSUE THREAD

**Issue by mzwang828** [getgridea/gridea#671]
## 概述

自定义首页使用的模板，将现在的index页面自定义为其他页面，例如home

## 动机

我想让访客进入网站第一眼看到的是整体的自我介绍（便于找工作😝），而将文章列表放在二级页面比如/home或者/posts

## 详细解释

我想实现的是，访客进入example.com第一眼看到的是一个个人介绍，然后点击 “主页” 菜单进入一个文章列表（默认的index）
我可以修改index模板让主页变成个人介绍，但是因为自定义模板不支持posts，pagination等变量，我没有办法简单的复刻另一个页面作为文章“主页”。
可否让自定义模板也支持posts等变量？

非常感谢您的这个项目!

**Comment by kaiqiangzhao** [comment]
我也遇到了这个问题，不知道你最后是怎么解决的呢?

**Comment by kaiqiangzhao** [comment]
<img width="941" alt="屏幕快照 2020-09-04 下午8 54 56" src="https://user-images.githubusercontent.com/38523576/92241617-19774f80-eef1-11ea-9732-4d939edcb8eb.png">

用了https://github.com/EryouHao/gridea-site的代码 ，点击预览的时候也会报错。
@EryouHao

**Comment by mzwang828** [comment]
@kaiqiangzhao 
我就直接简单粗暴的把用另一个静态网页做主页，然后放了一个链接跳转到gridea的blog，blog就用二级域名

**Comment by kaiqiangzhao** [comment]
@mzwang828 有点机智，但如果用github page的话就没办法了

**Comment by mzwang828** [comment]
@kaiqiangzhao 
还是可以的，我是用个人的github page 当主页，然后blog用项目的github page，然后绑定到二级域名上就可以了
