### ISSUE TITLE
gridea sftp建站

### ISSUE THREAD

**Issue by xyfzkd** [getgridea/gridea#684]
gridea可能缺少一个sftp建站的教程

目前，
有一个域名可以正常解析到服务器
且服务器80端口开放

下载gridea，在远程/SFTP合理配置后检测远程链接和同步都没有问题，在服务器端可以看到同步的文件

但是访问域名却没有反应，检测域名发现503报错，这是没有配置好gridea还是没有配置好服务器

**Comment by yang-xinfu** [comment]
maybe need nginx？

**Comment by xyfzkd** [comment]
yes, it is. THANKS A LOT!!
