### ISSUE TITLE
部分Tag点击后404

### ISSUE THREAD

**Issue by zcybupt** [getgridea/gridea#685]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   macOS 10.15.6   |
| 软件版本 |   0.9.2   |
| 主题名称 |   Walker / Pure   |

---

## 期望行为

点击标签显示带有该标签的文章

## 当前行为

在确定包含该标签的文章数量不为 0 的情况下，点击部分标签会404。但是在本地预览时是正常的，更换主题，重新生成并同步后依然存在该问题。

如[我的博客](https://zcybupt.github.io/tags/)中的“动态规划”标签。

本地预览：

![](https://raw.githubusercontent.com/zcybupt/images/master/PicGo/20200912211501.png)

在线预览：

![](https://raw.githubusercontent.com/zcybupt/images/master/PicGo/20200912211532.png)

**Comment by renbaoshuo** [comment]
你这个应该是用了下划线开头的文件夹名导致的...
在 `Gridea\static` 目录下加个 `.nojekyll` 文件试试

**Comment by zcybupt** [comment]
> 你这个应该是用了下划线开头的文件夹名导致的...
> 在 `Gridea\static` 目录下加个 `.nojekyll` 文件试试

我的路径为 `/Users/zcy/Documents/Gridea` , 并不含下划线, 但是问题确实解决了, 谢谢

**Comment by renbaoshuo** [comment]
> > 你这个应该是用了下划线开头的文件夹名导致的...
> > 在 `Gridea\static` 目录下加个 `.nojekyll` 文件试试
> 
> 我的路径为 `/Users/zcy/Documents/Gridea` , 并不含下划线, 但是问题确实解决了, 谢谢

我的意思是说你生成之后有以下划线开头的文件夹，被 Github Pages 自动忽略了

**Comment by zcybupt** [comment]
> > > 你这个应该是用了下划线开头的文件夹名导致的...
> > > 在 `Gridea\static` 目录下加个 `.nojekyll` 文件试试
> > 
> > 
> > 我的路径为 `/Users/zcy/Documents/Gridea` , 并不含下划线, 但是问题确实解决了, 谢谢
> 
> 我的意思是说你生成之后有以下划线开头的文件夹，被 Github Pages 自动忽略了

明白了，确实有，谢谢
