### ISSUE TITLE
feat: latex的 $$ \begin{} \end{} $$ 格式不支持

### ISSUE THREAD

**Issue by yangsp5** [getgridea/gridea#690]
开发者您好，我发现在gridea中对latex的支持：

* 仅有`$\alpha$`这种形式
* 不支持`$$\begin{align} \alpha \end{align} $$`这种形式
* 请问后续可以补上这种latex的编码吗？
* 数学系的学生需要经常编辑latex，双`$$`的形式会让公示更好看，也可以换行对齐
* 谢谢！

**Comment by Looomo** [comment]
原来这么早就提出来了呀，还是没修复
