### ISSUE TITLE
软件很长时间不更新了

### ISSUE THREAD

**Issue by zllafgafg** [getgridea/gridea#696]
发现这个软件已经很长时间没有更新了，希望尽快更新一下，并增加一些功能。看见有好多issue在反应软件的bug，但是作者也不回复呀，不会是不关注这个软件了吧。
希望以后尽快增加网页版的写博客功能；还有非常需要有从wordpress等导入到gridea的功能呀，要不每篇文章都要自己重新复制粘贴上去非常麻烦，希望尽快增加，谢谢！

**Comment by MrPeterJin** [comment]
同问，原先以为是要手动到官网查看更新但是看到上一次commit尚在8月底……不过更新的话这里建议加入用户友好的博客加密功能

**Comment by EryouHao** [comment]
在准备 Web 版，客户端暂时不太有更新了，后面可能会修复一下严重影响使用的 bug

**Comment by zllafgafg** [comment]
哦，好吧，谢谢开发者，加油开发呀。
