### ISSUE TITLE
求问如何将404错误界面定向到指定网页[如博客首页]

### ISSUE THREAD

**Issue by zllafgafg** [getgridea/gridea#702]
因为之前用过gridea，然后删除过，现在又重新使用了，所以在搜索引擎里搜索博客会有一些失效的错误界面，显示404。我想问一下，我应该怎么把404错误界面定向到博客首页呢？我在客户端里没有找到相关的设置，所以求问，谢谢。[因为自己不懂网页代码，所以如果是把相关代码指令添加到哪个html文件里，还希望高手直接打上来一下，方便复制，谢谢。]

**Comment by EryouHao** [comment]
static 文件夹里的 404.html 页面中，添加一下重定向的 js 代码即可

**Comment by zllafgafg** [comment]
好的，谢谢，明天有时间我去试一下。
