### ISSUE TITLE
Mac最新版本无法同步到 Github 上

### ISSUE THREAD

**Issue by LemonSoldOut** [getgridea/gridea#718]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 | Mac OS     |
| 软件版本 |  v0.9.2    |
| 主题名称 |  Simple    |

---
## 发起 Issue 理由
已查阅了一些人的 Issues，发现他们有一部分是因为 Theme，还有些本身同步不成功（出错）或需要时间进行同步。但是我这边完全没有任何问题，只是无法同步成功。
## 期望行为
文章能够同步到 Github 上，也相当于能在 Github 上找到相应的文件。

## 当前行为
1. 文章可以被本地 localhost:4000 端口访问
2. 文章显示已经成功同步，但是并没有同步到 Github 上，已查阅并没有任何相关文件在我的 Repository 里面
3. 我以为是我在创建完 Repository之后本地添加了 ReadMe.md 文件导致覆盖问题（原谅我可能想多了）
4. 添加完 ReadMe.md 文件之后，我将 Github 与一个域名链接在了一起，然后在软件界面进行域名的填写与同步。
5. 同步完成，Github 里面出现了 CNAME 文件，我觉得应该不是由我新增了 ReadMe.md 文件导致的问题，这 CNAME 文件可以同步，那么其他文件应该也能同步进来。花了十几分钟还是不知道问题出在哪里。

已试过 Win10，下完 exe 格式文件安装完之后居然丢失png 格式的图像文件。。我怀疑这软件针对我 qwq

**Comment by EryouHao** [comment]
我看你的仓库已经有文件了
