### ISSUE TITLE
标题使用[] 时发生错误

### ISSUE THREAD

**Issue by h843882065** [getgridea/gridea#72]
我标题名起为   [git] SSH 和 HTTP 的区别     时,点击保存,返回文章页列表,页面直接为空.不能继续任何操作,在本地目录中直接把该文章的标题改为   git SSH 和 HTTP 的区别  时,文章列表又可以看到了.

**Comment by EryouHao** [comment]
标题解析问题，下版本修复

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
