### ISSUE TITLE
网页版具体何时推出？

### ISSUE THREAD

**Issue by zllafgafg** [getgridea/gridea#720]
请问开发者，网页版具体什么时候能推出呢？有一个具体的时间吗？而且现在看见用户反馈的bug越来越多，自己使用也发现存在一些bug问题，那什么时候客户端也能更新一下？有具体时间点吗，能尽量快一点吗？谢谢。

**Comment by zllafgafg** [comment]
觉得开发者没有切实尽到开发维护的责任，迟迟都没有进展，也不更新软件等等，其实要是开发者确实没有时间和精力的话，也可以招募一些人参与开发软件，因为最重要的是应该让我们广大使用者更加方便，用得更舒心，不是吗。

**Comment by EryouHao** [comment]
「网页版具体什么时候能推出呢？」
目前网页版已经在内测了，如果是之前有在官网加入邮件订阅更新的话，应该已经收到内测链接了。由于还没有完善到可以向外推广的阶段，所以目前还没有公开使用。

「客户端什么时候可以更新一下？」
如果是日常有使用客户端的话，理论上来说应该没有阻碍使用的 bug。大多数 bug 是由于用户网络、电脑系统环境、手动操作文件等引起的；这些暂时没有精力去一一处理 case。

「可以招募一些人参与开发软件？」
README 中有写贡献流程，这个项目是开源的，如果有兴趣和能力的话，可以参与贡献，提交 PR。从贡献者列表可以看到之前也有一些小伙伴参与贡献了。但是发起招募这个事情的话，就没有精力与资金操作了。

如果遇到了什么 bug，可以先搜索看之前有没有其他人遇到同样的问题。解决不了，可以留言。

**Comment by huyunlei** [comment]
就讨厌这种人，这个软件又不是你写的，也没让你花钱，事这么多，人家开源让你写博客容易吗，bbbb啥，有本事你开源一个，你维护一个，

**Comment by huyunlei** [comment]
> 觉得开发者没有切实尽到开发维护的责任，迟迟都没有进展，也不更新软件等等，其实要是开发者确实没有时间和精力的话，也可以招募一些人参与开发软件，因为最重要的是应该让我们广大使用者更加方便，用得更舒心，不是吗。

狗币

**Comment by huyunlei** [comment]
> 觉得开发者没有切实尽到开发维护的责任，迟迟都没有进展，也不更新软件等等，其实要是开发者确实没有时间和精力的话，也可以招募一些人参与开发软件，因为最重要的是应该让我们广大使用者更加方便，用得更舒心，不是吗。

你能看得见吗，你的良心不会痛吗，**哈哈哈，骂死你，我喷死你，**

**Comment by huyunlei** [comment]
> 觉得开发者没有切实尽到开发维护的责任，迟迟都没有进展，也不更新软件等等，其实要是开发者确实没有时间和精力的话，也可以招募一些人参与开发软件，因为最重要的是应该让我们广大使用者更加方便，用得更舒心，不是吗。

心情很好嘛 ，键盘侠我喷死你

**Comment by huyunlei** [comment]
> 觉得开发者没有切实尽到开发维护的责任，迟迟都没有进展，也不更新软件等等，其实要是开发者确实没有时间和精力的话，也可以招募一些人参与开发软件，因为最重要的是应该让我们广大使用者更加方便，用得更舒心，不是吗。

**沙雕**

**Comment by zllafgafg** [comment]
只是想催促一下开发者，和表达自己一点的关于软件bug的不满意，并没有恶意。没想到遇到了一个称呼我为所谓“键盘侠”的键盘侠，你真的应该冷静冷静了。
