### ISSUE TITLE
为什么本地项目文件夹比上传到仓库的容量大了这么多呢？谢谢。

### ISSUE THREAD

**Issue by hihaixiaodai** [getgridea/gridea#727]
![Snipaste_2020-11-30_19-37-54](https://user-images.githubusercontent.com/74773383/100605885-91fc7980-3343-11eb-941e-a352c029f253.jpg)

**Comment by hihaixiaodai** [comment]
![Snipaste_2020-11-30_19-37-54](https://user-images.githubusercontent.com/74773383/100605943-a93b6700-3343-11eb-8b80-dfd73591730b.jpg)

**Comment by LiarrDev** [comment]
因为仓库只上传 output 文件夹

**Comment by hihaixiaodai** [comment]
> 因为仓库只上传output文件夹

谢谢指导。那本地那个\Gridea\output\.git\objects 文件夹好像不能删除啊？删了会不能同步。

**Comment by EryouHao** [comment]
@hihaixiaodai 可以删除整个 .git 文件夹，然后重新点检测远程链接保存后即可同步

**Comment by hihaixiaodai** [comment]
> @hihaixiaodai 可以删除整个 .git 文件夹，然后重新点检测远程链接保存后即可同步

谢谢指导！我去试一下。我发现就是这个文件夹容量大，请问这是个渲染的临时文件吗？请问是不是以后还会随着新增博文又慢慢变大呢？谢谢。

**Comment by EryouHao** [comment]
@hihaixiaodai 这个是用来推送文件到仓库用的文件夹，会随着新增博文慢慢变大，它的作用就是会保留你的提交记录显示到 github 上，如果不需要，可以定期删除
