### ISSUE TITLE
feat: Gridea for iPad，OK？

### ISSUE THREAD

**Issue by Wo-Ki** [getgridea/gridea#737]
## 概述
* Gridea for iPad

* 没啥要求，能在iPad上写东西，加图片，推送到GitHub上，就OK了

## 动机
* 想想，看文章做笔记啥的，用apple pencil，真想
* 偶尔出去或者在路上，想写点东西，还是带着iPad方便呀

* 别问，问就是项目经理老吐气

**Comment by EryouHao** [comment]
试试 web 版？（相信你可以找到链接，或者邮箱我发链接，目前在内测）但是 apple pencil 写写画画不支持，还是打字吧
