### ISSUE TITLE
请问为什么用vercel托管导入之后，只有博客首页是vercel提供的二级域名而博文还是github的旧地址？

### ISSUE THREAD

**Issue by hihaixiaodai** [getgridea/gridea#738]
请问为什么用vercel托管导入之后，只有博客首页是vercel提供的二级域名而博文还是github的旧地址？这也起不到加速作用啊？

难道要在远程设置里的「CNAME」加上vercel提供的二级域名？该怎么加上呢？

我还想保留github博客网站改怎么操作呢？

难道要装两套软件吗？

谢谢。

**Comment by EryouHao** [comment]
不要保留，没啥意义吧？将域名写成自己的 vercel 域名即可
