### ISSUE TITLE
这两天同步一直卡在转圈圈，如何排查故障呢

### ISSUE THREAD

**Issue by doubleLLL3** [getgridea/gridea#740]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   Windows 10   |
| 软件版本 |   0.9.2   |
| 主题名称 |  Next    |

---

## 期望行为

同步成功

## 当前行为
如下图所示，最近两天同步，一直转圈，不动，在本地的output文件有更新，但是好像不完整，然后就一直卡在下图界面，重启程序、重启电脑都没用。
![image](https://user-images.githubusercontent.com/44157339/102681435-40d1fe00-41fc-11eb-841a-0908767d84ee.png)

之前一直可以同步，不过有时候也是卡在这，重启程序就好了，这次不知道如何入手？

**Comment by doubleLLL3** [comment]
找到原因了，Onedrive的bug，导致output文件夹阻塞了，不能更新

**Comment by zjp693** [comment]
所以要怎么做呢

**Comment by zjp693** [comment]
我的问题和你一样耶，所以要这怎么才能解决呢

**Comment by doubleLLL3** [comment]
你也是把博客的文件夹放在onedrive里吗？
你试着把output文件夹里的所有文件全部删除，如果删不干净，就有可能和我是一样的问题。
解决方法：在我的电脑里右键博客文件夹所在的驱动器——属性——工具——检查驱动器错误，然后修复，重启就可以了。

**Comment by zjp693** [comment]
> 你也是把博客的文件夹放在onedrive里吗？
> 你试着把output文件夹里的所有文件全部删除，如果删不干净，就有可能和我是一样的问题。
> 解决方法：在我的电脑里右键博客文件夹所在的驱动器——属性——工具——检查驱动器错误，然后修复，重启就可以了。
 不是，我放在c盘的Gridea文件夹里面，github没有提示回复我，哈哈哈，不好意思，这么久回你

**Comment by zjp693** [comment]
我已经删除了，然后点远程连接文件就又回来了，但还是同步不了，一直转圈圈

**Comment by doubleLLL3** [comment]
可以在客户端渲染后，不用等圈圈转完，直接去output下查看有没有新的commit。
如果有，可以直接手动git push。
