### ISSUE TITLE
feat: 增加编辑截面的滚动条

### ISSUE THREAD

**Issue by MrPeterJin** [getgridea/gridea#749]
## 概述

在编辑Blog内容的时候希望添加测栏滚动条，方便手动定位。
## 动机
退出某篇长文章再进入编辑状态后，总要手动滑动到文章的最底部，希望能够提供滚动条手动定位。
## 详细解释
如同Preview界面一样加上可以手动定位的滚动条。如下图：
![image](https://user-images.githubusercontent.com/51412849/103743937-d7455280-5037-11eb-946f-527034789796.png)

**Comment by EryouHao** [comment]
TODO

**Comment by MrPeterJin** [comment]
Closed due to inactivity.
