### ISSUE TITLE
Mac下  invalid active developer path (/Library/Developer/CommandLineTools 解决办法

### ISSUE THREAD

**Issue by ERICYANYAN** [getgridea/gridea#75]
刚开始用，然后再测试连接的时候就失败了。但是看过数据的确没问题。最后打开开发者模式看了一下报了 这个错 
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), 
missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
最后xcode-select --install 一下就好了，希望可以写入文档

**Comment by 425324438** [comment]
对，我也是碰到这个问题了。谢谢你 @曾雁

**Comment by EryouHao** [comment]
已添加至 [FAQ](https://gridea.dev/docs/faq.html#mac-%E6%A3%80%E6%B5%8B%E8%BF%9C%E7%A8%8B%E5%A4%B1%E8%B4%A5%E6%80%8E%E4%B9%88%E5%8A%9E)，感谢 ❤️
