### ISSUE TITLE
本地更改index.html，用Gridea客户端同步后会覆盖，请问我该怎么让其生效？

### ISSUE THREAD

**Issue by baobaodz** [getgridea/gridea#751]
本地更改的是Gridea\output下的index.html；也通过git提交到了当前分支。用Gridea客户端执行同步后，又变回原来的了。请问该怎么做？

**Comment by margrop** [comment]
output 目录相当于编译后文件，改了也没用- -
建议去 themes 目录下面对于的主题文件夹下，更改 index.ejs 文件
