### ISSUE TITLE
不更新了吗？现在mac启动gridea很慢

### ISSUE THREAD

**Issue by aidancy** [getgridea/gridea#755]

**Comment by voidspiral** [comment]
实话实说，我打算撤了。。。

**Comment by doubleLLL3** [comment]
这个或许能帮到你：[解决Gridea客户端打不开/打开很慢以及同步不了的问题](https://xyz1024.top/post/xzimm60l1/)

**Comment by aidancy** [comment]
> 这个或许能帮到你：[解决Gridea客户端打不开/打开很慢以及同步不了的问题](https://xyz1024.top/post/xzimm60l1/)

可以，总算能正常用了

**Comment by lonbaw** [comment]
可以做到不打开客户端就可以同步吗

**Comment by lonbaw** [comment]
> > 这个或许能帮到你：[解决Gridea客户端打不开/打开很慢以及同步不了的问题](https://xyz1024.top/post/xzimm60l1/)
> 
> 可以，总算能正常用了

链接无法访问了

**Comment by doubleLLL3** [comment]
参考：https://xyz1024.top/post/grideafix/
```
需要对客户端修改

\Gridea\resources\app\index.html

对index.html进行编辑

搜索

https://cdn.headwayapp.co/widget.js

换成新的地址

下面是我的

https://cdn.jsdelivr.net/gh/XYZ1024-alt/CDN/widget.js
```

**Comment by lonbaw** [comment]
> 参考：https://xyz1024.top/post/grideafix/
> 
> ```
> 需要对客户端修改
> 
> \Gridea\resources\app\index.html
> 
> 对index.html进行编辑
> 
> 搜索
> 
> https://cdn.headwayapp.co/widget.js
> 
> 换成新的地址
> 
> 下面是我的
> 
> https://cdn.jsdelivr.net/gh/XYZ1024-alt/CDN/widget.js
> ```

漂亮，非常感谢

**Comment by nanlv11** [comment]
mac里index.html没有这个
只有一句
We're sorry but Gridea doesn't work properly without JavaScript enabled. Please enable it to continue.
