### ISSUE TITLE
按照教程设置自动发布到github pages上，但是打开一片空白，网址是https://omhuaan.github.io/能帮我看下是什么原因吗？谢谢

### ISSUE THREAD

**Issue by oMhuAaN** [getgridea/gridea#756]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 | win10 64     |
| 软件版本 |    最新 |
| 主题名称 |     默认 |

---

**Comment by zhengfan2014** [comment]
都没看见你有一个名为`omhuaan.github.io`的存储库，你是不是看错教程了

教程 ： https://gridea.dev/gridea-start/

**Comment by Lardu** [comment]
用户名.github.io    这个你没有创建吧

**Comment by helloJunyi** [comment]
还没有创建omhuaan.github.io的存储库。大概链接，同步也没有成功。
先看教程。

**Comment by oMhuAaN** [comment]
可能是被运营商屏蔽了，所有github.io都打不开
