### ISSUE TITLE
feat:是否可以加入应用内的教程？

### ISSUE THREAD

**Issue by qingdkj** [getgridea/gridea#758]
## 概述

我希望Gridea可以加入应用内的教程

## 动机

因为github和相关网站在某些时候访问速度缓慢，如果在应用内添加会不会有所改善？

**Comment by china-365vip** [comment]
我没太明白你的意思，在什么应用里添加？

**Comment by z-rx** [comment]
就是，在第一次启动的时候，给出一些使用提示？还有在一些比如说“远程”的界面上 多加一点提示

**Comment by china-365vip** [comment]
> 就是，在第一次启动的时候，给出一些使用提示？还有在一些比如说“远程”的界面上 多加一点提示

直接去官网，难道下载不去官网也该知道在搜索平台上搜索Gridea呀，你要不知道你会下载这个软件？
官网教程都能搜到的，没什么太大的必要

**Comment by qingdkj** [comment]
好的
