### ISSUE TITLE
无法正确解析主题

### ISSUE THREAD

**Issue by TimeInDreams** [getgridea/gridea#761]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 | windows10 1909     |
| 软件版本 |      |
| 主题名称 |   任意主题   |

---

## 当前行为

 远程同步后无法正确解析渲染页面
![image](https://user-images.githubusercontent.com/56781415/105608836-4cf34180-5de0-11eb-8c0b-000db0a07850.png)

**Comment by TimeInDreams** [comment]
已修复，需在远程将http协议改为https

**Comment by china-365vip** [comment]
> 已修复，需在远程将http协议改为https

本身就是你自己的问题，而不是程序
