### ISSUE TITLE
请问Gridea为什么同步成功，仓库名访问之后还是没有更新呢？

### ISSUE THREAD

**Issue by jijiehao233** [getgridea/gridea#764]

**Comment by helloJunyi** [comment]
我看你的库有master，你的意识是不是只是显示：jijiehao233.github.io  Talent Gathering
所以问题是：同步成功，但是页面没显示？
应该是因为github pages 里显示设置错误了

具体设置
1.在github对应的仓库名页面，点击“settings”
2.在“settings”的页面，下拉到“GitHub Pages”的设置，选择“Source”的Brach为“master”，然后点“save”
  （Brach，就是你在Gridea远程设置的分支的名称，两者必须一致。Source选择显示那个分支或不显示none）

**Comment by jijiehao233** [comment]
感谢！终于解决了
