### ISSUE TITLE
按照教程设置后，远程连接成功，保存成功，但是同步不成功

### ISSUE THREAD

**Issue by username123703** [getgridea/gridea#768]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  winodws 10    |
| 软件版本 |  0.9.2    |
| 主题名称 |   simple   |

---

## 期望行为
页面同步后，打开https://coding-pages-bucket-3523414-8335543-12685-496038-1304966184.cos-website.ap-hongkong.myqcloud.com后能够显示部署好的界面

## 当前行为
**远程连接成功，保存成功，但是**同步**不成功**，然后报错。显示：{data: {…}, localBranchs: {…}, message: "HTTP Error: 401 Unauthorized", success: false}
![图片](https://user-images.githubusercontent.com/78686677/107163907-2a1f7a80-69e7-11eb-98bf-c0a1ad47363f.png)

**Comment by mosooocn** [comment]
这个怎么处理的呢？

**Comment by wty-xjtu** [comment]
我也是这个问题

**Comment by Chiaspcn** [comment]
同步遇到了错误，请查阅 FAQ 或 Issues 来寻找解决方案

**Comment by EryouHao** [comment]
v0.9.3 支持设置代理了，同时更改了同步机制，可以试试。

**Comment by mosooocn** [comment]
?
你发的是什么
&nbsp;






 Warm Regards
Jackson
Mosooo Tex
Just socks.

But big difference!


Add             5008 Hutai Road, Shanghai, China
web            www.mosooosocks.com
email         ***@***.***
tel               +1(502)209 8333
whatsapp   +86  1390 1864212
wechat       onesockss
facebook    www.facebook.com/mosooo3
linkedin      https://www.linkedin.com/company/mosoooleggings/
                    
                 Jackson W

  

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "海岛心hey"; 
发送时间: 2022年5月24日(星期二) 晚上11:58
收件人: "getgridea/gridea"; 
抄送: "mosooocn"; "Comment"; 
主题: Re: [getgridea/gridea] 按照教程设置后，远程连接成功，保存成功，但是同步不成功 (#768)

&nbsp;



 
Closed #768 as completed.
 
&mdash;
