### ISSUE TITLE
一直显示远程连接失败

### ISSUE THREAD

**Issue by Ironic-Harase** [getgridea/gridea#771]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  0.92    |
| 软件版本 |   Win10   |
| 主题名称 |  Notes    |

---

## 期望行为

页面同步后，打开可以显示预览的界面

## 当前行为

根据教程一步步设置完成，也改了github pages master，但是还是同步不了。
p2是按照FAQ之后的结果。
![image](https://user-images.githubusercontent.com/79185030/108176346-de827480-713c-11eb-9c0d-04a41ade9abf.png)
![image](https://user-images.githubusercontent.com/79185030/108176426-f8bc5280-713c-11eb-8d79-7022fb5b04d4.png)

**Comment by mosooocn** [comment]
这是什么原因。我目测了一下。可能是梯子不稳定。

**Comment by ChenChenGith** [comment]
我也遇到了同样的问题，不架梯子也无法同步。

**Comment by china-365vip** [comment]
仓库名称就叫这个吗？

**Comment by zjs1224522500** [comment]
有解决办法吗？

**Comment by ChenChenGith** [comment]
> 有解决办法吗？感觉前几天还是好的

你这两天试了么？这两天好像正常了。
之前不行的时候观察到重新启动后的第一次同步一般是成功的。

**Comment by zjs1224522500** [comment]
> > 有解决办法吗？感觉前几天还是好的
> 
> 你这两天试了么？这两天好像正常了。
> 之前不行的时候观察到重新启动后的第一次同步一般是成功的。

昨天失败了，今天成功了。谢谢老哥~

**Comment by zjs1224522500** [comment]
又又又又又又又又又又失败了

**Comment by neverp** [comment]
again
