### ISSUE TITLE
软件卡死，左侧功能键全部显示0项，右侧各项配置清零，开发者选项卡死无法看报错

### ISSUE THREAD

**Issue by voidmaker69** [getgridea/gridea#777]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 | Windows     | 10
| 软件版本 |   Gridea   | 0.9.2
| 主题名称 |   内置   | Note

---

## 当前行为
![image](https://user-images.githubusercontent.com/32128684/109174518-e044db80-77bf-11eb-83ca-886da79ddeb0.png)

##可能原因：我放在了OneDrive的问题？目前软件重新安装也无法解决，仍卡死于这个状态

**Comment by voidmaker69** [comment]
版本 v 0.9.2 主题 Note @voidmaker69

**Comment by pping** [comment]
我遇到过，是因为在posts文件夹手动添加了md，在md文件内加入以下内容后就恢复正常了
`
---
title: 'title'
date: 2021-02-26 17:31:34
tags: []
published: true
hideInList: false
feature: 
isTop: false
---
`
