### ISSUE TITLE
read ETIMEOUT 同步失败&远程连接失败

### ISSUE THREAD

**Issue by HuDaQian** [getgridea/gridea#781]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |    MacOS11.2  |
| 软件版本 |     0.92 |
| 主题名称 |      Simple|

## 当前行为

{message: "connect ETIMEDOUT 13.250.177.223:443", success: false}

**Comment by HuDaQian** [comment]
错误信息：{message: "connect ETIMEDOUT 13.250.177.223:443", success: false}

**Comment by huangyuzhang** [comment]
遇到了一样的问题

**Comment by sadjjk** [comment]
最近出现了同样的问题
有解决的哥们嘛
同步不了了

**Comment by daffupman** [comment]
😭 俺也一样，急啊

**Comment by fyc-1358** [comment]
{message: "connect ETIMEDOUT 13.250.177.223:443", success: false}

**Comment by HuDaQian** [comment]
感觉像是梯子的问题，不开梯子连不上github，打开梯子又没有办法同步。希望增加个发布到本地的功能，然后把本地发布的文件手动同步到github。

**Comment by EryouHao** [comment]
v0.9.3 支持设置代理了，同时更改了同步机制，可以试试。
