### ISSUE TITLE
feat: 适配下 Big Sur 的图标大小以及 Apple Silicon 适配。

### ISSUE THREAD

**Issue by moriwang** [getgridea/gridea#782]
现在的图标大小比其他的大一圈。如图所示

<img width="59" alt="image" src="https://user-images.githubusercontent.com/9151525/109635420-4e551e00-7b85-11eb-9fcc-36c487236513.png">

这是[官方模板](https://developer.apple.com/design/resources/#macos-apps)供参考。

另外，请问现在对 Apple Silicon 的适配怎么样了？

**Comment by badshu** [comment]
作者是不是已经弃坑了

**Comment by moriwang** [comment]
> 作者是不是已经弃坑了

作者去做在线版了，我觉得没什么重大 bug 应该是不会维护了。
