### ISSUE TITLE
Gtihub 新建仓库默认分支不叫master了，叫main

### ISSUE THREAD

**Issue by Taivasjumala** [getgridea/gridea#783]
从 2020 年 10 月 1 日开始，GitHub 上的所有新库都将用中性词「main」命名，取代原来的「master」，因为后者是一个容易让人联想到奴隶制的术语。

**Comment by Taivasjumala** [comment]
提供的教程都默认master，俺刚接触GitHub，可难受死我了

**Comment by howellsky** [comment]
> 从 2020 年 10 月 1 日开始，GitHub 上的所有新库都将用中性词「main」命名，取代原来的「master」，因为后者是一个容易让人联想到奴隶制的术语。
感谢啊，折腾了好长时间终于解决了

**Comment by zhuaiice** [comment]
请问怎么解决这个问题？？谢谢！今天才接触，刚发现这个问题
