### ISSUE TITLE
Gridea同步成功率低。

### ISSUE THREAD

**Issue by fukazora** [getgridea/gridea#786]
有时同步成功，但大部分时间同步失败。检测远程链接可以正常使用。

**Comment by LiaoXiaoB** [comment]
我同步失败但网站上会出来

**Comment by linyuqi9** [comment]
相同问题

**Comment by dittocafe** [comment]
我也一样，同步总是不成功，网站也看不出来。检测远程链接可以正常使用

**Comment by fenghaojiang** [comment]
检测远程连接偶尔也不行

**Comment by yujunyan1216** [comment]
我最近也是这种情况啊啊啊

**Comment by rainlilysp** [comment]
有没有人解决了？我之前成功过一次，就只有一次了……

**Comment by CrimsonEX** [comment]
https://github.com/521xueweihan/GitHub520
问题暂时解决，建议参考这个。

**Comment by EryouHao** [comment]
v0.9.3 支持设置代理了，同时更改了同步机制，可以试试。
