### ISSUE TITLE
Gridea客户端无法同步到GitHub Pages（已解决！！！）

### ISSUE THREAD

**Issue by BonjourYY** [getgridea/gridea#789]
操作系统：Win 7
软件版本：0.9.2
主题名称：imhanjie

报错信息："Client network socket disconnected before secure TLS connection was established"

简述：可以正常预览，但是无法同步到GitHub Pages，第一次点击同步，console控制台提示 无法连接到GitHub。第二次就出现上面的报错信息。点击远程菜单，点击检测远程连接，报错 “远程连接失败，请检查仓库、用户名和令牌设置”，然后我把令牌重新设置过，还是没用。希望作者可以尽快修复。Gridea一直是我最佳的博客写作平台。

<hr />

# 解决方法
## 说明：方法不一定适用于任何人，谢谢。

首先，我一开始的报错提示是这个 "Client network socket disconnected before secure TLS connection was established"
后来，我就去Google，如下是解决方案。

- 按Windows键
- 搜索互联网选项
- 点击“ Internet选项”
- 点击“连接”
- 转到局域网设置
- “在LAN中使用代理服务器”中是否有复选标记？如果是这样，请尝试取消选中它。

按照上面的方法试了一下，检测远程连接是可以了，但是同步还是会报错。并且Ping GitHub 也是Ping不通的。
报错信息变成：connect ETIMEDOUT 140.82.112.4:443（后面的这个IP地址每个人可能不一样）

后来我去站长之家 [http://ping.chinaz.com/github.com](http://ping.chinaz.com/github.com) 
找到了能Ping的上GitHub的地址，编辑Host文件，在最后一行加上 13.229.188.59 github.com
最后，问题就解决了。
每个人情况不一样，可能和你用的VPN也有关系。我之前在Twitter上问过作者，作者说可能是网络问题。
如果上面的方法不适用你，估计只能等作者看看以后会不会修复这个问题了。

**Comment by pping** [comment]
🙁 同步遇到了错误，请查阅 FAQ 或 Issues 来寻找解决方案，我的也用不了了，一直同步失败

**Comment by jonathanqwq** [comment]
我的也是啊

**Comment by jack-ke** [comment]
难顶啊  我开不开VPn  都同步出错

**Comment by maxbad** [comment]
🙁 同步遇到了错误，请查阅 FAQ 或 Issues 来寻找解决方案   , 也是这个错误啊

**Comment by TsriGero** [comment]
coding遇到同样的问题

**Comment by nwuzmedoutlook** [comment]
打开Gridea客户端，左上角“编辑”-->“开发者工具”-->"console"-->“检测结果”-->大多数情况是因为出现这个"message: "connect ETIMEDOUT 140.82.112.4:443"
success: false"
我按照这个博主的方法解决成功：
Gridea 检测远程连接失败_悄悄地努力的博客-CSDN博客_gridea远程连接失败  https://blog.csdn.net/weixin_46034990/article/details/104742147

**Comment by kevinspider** [comment]
一直出现这个问题, 算了 我还是回去用 hexo 吧

**Comment by WertherHu** [comment]
我这边是同步的时候提示：read ECONNRESET

**Comment by BonjourYY** [comment]
> 操作系统：Win 7
> 软件版本：0.9.2
> 主题名称：imhanjie
> 
> 报错信息："Client network socket disconnected before secure TLS connection was established"
> 
> 简述：可以正常预览，但是无法同步到GitHub Pages，第一次点击同步，console控制台提示 无法连接到GitHub。第二次就出现上面的报错信息。点击远程菜单，点击检测远程连接，报错 “远程连接失败，请检查仓库、用户名和令牌设置”，然后我把令牌重新设置过，还是没用。希望作者可以尽快修复。Gridea一直是我最佳的博客写作平台。

**Comment by BonjourYY** [comment]
我的问题已经解决了，大家可以看下方法。

**Comment by Jonathan4s** [comment]
在host里加了 13.229.188.59 github.com 这个就好了谢谢楼主

**Comment by linyuqi9** [comment]
加上host妥了，大概率怀疑是两会墙了gh。

**Comment by Jonathan4s** [comment]
> 加上host妥了，大概率怀疑是两会墙了gh。

同步之后，你的github主页变成gridea那样的界面了吗？我一直没有

**Comment by linyuqi9** [comment]
> > 加上host妥了，大概率怀疑是两会墙了gh。
> 
> 同步之后，你的github主页变成gridea那样的界面了吗？我一直没有

一切正常。

**Comment by WertherHu** [comment]
原来一直是提示：read ECONNRESET，然后检查远程连接错误：远程连接失败,请检查仓库、用户名和 token 设置。
改了host之后，终于出现了跟大家一样的错误：message: "connect ETIMEDOUT ....

然后就重新设置了git的代理：
git config --global http.proxy ....
git config --global https.proxy  ....

暂时解决了同步问题。

希望gridea里直接提供设置代理的功能。

**Comment by mj5219054** [comment]
可以正常预览，但是无法同步到GitHub Pages，第一次点击同步，console控制台提示 无法连接到GitHub。第二次就出现上面的报错信息。点击远程菜单，点击检测远程连接，报错 “远程连接失败，请检查仓库、用户名和令牌设置”，然后我把令牌重新设置过，还是没用。希望作者可以尽快修复。

**Comment by Jonathan4s** [comment]
> 可以正常预览，但是无法同步到GitHub Pages，第一次点击同步，console控制台提示 无法连接到GitHub。第二次就出现上面的报错信息。点击远程菜单，点击检测远程连接，报错 “远程连接失败，请检查仓库、用户名和令牌设置”，然后我把令牌重新设置过，还是没用。希望作者可以尽快修复。

同样的问题 [握手]

**Comment by jonathanqwq** [comment]
其实就是网络问题简单说



jonathan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;网站：https://jonathanqwq.github.io


------------------ 原始邮件 ------------------
From: Jonathan4s ***@***.***&gt;
发送时间: 03/23/2021, 16:08
To: getgridea/gridea ***@***.***&gt;
抄送: Shi Jonathan ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Reply:[getgridea/gridea] Gridea客户端无法同步到GitHub Pages（已解决！！！） (#789)





  
可以正常预览，但是无法同步到GitHub Pages，第一次点击同步，console控制台提示 无法连接到GitHub。第二次就出现上面的报错信息。点击远程菜单，点击检测远程连接，报错 “远程连接失败，请检查仓库、用户名和令牌设置”，然后我把令牌重新设置过，还是没用。希望作者可以尽快修复。
  
同样的问题 [握手]

**Comment by BlueskyClouds** [comment]
确实，单纯的网络问题

**Comment by aaunacn** [comment]
同步是同步了，但图片、主题等都无法正常限时，基本是乱码状态

**Comment by jonathanqwq** [comment]
这也许是你的主题的问题ba




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getgridea/gridea"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月26日(星期五) 凌晨1:10
***@***.***&gt;;
抄送:&nbsp;"Jonathan ***@***.******@***.***&gt;;
主题:&nbsp;Re: [getgridea/gridea] Gridea客户端无法同步到GitHub Pages（已解决！！！） (#789)





 
同步是同步了，但图片、主题等都无法正常限时，基本是乱码状态

**Comment by wearehere8** [comment]
网络问题的参考如下：
前提，有安装git
点击同步，在output文件夹就会生成需要上传的文件了。
output的.git的config里面的remote的url中的"github.com"改成"github.com.cnpmjs.org"，然后手动git push这个想法我提了建议
https://github.com/getgridea/gridea/issues/796
看作者会不会采纳

**Comment by Jonathan4s** [comment]
> 网络问题的参考如下：
> 前提，有安装git
> 点击同步，在output文件夹就会生成需要上传的文件了。
> output的.git的config里面的remote的url中的"github.com"改成"github.com.cnpmjs.org"，然后手动git push这个想法我提了建议
> #796
> 看作者会不会采纳

怎么搭配git使用，本地仓库github文件夹里没有内容，还是说git push gridea的文件夹吗，有步骤教程可以指导一下吗？

**Comment by wearehere8** [comment]
> 
> 
> > 网络问题的参考如下：
> > 前提，有安装git
> > 点击同步，在output文件夹就会生成需要上传的文件了。
> > output的.git的config里面的remote的url中的"github.com"改成"github.com.cnpmjs.org"，然后手动git push这个想法我提了建议
> > #796
> > 看作者会不会采纳
> 
> 怎么搭配git使用，本地仓库github文件夹里没有内容，还是说git push gridea的文件夹吗，有步骤教程可以指导一下吗？

在gridea文档的文件夹里面，默认在“文档-Gridea”里面，你在gridea设置里也能查到路径。点击gridea的同步按钮后，gridea里面的output文件夹里面的就是要发布到github的文件，cd output 后 git push，就能推上去了。

**Comment by Jonathan4s** [comment]
> > > 网络问题的参考如下：
> > > 前提，有安装git
> > > 点击同步，在output文件夹就会生成需要上传的文件了。
> > > output的.git的config里面的remote的url中的"github.com"改成"github.com.cnpmjs.org"，然后手动git push这个想法我提了建议
> > > #796
> > > 看作者会不会采纳
> > 
> > 
> > 怎么搭配git使用，本地仓库github文件夹里没有内容，还是说git push gridea的文件夹吗，有步骤教程可以指导一下吗？
> 
> 在gridea文档的文件夹里面，默认在“文档-Gridea”里面，你在gridea设置里也能查到路径。点击gridea的同步按钮后，gridea里面的output文件夹里面的就是要发布到github的文件，cd output 后 git push，就能推上去了。

git push origin main 报错
“$ git push origin main
fatal: unable to access 'https://github.com/我的库.git/
': Proxy CONNECT aborted”
我哭了

**Comment by wearehere8** [comment]
> 
> 
> > > > 网络问题的参考如下：
> > > > 前提，有安装git
> > > > 点击同步，在output文件夹就会生成需要上传的文件了。
> > > > output的.git的config里面的remote的url中的"github.com"改成"github.com.cnpmjs.org"，然后手动git push这个想法我提了建议
> > > > #796
> > > > 看作者会不会采纳
> > > 
> > > 
> > > 怎么搭配git使用，本地仓库github文件夹里没有内容，还是说git push gridea的文件夹吗，有步骤教程可以指导一下吗？
> > 
> > 
> > 在gridea文档的文件夹里面，默认在“文档-Gridea”里面，你在gridea设置里也能查到路径。点击gridea的同步按钮后，gridea里面的output文件夹里面的就是要发布到github的文件，cd output 后 git push，就能推上去了。
> 
> git push origin main 报错
> “$ git push origin main
> fatal: unable to access '[https://github.com/我的库.git/](https://github.com/%E6%88%91%E7%9A%84%E5%BA%93.git/)
> ': Proxy CONNECT aborted”
> 我哭了

你没改链接啊，github不稳，gridea会同步失败就是因为默认的github.com连接不稳定，所以才自己改链接手动git push，在.git的config把"github.com"改成"github.com.cnpmjs.org"，这是阿里云新加坡节点。

**Comment by Jonathan4s** [comment]
> > > > > 网络问题的参考如下：
> > > > > 前提，有安装git
> > > > > 点击同步，在output文件夹就会生成需要上传的文件了。
> > > > > output的.git的config里面的remote的url中的"github.com"改成"github.com.cnpmjs.org"，然后手动git push这个想法我提了建议
> > > > > #796
> > > > > 看作者会不会采纳
> > > > 
> > > > 
> > > > 怎么搭配git使用，本地仓库github文件夹里没有内容，还是说git push gridea的文件夹吗，有步骤教程可以指导一下吗？
> > > 
> > > 
> > > 在gridea文档的文件夹里面，默认在“文档-Gridea”里面，你在gridea设置里也能查到路径。点击gridea的同步按钮后，gridea里面的output文件夹里面的就是要发布到github的文件，cd output 后 git push，就能推上去了。
> > 
> > 
> > git push origin main 报错
> > “$ git push origin main
> > fatal: unable to access '[https://github.com/我的库.git/](https://github.com/%E6%88%91%E7%9A%84%E5%BA%93.git/)
> > ': Proxy CONNECT aborted”
> > 我哭了
> 
> 你没改链接啊，github不稳，gridea会同步失败就是因为默认的github.com连接不稳定，所以才自己改链接手动git push，在.git的config把"github.com"改成"github.com.cnpmjs.org"，这是阿里云新加坡节点。

.git文件里的config中 "github.com"改成了“github.com.cnpmjs.org"，但是之后又自动变成github.com了，而且git push 一直有问题……

**Comment by wearehere8** [comment]
> 
> 
> > > > > > 网络问题的参考如下：
> > > > > > 前提，有安装git
> > > > > > 点击同步，在output文件夹就会生成需要上传的文件了。
> > > > > > output的.git的config里面的remote的url中的"github.com"改成"github.com.cnpmjs.org"，然后手动git push这个想法我提了建议
> > > > > > #796
> > > > > > 看作者会不会采纳
> > > > > 
> > > > > 
> > > > > 怎么搭配git使用，本地仓库github文件夹里没有内容，还是说git push gridea的文件夹吗，有步骤教程可以指导一下吗？
> > > > 
> > > > 
> > > > 在gridea文档的文件夹里面，默认在“文档-Gridea”里面，你在gridea设置里也能查到路径。点击gridea的同步按钮后，gridea里面的output文件夹里面的就是要发布到github的文件，cd output 后 git push，就能推上去了。
> > > 
> > > 
> > > git push origin main 报错
> > > “$ git push origin main
> > > fatal: unable to access '[https://github.com/我的库.git/](https://github.com/%E6%88%91%E7%9A%84%E5%BA%93.git/)
> > > ': Proxy CONNECT aborted”
> > > 我哭了
> > 
> > 
> > 你没改链接啊，github不稳，gridea会同步失败就是因为默认的github.com连接不稳定，所以才自己改链接手动git push，在.git的config把"github.com"改成"github.com.cnpmjs.org"，这是阿里云新加坡节点。
> 
> .git文件里的config中 "github.com"改成了“github.com.cnpmjs.org"，但是之后又自动变成github.com了，而且git push 一直有问题……

看这个https://github.com/getgridea/gridea/issues/796， 还不会算了：-（

**Comment by Jonathan4s** [comment]
> > > > > > > 网络问题的参考如下：
> > > > > > > 前提，有安装git
> > > > > > > 点击同步，在output文件夹就会生成需要上传的文件了。
> > > > > > > output的.git的config里面的remote的url中的"github.com"改成"github.com.cnpmjs.org"，然后手动git push这个想法我提了建议
> > > > > > > #796
> > > > > > > 看作者会不会采纳
> > > > > > 
> > > > > > 
> > > > > > 怎么搭配git使用，本地仓库github文件夹里没有内容，还是说git push gridea的文件夹吗，有步骤教程可以指导一下吗？
> > > > > 
> > > > > 
> > > > > 在gridea文档的文件夹里面，默认在“文档-Gridea”里面，你在gridea设置里也能查到路径。点击gridea的同步按钮后，gridea里面的output文件夹里面的就是要发布到github的文件，cd output 后 git push，就能推上去了。
> > > > 
> > > > 
> > > > git push origin main 报错
> > > > “$ git push origin main
> > > > fatal: unable to access '[https://github.com/我的库.git/](https://github.com/%E6%88%91%E7%9A%84%E5%BA%93.git/)
> > > > ': Proxy CONNECT aborted”
> > > > 我哭了
> > > 
> > > 
> > > 你没改链接啊，github不稳，gridea会同步失败就是因为默认的github.com连接不稳定，所以才自己改链接手动git push，在.git的config把"github.com"改成"github.com.cnpmjs.org"，这是阿里云新加坡节点。
> > 
> > 
> > .git文件里的config中 "github.com"改成了“github.com.cnpmjs.org"，但是之后又自动变成github.com了，而且git push 一直有问题……
> 
> 看这个[https://github.com/getgridea/gridea/issues/796#issue-842307398，](https://github.com/getgridea/gridea/issues/796#issue-842307398%EF%BC%8C) 还不会算了：-（

我不用同步的功能了，写完文章保存之后，我手工从git init开始，到git push来一遍就好了

**Comment by TYtangyi** [comment]
真的可以，感谢

**Comment by chalezhang** [comment]
> 我这边是同步的时候提示：read ECONNRESET

我的也是提示这个错误，你的解决了吗？解决了告诉我一下方法。

**Comment by Eason-zz** [comment]
我想请问一下无法同步，异常是这样子的该怎么解决呢 message: "Author name and email must be specified as an argument or in the .git/config file.", success: false}

**Comment by romancekami** [comment]
> 我这边是同步的时候提示：read ECONNRESET

我也是，问下有解决方法吗？

**Comment by HugoHann** [comment]
> 我想请问一下无法同步，异常是这样子的该怎么解决呢 message: "Author name and email must be specified as an argument or in the .git/config file.", success: false}

我也是这个问题，请问解决了么

**Comment by CALOS985** [comment]
> 在host里加了 13.229.188.59 github.com 这个就好了谢谢楼主

host在哪？

**Comment by nileblack** [comment]
> 我想请问一下无法同步，异常是这样子的该怎么解决呢 message: "Author name and email must be specified as an argument or in the .git/config file.", success: false}

临时的一个解决办法是，直接进入output目录，
```
git config user.name xxxx
git config user.email xxxx@xxxx
```

**Comment by Waterkin** [comment]
chunk-vendors.c212ddc4.js:302 TypeError: Cannot read property 'format' of null
    at r.ot (app.36afefc7.js:1)
    at r.e._render (chunk-vendors.c212ddc4.js:39)
    at r.n (chunk-vendors.c212ddc4.js:39)
    at nn.get (chunk-vendors.c212ddc4.js:39)
    at nn.run (chunk-vendors.c212ddc4.js:39)
    at Zi (chunk-vendors.c212ddc4.js:39)
    at Array.<anonymous> (chunk-vendors.c212ddc4.js:39)
    at ut (chunk-vendors.c212ddc4.js:39)

**Comment by 15512818226** [comment]
哥们儿们
netlify也是可以的
不要盯着Github Pages不放
看我的https://blog.huizenx.top/
