### ISSUE TITLE
主题“Simple”在移动端访问时崩坏

### ISSUE THREAD

**Issue by SteamFinderMini** [getgridea/gridea#80]
同

**Comment by EryouHao** [comment]
能提供一下截图看下吗？

**Comment by SteamFinderMini** [comment]
![ios](https://user-images.githubusercontent.com/50077666/56894729-4aec3980-6ab9-11e9-8f53-0cbfa90f31f6.jpg)
![ipad](https://user-images.githubusercontent.com/50077666/56894730-4b84d000-6ab9-11e9-80e7-1d24ebc021b2.jpg)

**Comment by afderlqs** [comment]
我也遇到了，手机端的simple问题有点严重，格式出错比较大

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1), 需要更新下 simple 主题
