### ISSUE TITLE
安装失败，不确定是不是bug。

### ISSUE THREAD

**Issue by SpongeBab** [getgridea/gridea#807]
用命令行安装的最新版
`sudo dpkg -i gridea_0.9.2_amd64.deb `
![2021-04-23 15-34-51 的屏幕截图](https://user-images.githubusercontent.com/65898238/115835961-7f492500-a449-11eb-9f75-447c157e7e10.png)

**Comment by SpongeBab** [comment]
![2021-04-23 15-38-33 的屏幕截图](https://user-images.githubusercontent.com/65898238/115836396-039ba800-a44a-11eb-88a8-efcfe0fb10db.png)
感觉是加载太慢了。现在好了，顺便官网是否考虑出一个使用教程，如何和github page配合使用？

**Comment by china-haoxuan** [comment]
百度

**Comment by china-haoxuan** [comment]
官网上都有的

**Comment by SpongeBab** [comment]
OK，thank u。
