### ISSUE TITLE
新建主题格式是基于什么原因考虑的呢? 为什么不直接基于 hexo

### ISSUE THREAD

**Issue by uu0** [getgridea/gridea#82]
如果直接能整合 hexo ,那么能省下来很多移植主题的功夫.

**Comment by afderlqs** [comment]
可想而知这是一个巨大的工程，hexo上好多漂亮的主题，尤其是背景渲染值得去看呢。

**Comment by EryouHao** [comment]
我们未来会对主题系统做更多的事情，敬请期待。做 Hexo 兼容会消耗一部分精力，可等待社区出移植版
