### ISSUE TITLE
readd ECONNRESET

### ISSUE THREAD

**Issue by pilgrimlyieu** [getgridea/gridea#822]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   Windows10   |
| 软件版本 |  Gridea    |
| 主题名称 |      |

---

## 当前行为
远程连接有时行有时不行
同步一次都不行
远程连接和同步不行时message都是"read ECONNRESET"

**Comment by H1224282162** [comment]
![微信截图_20210519105528](https://user-images.githubusercontent.com/68718191/118749824-d992a580-b890-11eb-9348-d9b9be49d0eb.png)
我也遇到了同样的问题，也是win10系统，远程连接成功，同步失败

**Comment by doubleLLL3** [comment]
我也是一样的问题。现在每次都是渲染后，去output目录下手动git push。

**Comment by gd1214b** [comment]
可以参考一下：
<https://blog.gd1214b.icu/post/F2_C5EVQh/>

**Comment by Zillion-X** [comment]
> 我也是一样的问题。现在每次都是渲染后，去output目录下手动git push。

你好，请问怎样手动 git push？我也是遇到同样的问题，现在想要通过手动解决问题。（因为是小白所以不懂很多东西，希望可以将步骤写清楚一点）

**Comment by pilgrimlyieu** [comment]
没有维护的迹象，关闭了。
