### ISSUE TITLE
feat: Gridea老同步失败，也许可以增加一个设置代理的功能

### ISSUE THREAD

**Issue by YerayL** [getgridea/gridea#823]
## 概述

增加一个设置代理（proxy）的功能

## 动机

使用Gridea时，经常同步失败，偶尔才能成功一次。
于是我手动使用git push发现也失败了，发现时git bash没有设置代理造成的：
git config --global http.proxy 'socks5://127.0.0.1:4781'
设置完后就可以手动git push了。
所以我想issues里面有这么多人同步失败，也许可以增加一个设置代理的功能？

**Comment by lanyinyu** [comment]
我发现git bash设置代理以后，Grideag好像也能同步成功了......

**Comment by 2489344858** [comment]
纯小白，请问怎么设置代理

**Comment by EryouHao** [comment]
v0.9.3 支持设置代理了，可以试试。
