### ISSUE TITLE
同步失败，求助

### ISSUE THREAD

**Issue by pth2000** [getgridea/gridea#825]
同步失败，还没找到解决办法，求助。

![image](https://user-images.githubusercontent.com/36351616/118087211-cba7d500-b3f7-11eb-8e90-0b2f74657518.png)

**Comment by afret0** [comment]
在尝试使用代理同步....
我国外网络没问题

**Comment by gd1214b** [comment]
可以参考一下：
<https://blog.gd1214b.icu/post/F2_C5EVQh/>
