### ISSUE TITLE
Q : 远程连接成功，但同步时显示 404: NOT_FOUND

### ISSUE THREAD

**Issue by milkycoffee527** [getgridea/gridea#826]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  macOS 10.12.6    |
| 软件版本 |   0.8.2   |
| 主题名称 |  Notes    |

---

**Comment by apocalypsestudent** [comment]
我的是403

**Comment by AllGetHub** [comment]
GitHub在国内联通性不佳，建议梯字或者添加GitHub的IP到hosts

**Comment by like-code-ljh** [comment]
应该不是连接问题，我用coding也是这个问题  两个平台都同步不了
Duplicate of #

**Comment by EryouHao** [comment]
v0.9.3 支持设置代理了，同时更改了同步机制，可以试试。
