### ISSUE TITLE
Q ： 同步错误

### ISSUE THREAD

**Issue by milkycoffee527** [getgridea/gridea#827]
连接可以，但是现在基于一个仓库创建一个 github pages 需要仓库非空，那么应该在仓库中添加什么文件呢？

**Comment by apocalypsestudent** [comment]
对的，我也遇到了这个问题。（主要是对于这方面还是萌新……）

**Comment by apocalypsestudent** [comment]
应该是往里面放入你的output文件夹里的所有东西
