### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by LiarrDev** [getgridea/gridea#829]
我同步完成后，GitHub 给我发了一封 Emali：

> The page build failed for the `master` branch with the following error:
>
> Unable to build page. Please try again later.
>
> For information on troubleshooting Jekyll see:
>
>  https://docs.github.com/articles/troubleshooting-jekyll-builds
>
> If you have any questions you can submit a request at https://support.github.com/contact?repo_id=173916947&page_build_id=253588918

博客对应的 Repo 是有更新的，但是博客却没有 Deploy 成功，有没有解决方法？

**Comment by myx1002** [comment]
请问解决了吗

**Comment by LiarrDev** [comment]
> Unable to build page. Please try again later.

所以我隔了两天再试，它又成功了。

**Comment by LiarrDev** [comment]
> 请问解决了吗

Email 中提到：
> Unable to build page. Please try again later.

所以我隔了两天再试，它又成功了。

**Comment by myx1002** [comment]
谢谢老哥呀，我也找到问题了，已经联系了客服帮我处理了。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getgridea/gridea"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [getgridea/gridea] Page build failure (#829)





  
请问解决了吗
  
Email 中提到：
  
Unable to build page. Please try again later.
  
所以我隔了两天再试，它又成功了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
