### ISSUE TITLE
gitalk Error: Validation Failed

### ISSUE THREAD

**Issue by initsysctrl** [getgridea/gridea#84]
![](https://ws4.sinaimg.cn/large/006tNc79ly1g2msv2ygo2j312e0a8aa5.jpg)
请问如何在gridea引入md5,对url进行加密？

**Comment by EryouHao** [comment]
目前几个内置主题在使用 gitalk 的时候是采用截取的策略（主要考虑之前用户已经有文章评论的原因），可自行修改改为 url md5的

**Comment by wmltyq** [comment]
我还是没搞懂怎么解决……

**Comment by rubyyc** [comment]
@EryouHao 对啊，目前还是报错。请问如何解决？

**Comment by rubyyc** [comment]
@EryouHao 
`var gitalk = new Gitalk({
    clientID: '<%= commentSetting.gitalkSetting.clientId %>',
    clientSecret: '<%= commentSetting.gitalkSetting.clientSecret %>',
    repo: '<%= commentSetting.gitalkSetting.repository %>',
    owner: '<%= commentSetting.gitalkSetting.owner %>',
    admin: ['<%= commentSetting.gitalkSetting.owner %>'],
    id: (location.pathname).substring(0, 49),      // Ensure uniqueness and length less than 50
    distractionFreeMode: false  // Facebook-like distraction free mode
  }) 
`
看到您的源码是截取,但还是报错啊

**Comment by rubyyc** [comment]
``

> @EryouHao
> `var gitalk = new Gitalk({ clientID: '<%= commentSetting.gitalkSetting.clientId %>', clientSecret: '<%= commentSetting.gitalkSetting.clientSecret %>', repo: '<%= commentSetting.gitalkSetting.repository %>', owner: '<%= commentSetting.gitalkSetting.owner %>', admin: ['<%= commentSetting.gitalkSetting.owner %>'], id: (location.pathname).substring(0, 49), // Ensure uniqueness and length less than 50 distractionFreeMode: false // Facebook-like distraction free mode }) `
> 看到您的源码是截取,但还是报错啊

gitalk Error: Validation Failed依然报错
