### ISSUE TITLE
希望可以在服务器部署客户端

### ISSUE THREAD

**Issue by qianmianyao** [getgridea/gridea#840]
## 概述

希望可以在服务器部署客户端，直接在网页编辑文章

## 动机

由于不是时时刻刻有电脑，希望可以在ipad或者手机编辑文章，而且更换电脑备份比较麻烦

## 详细解释

类似hexo一样活着hugo那种，可以在服务器部署客户端，然后推送到github

**Comment by EryouHao** [comment]
可以试试 web 版 Gridea。客户端本身没办法部署，例如服务器是一个无图形化的 linux，如何用手机或 iPad 等设备来操作一个 UI 的客户端呢？目前 web 版是支持的。

**Comment by qianmianyao** [comment]
目前web版本不支持主题呀
