### ISSUE TITLE
feat: 增加Android版本

### ISSUE THREAD

**Issue by cloudw233** [getgridea/gridea#848]
## 概述

让gridea运行在Android上

## 动机

电脑太重，不方便随时写博客

## 详细解释

Android版gridea客户端

**Comment by efu00** [comment]
不是有gridea web

**Comment by cloudw233** [comment]
但我没电脑啊

**Comment by JOJOforshaun** [comment]
gridea web 每个月6块钱，就能用几乎任何能使用浏览器的设备写文章了啊。也不需要操心网站部署的问题，直接代托管了
https://web.gridea.dev/

**Comment by Can1425** [comment]
能给我用用吗，求

**Comment by cloudw233** [comment]
已转用hexo+gh-action
