### ISSUE TITLE
博客内容全消失，设置里站点源文件项变空

### ISSUE THREAD

**Issue by Blackmesa-Canteen** [getgridea/gridea#859]
保存了一个新博客后，发现原来的博客内容全消失（文章，菜单，标签全变0），设置里站点源文件项变空，配置信息全丢失。

**Comment by Blackmesa-Canteen** [comment]
我的心血也全没了。同步到github会把我原来写的全部覆盖掉。

**Comment by Blackmesa-Canteen** [comment]
原来的Gridea目录里的东西打不开，设置站点源文件路径后保存，内容还是空的，空的，空的。

**Comment by Blackmesa-Canteen** [comment]
同步后，又覆盖了我线上的repository，历史commit也全空了

**Comment by Blackmesa-Canteen** [comment]
我不知道这个bug是谁写出来的，我操你大爷。

**Comment by Blackmesa-Canteen** [comment]
明白Bug原因了：博文标题里出现了特殊字符。

**Comment by iskylite** [comment]
那么如何恢复博客呢，所有的commit都没了

**Comment by Blackmesa-Canteen** [comment]
那就确实没了, 索性我在使用此应用前备份了博文,没有完全丢. 目前已经弃用Gridea,转为使用其他万星开源博客项目.

**Comment by iskylite** [comment]
其他大佬的开源博客项目?能不能给个链接，谢谢

**Comment by zhangyiming748** [comment]
遇到了和你同样的问题，不过幸好我把它本地的文档库保存到了另一个github仓库，每次同步后我都手动再同步一下
