### ISSUE TITLE
付费版出来后，该版本一年半未进行任何更新了，这个项目还继续吗？

### ISSUE THREAD

**Issue by azgh** [getgridea/gridea#865]
从wordpress转到gridea，觉得这个项目很有潜力，虽然功能不完善，但不断修bug增加feature，未来肯定是个不错的开源项目，而且这个gui版本的git我觉得是个```great idea```，对于只想写东西，不想琢磨太多技术的人来说，很好。
一直关注这个项目，直到发现还有个付费版，是不是意味着这个版本停止开发，只专注于付费版了？

**Comment by dst111dst** [comment]
a ???? 我都没发现。。。。呜呜不是吧...

**Comment by PyMakerMike** [comment]
付费版在哪

**Comment by NoctuG** [comment]
> 付费版在哪

应该是这个
https://web.gridea.dev/

**Comment by Error063** [comment]
这个好像是开发者给你一个博客空间，独立于GitHub的东西，速度相对于GitHub稍微快一点

**Comment by GlodenBoy** [comment]
线上版 相对省事一点，但是也希望作者 能同时兼顾到开源版

**Comment by EryouHao** [comment]
更新了 v0.9.3 版本，支持了部署 Netlify、解决了同步问题和支持设置代理。

正常使用是没问题的哈，只不过更新可能不会太频繁了。
