### ISSUE TITLE
Gridea客户端无法同步到GitHub Pages（已解决！！！）

### ISSUE THREAD

**Issue by uslook** [getgridea/gridea#866]
打开c:/windows/system32/drivers/etc/hosts，
增加
#13.229.188.5 github.com
#52.74.223.119 github.com

Ctrl+R 输入 cmd

弹出命令框
输入
ipconfig /displaydns

显示所有 dns内容

ipconfig /flushdns

刷新所有 dns内容
然后同步即可

**Comment by aianita** [comment]
MAC版本的解决方案有吗

**Comment by romancekami** [comment]
> 打开c:/windows/system32/drivers/etc/hosts，
> 增加
> #13 .229.188.5 github.com
> #52 .74.223.119 github.com
> 
> Ctrl+R 输入 cmd
> 
> 弹出命令框
> 输入
> ipconfig /displaydns
> 
> 显示所有dns内容
> 
> ipconfig /flushdns
> 
> 刷新所有dns内容
> 更新同步

老哥您好，我第一次在issue评论，多多见谅，请问下：
老哥在网站ip前面添加的#在host中应该是表示注释的意思吧？如果是注释那么应该就不会生效，那老哥增加这个有啥用呢？

**Comment by uslook** [comment]
> > ・#13.22918.5 github.com #52.74223.119 github.com 
> > 克特勒勒克勒克特克
> > 电子信息/显示器
> > 电子
> > 伊普自信/冲洗
> > 新人更新
> 
> ・周特约记者 周美红）《第三十一次大夫》一言不发，《多吉特》一言不发：《
> 无国大夫》《无名小子》《无名小精昆》《无名小精昆》？《无国大法》《无名小子》？《无国大法》《乔夫·乔夫·乔夫？》《乔夫·乔夫？》《乔夫·



> > 打开c:/windows/system32/drivers/etc/hosts，
> > 增加
> > #13 .229.188.5 github.com
> > #52 .74.223.119 github.com
> > Ctrl+R 输入 cmd
> > 弹出命令框
> > 输入
> > ipconfig /displaydns
> > 显示所有dns内容
> > ipconfig /flushdns
> > 刷新所有dns内容
> > 更新同步
> 
> 老哥您好，我第一次在issue评论，多多见谅，请问下：
> 老哥在网站ip前面添加的#在host中应该是表示注释的意思吧？如果是注释那么应该就不会生效，那老哥增加这个有啥用呢？

不好意思，我搞错了，我发现一个方法可以成功同步，连接自己手机的流量热点可以同步成功，我的是移动

**Comment by uslook** [comment]
> MAC版本的解决方案有吗

我发现一个方法可以成功同步，连接自己手机的流量热点可以同步成功

**Comment by gd1214b** [comment]
可以参考一下：
<https://blog.gd1214b.icu/post/F2_C5EVQh/>

**Comment by EryouHao** [comment]
v0.9.3 支持设置代理了，可以试试。
