### ISSUE TITLE
HTTP Error: 403 Forbidden

### ISSUE THREAD

**Issue by djwccc** [getgridea/gridea#868]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   windows10   |
| 软件版本 |   0.9.2   |
| 主题名称 |   NexT   |

---

## 期望行为
同步Gridea

## 当前行为
同步失败，控制台报错HTTP Error: 403 Forbidden

**Comment by 839284824** [comment]
遇到了同样的问题，求解
