### ISSUE TITLE
同步失败，错误信息为read etimedout，各种方法都试过了

### ISSUE THREAD

**Issue by dst111dst** [getgridea/gridea#871]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   mac os   |
| 软件版本 |   0.9.2..? 最新版本  |
| 主题名称 |   next   |

---

## 期望行为
同步成功

## 当前行为
报错，显示read etimedout

如题，我ping github.com是可行的，但是仍然显示read etimedout... 所以我去修改了mac下的hosts文件，但是改了代理之后还是报这个错误。。。
一切方法我都尝试过了，包括直接删除output文档，查改并修改output下.git文件夹中的config，所有网络上现成的方式我都尝试过了，没有一种能帮我成功同步。。。

**Comment by dst111dst** [comment]
我的仓库显示的样子还是等待被写入的样子，说明gridea在这个过程中没有修改过一点点仓库中的内容。。。

**Comment by dst111dst** [comment]
对了，有几次显示同步成功，但是并没有变化....

**Comment by Ender32k** [comment]
我有时也是这样...

**Comment by WilliamColton** [comment]
https://blog.gd1214b.icu/post/F2_C5EVQh/

**Comment by WilliamColton** [comment]
可以看一下这篇教程

**Comment by hxhc** [comment]
gridea不走系统代理，用proxifier/proxychains强制gridea走代理
