### ISSUE TITLE
自定义域名后再次同步会将原域名文件CNAME覆盖造成自定义域名失效问题

### ISSUE THREAD

**Issue by nmydt** [getgridea/gridea#879]
自定义域名后再次同步会将原域名文件CNAME覆盖造成自定义域名失效，我们无法多次进行默认分支的重复提交CNAME或再次进行自定义域名工作，这将造成很大的不方便性。

建议：可以增加一个选项使得个人可以自定义增加额外的文件到output静态文件目录中使得最后生成的静态文件不因覆盖问题造成麻烦。

**Comment by Gabriel-1023** [comment]
同样问题，为什么CNAME文件放到static文件夹里边死活同步不到仓库里边。。。

**Comment by nmydt** [comment]
gridea客户端配置github页面里面可以填域名

**Comment by nmydt** [comment]
> 同样问题，为什么CNAME文件放到static文件夹里边死活同步不到仓库里边。。。

gridea客户端配置github页面里面可以填域名

**Comment by Gabriel-1023** [comment]
> > 同样问题，为什么CNAME文件放到static文件夹里边死活同步不到仓库里边。。。
> 
> gridea客户端配置github页面里面可以填域名

刚评论完就发现了，谢谢哈哈哈，不知道为啥看了好多遍都没发现还有个CNAME配置
