### ISSUE TITLE
使用日期作为标题的时候会出现问题

### ISSUE THREAD

**Issue by halftrue** [getgridea/gridea#88]
例：我使用2019-05-04作为标题的时候，会把标题自动变为2019-05-04T00:00:00.000Z
而只要加上一些多余的汉字的时候，就不会发生这个情况

**Comment by EryouHao** [comment]
已经修复，下个版本更新

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
