### ISSUE TITLE
WiFi环境下同步失败

### ISSUE THREAD

**Issue by coolf233** [getgridea/gridea#880]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  win10    |
| 软件版本 | 0.9.2     |
| 主题名称 |    papaper  |

---

## 期望行为
WiFi环境下远程同步正常！

## 当前行为
WiFi环境下同步失败连接移动数据就可以同步

![image](https://user-images.githubusercontent.com/70014225/129324845-92fcb45c-19c4-4c5d-852b-8c33a741756b.png)

**Comment by coolf233** [comment]
解决办法有两种，用手机开数据热点，电脑连接后会直接同步成功，第二种是强制使用使用代理
There are two solutions, open data hotspot with mobile phone, computer connection will be directly successful synchronization, the second is forced to use proxy

**Comment by EryouHao** [comment]
可以试试 v0.9.3 版本哈，解决了同步问题，和支持了设置代理。
