### ISSUE TITLE
同步错误，寻求帮助！

### ISSUE THREAD

**Issue by xxedu** [getgridea/gridea#883]
用gridea+github，远程连接可以，同步失败，提示："An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: SHA check failed! Expected 65210402ffaa66bf324a6134481f03fd6d0fffd6, computed da39a3ee5e6b4b0d3255bfef95601890afd80709"
请问大神需要怎么处理？

**Comment by zjp693** [comment]
> 另一种解决办法：不需要走全局代理，只是DNS被污染，用Github上 FastGithub或者devsidecar这种工具也可以轻松解决。

有具体操作的教程吗

**Comment by EryouHao** [comment]
可以试试 v0.9.3 版本哈，解决了同步问题，和支持了设置代理。
