### ISSUE TITLE
Github 同步失败的解决办法

### ISSUE THREAD

**Issue by dyxang** [getgridea/gridea#886]
基于原开发者一直没有更新解决办法。Github 同步失败又多半是国内网络情况原因，所以我只好自己动手丰衣足食找到**其中一个适合我的解决办法**了，也希望对某些特殊情况的有所帮助。
由于 Gridea 0.9.2 使用的是新的内置 git，使用开发者边车工具没法代理它。所以我们得改一下

> 注意：需自己已单独安装了 Git ，并且去 [Gitee](https://gitee.com/docmirror/dev-sidecar) 或 [Github](https://github.com/docmirror/dev-sidecar) 安装**开发者边车辅助工具**，为什么非要安装这个工具你去它主页看就知道了，对这软件对以后也有帮助。

# 懒人/小白
安装我已做好修改的版本 [网盘地址](https://www.aliyundrive.com/s/RKWR1y8eMng)，卸载原先的再安装这个。不放心的继续看下面

# 自己动手编译
```bs 
Node.js 版本需大于 v10.0.
git clone https://github.com/getgridea/gridea.git
cd gridea
```
此时把文件`packege.json`里的`"isomorphic-git": "^0.78.3",`替换为`"simple-git": "^1.107.0",`。
未安装 yarn 先 `npm install -g yarn`安装，然后到 Github 切换 Tags 把 0.9.1 版本的 `gridea\src\server\deploy.ts` 复制到新版本里覆盖。
```
yarn
yarn electron:serve
yarn electron:build
```
命令行跑完后在`\gridea\dist_electron`找到安装包

**Comment by Lorde627** [comment]
能有macOS版的吗😭

**Comment by dyxang** [comment]
> 能有macOS版的吗😭

阿哲，你可以自己尝试build啊

**Comment by philixz** [comment]
我下载了你的这个新版本，远程连接都通过了，但是就同步遇到错误。你还在用吗，有没有空帮我debug

**Comment by dyxang** [comment]
> 我下载了你的这个新版本，远程连接都通过了，但是就同步遇到错误。你还在用吗，有没有空帮我debug

自己带详细描述我才能帮你

**Comment by philixz** [comment]
fatal: A branch named 'master' already exists.         报错信息是这样的

**Comment by philixz** [comment]
> > 我下载了你的这个新版本，远程连接都通过了，但是就同步遇到了错误。你还在用吗，有没有空帮我调试
> 
> 自己带详细描述我不会帮忙

以前的文件夹直接备份过来的不行（备份的方式不对吗），暂时建了个新库就好了

**Comment by dyxang** [comment]
> > > 我下载了你的这个新版本，远程连接都通过了，但是就同步遇到了错误。你还在用吗，有没有空帮我调试
> > 
> > 
> > 自己带详细描述我不会帮忙
> 
> 以前的文件夹直接备份过来的不行（备份的方式不对吗），暂时建了个新库就好了

这报错你百度一下都知道了

**Comment by luoyelusheng** [comment]
最新解决方案，走全局代理，具体过程可参看[这里](https://www.luoyelusheng.com/post/Gridea%E5%90%8C%E6%AD%A5github%E5%A4%B1%E8%B4%A5%E6%9C%80%E7%BB%88%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88/)

**Comment by dyxang** [comment]
> 最新解决方案，走全局代理，具体过程可参看[这里](https://www.luoyelusheng.com/post/Gridea%E5%90%8C%E6%AD%A5github%E5%A4%B1%E8%B4%A5%E6%9C%80%E7%BB%88%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88/)

另一种解决办法：不需要走全局代理，只是DNS被污染，用Github上 FastGithub或者devsidecar这种工具也可以轻松解决。
