### ISSUE TITLE
📢 [2021.10.23 更新] 关于检测远程链接成功，但同步错误的案例收集与修复测试包

### ISSUE THREAD

**Issue by EryouHao** [getgridea/gridea#890]
久等了，所有人。

如果你遇到了检测远程链接成功，但是却同步失败，大概率是遇到了网络问题，导致没有同步成功。

现在，我修复了这一问题，发布了 Mac 和 Windows 的测试包，但是我并不能保证其肯定能正常工作，所以需要你来进行安装测试。

测试后，无论成功与否，都欢迎在此 issue 下进行回复，告知我，以便我进行后续的正式发布。

感谢。

测试包下载：

[Gridea 0.9.支持 Netlify 部署与支持自动使用系统代理的安装包](https://github.com/EryouHao/gridea-test-install/releases/tag/2.0)

于 2021.10.23 更新

**Comment by voidint** [comment]
macOS Big Sur 11.5.2 无法同步（检测远程连接成功，同步操作长时间未响应）

**Comment by EryouHao** [comment]
@voidint 你的报错是什么，可以提供一下截图吗？

**Comment by fengguowudi** [comment]
增加个导出zip呗，或者支持下gitee

**Comment by voidint** [comment]
> @voidint 你的报错是什么，可以提供一下截图吗？

怎么看报错信息？有日志吗？点击`同步`按钮后就开始loading，没任何响应，看不到任何错误信息。

**Comment by EryouHao** [comment]
> > @voidint 你的报错是什么，可以提供一下截图吗？
> 
> 怎么看报错信息？有日志吗？点击`同步`按钮后就开始loading，没任何响应，看不到任何错误信息。

@voidint 等久一会儿，会有报错弹窗吗？这次加了同步失败的报错弹窗。

**Comment by chllivein** [comment]
实测修复后每次都能成功同步，美滋滋。还是请求作者增加一个显式的按钮来开启/关闭使用系统代理，可以的话就更方便了。

**Comment by muziling** [comment]
挂代理还是失败
[Server] 同步失败： request to https://api.github.com/repos/muziling/muziling.github.io/git/blobs failed, reason: socket hang up

**Comment by EryouHao** [comment]
> 这个同步搞得我血压狂飙，太差劲了

@lrxtzm 是还没同步成功吗还是什么原因？

**Comment by EryouHao** [comment]
> 挂代理还是失败
> [Server] 同步失败： request to https://api.github.com/repos/muziling/muziling.github.io/git/blobs failed, reason: socket hang up

@muziling 我看你的仓库已经同步成功了？

**Comment by muziling** [comment]
> > 挂代理还是失败
> > [Server] 同步失败： request to https://api.github.com/repos/muziling/muziling.github.io/git/blobs failed, reason: socket hang up
> 
> @muziling 我看你的仓库已经同步成功了？

反复试，只有一次成功

**Comment by Yan-Tianyi** [comment]
次次成功

**Comment by voidint** [comment]
更新Gridea-0.9.2.dmg，点击`同步`后很长时间都没有响应，很长时间指的是超过一个小时的等待。我也没有看到任何提示窗口，任何提示性的文字之类。

**Comment by liwangping** [comment]
我这边也是出现了远程测试成功了，但是同步了几次，失败的情况。始终没有成功。不过我用于保存blog静态资源的[githubname].io这个仓库在9个月前就是存在的。所以我试了下把这个仓库删除掉了。然后重新建了一个。再进行远程连接测试与同步，发现是可以很快进行同步成功的。

**Comment by missmeee** [comment]
同步成功

**Comment by djzrs** [comment]
无法输入，英文状态下按下键盘，输入界面无反应，光标不跳动。中文模式下按下空格键选中打出的文字编辑界面无反应。同步到GitHub正常。

**Comment by lonelyuan** [comment]
成功，就是速度太慢了，，，强烈建议出一个代理模式

**Comment by Ap01lo** [comment]
win10，就第一次成功了，后面要等很长很长时间还没有结果

**Comment by aqrx-cs** [comment]
需要等待候很长时间，还是没有成功/失败的提示 还是不行

**Comment by EryouHao** [comment]
> 成功，就是速度太慢了，，，强烈建议出一个代理模式

@lonelyuan 如果电脑上有配置代理的话，这个新的包应该会走代理的。

**Comment by mj5219054** [comment]
写的东西都丢失了啊无语了啊啊啊啊

**Comment by lonelyuan** [comment]
> > 成功，就是速度太慢了，，，强烈建议出一个代理模式
> 
> @lonelyuan 如果电脑上有配置代理的话，这个新的包应该会走代理的。

emm我用的v2ray，并没有抓到包

**Comment by MoSpade** [comment]
我的远程连接成功,但是同步不了,

🙁 同步遇到了错误，请查阅 FAQ 或 Issues 来寻找解决方案

**Comment by MoSpade** [comment]
怎么解决

**Comment by wsbb741** [comment]
作者您好啊，我也是连接成功，同步失败，然后我就顺着提示找到这里来了 哈哈，
昨晚试着下载了您的这个安装包，重新安装了一下，但是还是没有同步成功哎，
请问如果我开了代理的网络，具体怎样操作才能成功呢？
或者之前的老版本有没有推荐的，可以解决这个同步问题，谢谢！

**Comment by EryouHao** [comment]
@MoSpade 久等了。请问你有显示具体的报错信息吗？如果是显示 ETIMEDOUT，说明你的网络连接 `api.github.com` 这个的使用不通。这个目前没有太好的办法。

如果想省心一点，可以看看我开发的的 Web 版本

**Comment by likong** [comment]
Failed to load resource: net::ERR_TIMED_OUT

connect ETIMEDOUT 13.250.177.223:443"

报错。。。。咋办

**Comment by luoyelusheng** [comment]
默认走http的，换成ssh，貌似就好了

> cd output
> git remote remove origin
> git remote add origin git@github.com:user/user.github.io.git

**Comment by FJAkeys** [comment]
检测链接成功但是同步失败，这里是console log：
chunk-vendors.785f1d04.js:313 {data: {…}, localBranchs: {…}, message: "Unparsable response from server! Expected "unpack ok" or "unpack [error message]" but received "".", success: false}

**Comment by lonelyuan** [comment]
![image](https://user-images.githubusercontent.com/44459536/140289131-d10eb9c6-7ddc-4822-97a6-1a563e0f3645.png)
![image](https://user-images.githubusercontent.com/44459536/140289094-331e7843-50da-4d4c-b3c5-fcd561d89041.png)

新安装包又同步不了了，v2ray的日志怎么显示在连接netlify？我明明是pages。。。

**Comment by CALOS985** [comment]
> @voidint 你的报错是什么，可以提供一下截图吗？

widget.js:1 Failed to load resource: net::ERR_TIMED_OUT
楼主，请问这个报错怎么解决

**Comment by haoenz** [comment]
冲着使用方便来着，但是一直同步失败实在太劝退了…
试过clash开tun模式，成功了几次之后又不行了…
还是先退回hexo等作者修好代理再说吧orz

**Comment by ljd1995** [comment]
报这个错，app.bf0497ff.js:formatted:2144 Uncaught TypeError: Cannot read property 'success' of null
    at EventEmitter.<anonymous> (app.bf0497ff.js:formatted:2144)
    at Object.onceWrapper (events.js:291)
    at EventEmitter.emit (events.js:203)
    at Object.onMessage (init.ts:50)

**Comment by autolins** [comment]
![image](https://user-images.githubusercontent.com/59790319/143460245-0dcb8c3f-f5ee-430c-836d-c6d49bfb8144.png)

**Comment by dawn-cmd** [comment]
连接成功但是同步长时间无响应

**Comment by ClaireLind1** [comment]
win10系统，远程连接成功但是同步不成功。

**Comment by zxC0der** [comment]
win11 远程连接失败，同步失败 TIMEOUT

**Comment by PPPerryPan** [comment]
连接偶尔成功，但同步依然失败，代理软件也没有捕捉到Gridea走了代理。报错：read ECONNRESET

**Comment by gexiaya** [comment]
我基本跟上述情况一直，心态炸裂，折腾好几天了

**Comment by long-life233** [comment]
提示同步失败,但是打开网址是有内容的(第一次弄这个)

**Comment by wangzhichao1990** [comment]
成功过一次，再也不行了。

**Comment by BangwenHe** [comment]
> 成功过一次，再也不行了。 🙁 同步遇到了错误，请查阅 FAQ 或 Issues 来寻找解决方案

其实可以自己到Gridea的output文件夹去push到github的，这样就可以走自己设置的git的代理了。

**Comment by Ray-Lum** [comment]
![image](https://user-images.githubusercontent.com/51054841/147315258-dede0fc6-eae7-4a31-b96e-81786e5d76b3.png)
![image](https://user-images.githubusercontent.com/51054841/147315295-9cdc848b-e996-4e06-bbc3-1df0ad950db0.png)
使用了全局代理，梯子和令牌设置都是好的，但我还是搞不定……

**Comment by Guopop** [comment]
设置token的时候， 把除了repo其他也都选上就可以了。亲测有效
![image](https://user-images.githubusercontent.com/24852609/147403968-c76fc992-d3d4-4080-a09e-ba03408d723b.png)

**Comment by hwqDqwh** [comment]
![image](https://user-images.githubusercontent.com/21328533/147432190-5ca9ef2e-5fa8-4fd3-9551-8c78e57661c4.png)
看起来还是没用上系统代理，暂时只能手动推送 output 目录撑一下，期待解决

**Comment by gamesuchao** [comment]
![image](https://user-images.githubusercontent.com/77901052/147676857-d1739b0e-ceb7-4392-869b-57f7726bef6c.png)

**Comment by MarkDeia** [comment]
支持netlify的版本（23 Oct 2021）使用pages却请求netlify，导致连接异常。
不支持netlify的版本（09 Sep 2021）使用起来一切正常。

**Comment by aifact** [comment]
最后还是手动了，我试出了一种简单的方法是，把本地文件放本地云盘文件夹，先清空gridea的output文件夹，然后用git命令或git gui把github或其他远程git库，克隆到output，用空的sftp远程配置，仅填好部署的访问网址，点同步后，等待创建好新文件，然后自己用git或git gui客户端，如github desk同步，这时候用ssh，用安装的fastgithub程序，都很快，还能选择不提交部署站点的配置文件，半手动提交，本来都放弃了，现在很爽了，又开淦了

**Comment by kuraqi** [comment]
更新前（不支持netlify的版本）第一次设置的时候同步成功了，挂代理有可能成功。
于是更新了支持netlify的版本，更新了之后连远程连接都无法连接上了……无论挂不挂代理都无法，如图显示
![image](https://user-images.githubusercontent.com/96760852/147879956-69966c96-9e3b-4f3c-8032-bc4c172d297a.png)

**Comment by 39miku520** [comment]
`Uncaught TypeError: Cannot read property 'success' of null
    at EventEmitter.<anonymous> (app.bf0497ff.js:1)
    at Object.onceWrapper (events.js:291)
    at EventEmitter.emit (events.js:203)
    at Object.onMessage (init.ts:50)`

怎么回事啊

**Comment by 39miku520** [comment]
Uncaught TypeError: Cannot read property 'success' of null
    at EventEmitter.<anonymous> (app.bf0497ff.js:1)
    at Object.onceWrapper (events.js:291)
    at EventEmitter.emit (events.js:203)
    at Object.onMessage (init.ts:50)

怎么回事啊

**Comment by kelegele** [comment]
代理开好了，外网可以访问。
远程连接测试成功了。
但就是同步失败：
🙁 同步遇到了错误，请查阅 FAQ 或 Issues 来寻找解决方案

我先去push了，希望这个问题能够解决一下

**Comment by cunzher** [comment]
Netlify。远程连接失败。系统代理设置正常。代理开启或关闭均失败

**Comment by dgjj1991** [comment]
远程连接测试成功，然后点击同步失败，再次点击远程连接会失败提示配置或者令牌错误。然后关闭软件重启，远程连接成功，然后点击同步循环

**Comment by RowanWang6** [comment]
更换了自定义网站图标之后，远程连接成功，但是点同步后就一直转圈。我盯着看好久，最后跳了一个同步成功，但是根本没成功。 console没有报错。

**Comment by dgjj1991** [comment]
> 更换了自定义网站图标之后，远程连接成功，但是点同步后就一直转圈。我盯着看好久，最后跳了一个同步成功，但是根本没成功。 console没有报错。

亲测这个方法有效https://sonatta.top/post/Ux6xKOeOx/

**Comment by Lzh2665692** [comment]
> > @voidint 你的报错是什么，可以提供一下截图吗？
> 
> 怎么看报错信息？有日志吗？点击`同步`按钮后就开始loading，没任何响应，看不到任何错误信息。

解决方法：[https://pdssyzfz.tk/post/gridea-tong-bu-shi-bai-shi-dai-li-wen-ti/](url)

> ![image](https://user-images.githubusercontent.com/21328533/147432190-5ca9ef2e-5fa8-4fd3-9551-8c78e57661c4.png) 看起来还是没用上系统代理，暂时只能手动推送 output 目录撑一下，期待解决

解决方法：[https://pdssyzfz.tk/post/gridea-tong-bu-shi-bai-shi-dai-li-wen-ti/](url)

**Comment by qingee** [comment]
选择GitHub进行远程检测和同步都是请求的Netlify，并没有请求GitHub

**Comment by EryouHao** [comment]
最新的 v0.9.3 版本已经支持部署 Netlify 和设置代理，有同步问题的朋友可以试试哈
