### ISSUE TITLE
同步遇到一点问题

### ISSUE THREAD

**Issue by jm0820** [getgridea/gridea#892]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |    mac  |
| 软件版本 |   0.9.2   |
| 主题名称 |    Notes  |

## 期望行为

  同步成功

## 当前行为

同步不成功，打开开发者工具显示以下信息
  connect ETIMEDOUT 20.205.243.166:443".

**Comment by PPPerryPan** [comment]
> 问题主要原因是github需要翻墙才能同步成功，所以电脑需要走全局代理可以解决这个问题，具体过程可参看[这里](https://www.luoyelusheng.com/post/Gridea%E5%90%8C%E6%AD%A5github%E5%A4%B1%E8%B4%A5%E6%9C%80%E7%BB%88%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88/)

并不行，Windows这边Gridea不会走代理，即使配置了代理服务器也没用，Gridea依然直连，软件内也没有配置代理服务器的选项。

**Comment by makabakalalala** [comment]
最后同步成功了吗

**Comment by EryouHao** [comment]
可以试试 v0.9.3 版本哈，解决了同步问题，和支持了设置代理。
