### ISSUE TITLE
feat: 可以考虑用ssh连接GitHub

### ISSUE THREAD

**Issue by sjh0020** [getgridea/gridea#899]
## 概述

如标题所示

## 动机

看到目前的解决想法是用系统代理，于是像给出用ssh的建议

## 详细解释

ssh可以直接和GitHub通讯，而不用经过代理

## 有个问题

我想把博客放到`user.github.io/bolg`该怎么做，完成同步

目前因为网络问题都是手动把output文件夹内容拖到user.github.io下的blog文件夹，然后在上级目录用git提交

如果不行能否自定义output文件夹位置及名称

**Comment by luoyelusheng** [comment]
还可以这样啊，但是gridea点击同步才会打包生产环境，然后再去output目录提交，感觉还是有点麻烦，但是如果软件首次配置好的话，只要后台默认开着，直接点同步就行（还是太懒了，逃...）

**Comment by aifact** [comment]
简单的方法是，清空output，然后用git命令或git gui把github或其他远程git库，克隆到output，用空的sftp远程配置，仅填好部署网址，点同步后创建文件后，然后自己用git或git gui同步，还能用fastgithub，很快

**Comment by EryouHao** [comment]
v0.9.3 版本支持设置代理了哈，可以试试
