### ISSUE TITLE
RSS 是否会支持

### ISSUE THREAD

**Issue by jcw01** [getgridea/gridea#90]
对于软件内部直接支持rss 订阅源的导出，这个功能会支持嚒，这个可能是刚需！

**Comment by EryouHao** [comment]
下个版本，敬请期待

**Comment by jcw01** [comment]
哈哈哈，很期待了

Lapsy
热爱数码&互联网
如果批评不自由，则赞美无意义

**Comment by EryouHao** [comment]
已增加 [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)

**Comment by jcw01** [comment]
你好，开发者，我想咨询一下RSS 在主题哪里添加 href="<%= themeConfig.domain %>/atom.xml" 在哪里添加


 






在 2019-05-26 16:32:56，"fehey" <notifications@github.com> 写道：


已增加 v0.8.1
