### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by huangyinhaow** [getgridea/gridea#910]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |   Win11   |
| 软件版本 |   0.92   |
| 主题名称 |   无   |

---

## 期望行为

连接成功

## 当前行为
![image](https://user-images.githubusercontent.com/64564727/137609981-83993269-2da4-4f74-b18e-103f81d283f0.png)
多次尝试无效

**Comment by SuenChi** [comment]
![image](https://user-images.githubusercontent.com/60096484/144011737-be7e5812-f518-4a4c-9a3e-682aab1a3bb8.png)
wo'd
我的问题和你一样

**Comment by UIE-z** [comment]
i have the same problem

**Comment by Runnerxr** [comment]
我的问题和你一样

**Comment by TheCedar** [comment]
I have the same problem+1

**Comment by yiwp9** [comment]
+1

**Comment by YiLeiNaQAQ** [comment]
+1

**Comment by SuenChi** [comment]
HR你好，感谢您对本人能力的认可，在与贵公司面谈的过程中，你们表现地相当出色，贵公司丰富的企业文化和诚恳态度给我留下了深刻印象。但综合各方面的因素，很遗憾地通知您，贵公司未通过本人的企业筛选，现已纳入本人的企业备选池，如以后有合适的合作机会，我将及时与贵公司取得联系。希望贵公司能理解我的决定，期待有机会再谋求共同发展。也希望贵公司不要气馁，继续努力！祝贵公司业务顺利，前途景气！

**Comment by oldhelps** [comment]
软件版本：0.9.3
win11
无法连接

**Comment by SuenChi** [comment]
HR你好，感谢您对本人能力的认可，在与贵公司面谈的过程中，你们表现地相当出色，贵公司丰富的企业文化和诚恳态度给我留下了深刻印象。但综合各方面的因素，很遗憾地通知您，贵公司未通过本人的企业筛选，现已纳入本人的企业备选池，如以后有合适的合作机会，我将及时与贵公司取得联系。希望贵公司能理解我的决定，期待有机会再谋求共同发展。也希望贵公司不要气馁，继续努力！祝贵公司业务顺利，前途景气！

**Comment by huangyinhaow** [comment]
解决方法：
- 关闭本地反代
- 开启代理

**Comment by WangMingxuan313** [comment]
+1

**Comment by SuenChi** [comment]
HR你好，感谢您对本人能力的认可，在与贵公司面谈的过程中，你们表现地相当出色，贵公司丰富的企业文化和诚恳态度给我留下了深刻印象。但综合各方面的因素，很遗憾地通知您，贵公司未通过本人的企业筛选，现已纳入本人的企业备选池，如以后有合适的合作机会，我将及时与贵公司取得联系。希望贵公司能理解我的决定，期待有机会再谋求共同发展。也希望贵公司不要气馁，继续努力！祝贵公司业务顺利，前途景气！

**Comment by haizihhh** [comment]
> 解决方法：
> 
> * 关闭本地反代
> * 开启代理

怎么弄能详细点吗

**Comment by SuenChi** [comment]
HR你好，感谢您对本人能力的认可，在与贵公司面谈的过程中，你们表现地相当出色，贵公司丰富的企业文化和诚恳态度给我留下了深刻印象。但综合各方面的因素，很遗憾地通知您，贵公司未通过本人的企业筛选，现已纳入本人的企业备选池，如以后有合适的合作机会，我将及时与贵公司取得联系。希望贵公司能理解我的决定，期待有机会再谋求共同发展。也希望贵公司不要气馁，继续努力！祝贵公司业务顺利，前途景气！

**Comment by anwangAC** [comment]
> > 解决方法：
> > 
> > * 关闭本地反代
> > * 开启代理
> 
> 怎么弄能详细点吗

就是说不开steamcommunity_302或加速器，如果关了再试还是没用，那么就用全局科学上网（ 木弟             子）
