### ISSUE TITLE
第一次同步完，网页刷新，内容不变

### ISSUE THREAD

**Issue by lshywwl** [getgridea/gridea#917]
仓库域名网页内还是readme的内容

**Comment by gd1214b** [comment]
gridea点完同步之后在GitHub desktop上能看到更改吗？

**Comment by lshywwl** [comment]
额 我没用desktop

**Comment by gd1214b** [comment]
那你还是按照我这个教程操作一下吧：
<https://blog.gd1214b.icu/post/F2_C5EVQh/>

**Comment by lshywwl** [comment]
![Uploading 1637576893(1).png…]()

**Comment by lshywwl** [comment]
![1637576893(1)](https://user-images.githubusercontent.com/47691816/142845685-369e2aac-2f45-4e31-84cd-2dcd282d0aad.png)

**Comment by lshywwl** [comment]
同步完就变成这样了

**Comment by lshywwl** [comment]
已解决，分支填main就行了
