### ISSUE TITLE
在 paper 主题下最新文章列表会显示隐藏的文章

### ISSUE THREAD

**Issue by xxxuuu** [getgridea/gridea#92]
在主页的时候是正常的：

![image](https://user-images.githubusercontent.com/31284445/57191600-0568ba00-6f5a-11e9-9936-5219d3202135.png)

但点进任意一篇文章后，在最新文章列表就可以看到「点分治」这篇隐藏文章了：
![image](https://user-images.githubusercontent.com/31284445/57191647-7e681180-6f5a-11e9-83c5-b6d7745920bb.png)

**Comment by EryouHao** [comment]
fixed [v0.8.1](https://github.com/getgridea/gridea/releases/tag/v0.8.1)
