### ISSUE TITLE
feat: 每次构建时不要删除额外的文件夹

### ISSUE THREAD

**Issue by haoenz** [getgridea/gridea#926]
有时候会在repo里上传一些纯文本的代码文件，然后在文章里引用。
比如我会在uploads/里上传了uploads/test.py
然后再post的文章里用相对路径../uploads/test.py来引用
可是gridea每次生成网站时都会把uploads/文件夹删掉

**Comment by EryouHao** [comment]
在static 文件夹里放就可以了。
