### ISSUE TITLE
同步成功但是网页无内容

### ISSUE THREAD

**Issue by 2jduead** [getgridea/gridea#927]
windows客户端同步成功，但网页不显示内容，只显示一个域名
![屏幕截图 2021-12-15 172234](https://user-images.githubusercontent.com/68358308/146159166-1643ab3c-56d3-4e51-8152-d69da2f3cf75.png)

**Comment by rangercyh** [comment]
我也遇到一样的问题，看调试估计是 https://cdn.jsdelivr.net 挂了

**Comment by aifact** [comment]
> 我也遇到一样的问题，看调试估计是 https://cdn.jsdelivr.net 挂了

是的，最近jsdelivr挂了

**Comment by cooronx** [comment]
为什么我还是没好，还挂着的吗？

**Comment by aifact** [comment]
> 为什么我还是没好，还挂着的吗？
好像彻底歇菜了，
建议用netlify部署, 参考 <https://navdoc.super.site>

**Comment by aifact** [comment]
> 为什么我还是没好，还挂着的吗？
好像是彻底歇菜了？

**Comment by im-smuze** [comment]
你可能同步到mater分支了，github默认是main

**Comment by EryouHao** [comment]
我看楼主已经同步成功，且网页可访问了，先关了。
