### ISSUE TITLE
coding已经不在提供 网站托管/静态网站 服务了？

### ISSUE THREAD

**Issue by TailendWong** [getgridea/gridea#956]
我没找到，貌似已经不提供了。。。，知道的大佬能否告知是否coding确实不支持了。

参考链接https://blog.csdn.net/qq_23858785/article/details/123104823

希望除了github，能添加对gitee的支持。

**Comment by xiyuvi** [comment]
coding已经转收费了，gitee不支持自定义域名

**Comment by TailendWong** [comment]
> coding已经转收费了，gitee不支持自定义域名

感谢大佬解答
