### ISSUE TITLE
标签样式问题

### ISSUE THREAD

**Issue by BoWang816** [getgridea/gridea#97]
![image](https://user-images.githubusercontent.com/26587649/57294244-97f38f80-70f9-11e9-952a-8a391d7daca9.png)

不知道为何会这样，但是开发版跑的时候是正常的

**Comment by Suremotoo** [comment]
这个问题已经解决，但是要等下一个版本哦（很快推出），耐心等待😝😝。https://github.com/getgridea/gridea/pull/86#issue-275909452

**Comment by BoWang816** [comment]
好的！等待更新！
