### ISSUE TITLE
Mac 0.9.2版本的 Gridea 找不到 Netlify 部署的渠道

### ISSUE THREAD

**Issue by mophia** [getgridea/gridea#972]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/92929085/163979927-62cc826a-0246-42fd-b560-b311b5690c69.png">

您好，Mac 0.9.2版本的 Gridea 找不到官网 https://gridea.dev/netlify/ 说的 Netlify 部署的渠道。请问方便告知一下吗？多谢您！

**Comment by wherelse** [comment]
置顶issue第一个就是
https://github.com/getgridea/gridea/issues/890#issue-991858862

**Comment by EryouHao** [comment]
之前只发了测试包，最新的0.9.3 版本已经支持。
