### ISSUE TITLE
关于连接成功同步失败

### ISSUE THREAD

**Issue by zerobiubiu** [getgridea/gridea#975]
# 第一步

先把远程信息写好，最好挂上代理，检测远程连接，通了才能进行下一步

# 第二步

同步失败，报错"connect ETIMEDOUT"就是连不上
不过只要连接成功就行
原因可能是Git没有走代理，连接超时，只要去关了Git的代理，让他去走系统代理

```git
git config --global --unset http.proxy
git config --global --unset https.proxy 
```

如果还不行，就用土方法，自己手动传output吧

**Comment by EryouHao** [comment]
0.9.3 已增加代理设置
