### ISSUE TITLE
为什么会有这种间距问题？该怎么调？

### ISSUE THREAD

**Issue by Chainguys** [getgridea/gridea#977]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/6762674/167157274-266725c4-abd0-4878-a419-314abd3c6624.png">

补充：用了NexT主题。

**Comment by wherelse** [comment]
应该是输入法半角全角的问题，最好自己检查一下md的内容

**Comment by Chainguys** [comment]
Meanwhile, Seraphim was interviewed in [eFinancialCareers](https://twitter.com/eulerfinance/status/1510091127336013824) and will be attending [Devconnect](https://twitter.com/CryptoCanal/status/1511041954624286727) in Amsterdam on 25th April.

没问题啊你看

**Comment by Chainguys** [comment]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/6762674/167160116-e37cc82e-4ed3-4b37-8bce-45bb7774d3d1.png">
泥马 甚至预览都没有问题。。。

**Comment by wherelse** [comment]
尝试在尾部或者下一行的第一个单词后添加空格，可能是两端对齐导致的

**Comment by Chainguys** [comment]
> 尝试在尾部或者下一行的第一个单词后添加空格，可能是两端对齐导致的

有没有办法改默认对齐方式。。。

**Comment by EryouHao** [comment]
@Chainguys 建议可以去 NextT 主题仓库提 issue 问下哈，感谢。通常都是可以通过自定义 CSS 来解决的。但是需要知道对应的 class

https://github.com/hsxyhao/gridea-theme-next/issues
