### ISSUE TITLE
snap软件包安装后，第一次可以正常打开，退出后，再次点击图标没有反应，终端输入也没有任何输出

### ISSUE THREAD

**Issue by izumi-sora** [getgridea/gridea#992]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |debian      |
| 软件版本 |      11|
| 主题名称 |      gnome|

---

## 期望行为
点击图标打开gridea

## 当前行为
没有任何反映

**Comment by izumi-sora** [comment]
之前的92版本也不行，猜测是snap更新的关系

**Comment by izumi-sora** [comment]
izumi@debian:~/Documents$ gridea 
izumi@debian:~/Documents$

**Comment by izumi-sora** [comment]
izumi@debian:|~/Documents$ gridea 
izumi@debian:|~/Documents$

**Comment by izumi-sora** [comment]
izumi@debian:\~/Documents$ gridea 
izumi@debian:\~/Documents$

**Comment by EryouHao** [comment]
没有太测试过 linux 版本。如果感兴趣可以直接通过源码 watch 方式跑一下，然后看是否有什么报错

**Comment by izumi-sora** [comment]
https://www.addictivetips.com/ubuntu-linux-tips/install-appimages-linux/
之前嫌弃appimage要手动写桌面图标，发现解决方法
