### ISSUE TITLE
Bug: Gridea cannot connect to JSDeliver

### ISSUE THREAD

**Issue by hayato-blog** [getgridea/gridea#995]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  Ubuntu 20.04.4 LTS x86_64   |
| 软件版本 |   0.9.3   |
| 主题名称 |   暂无   |

---

## 期望行为

页面显示完好，无 Js 文件无法加载或加载超时等问题

## 当前行为

![image](https://user-images.githubusercontent.com/106329333/170523587-9ec4b583-d5ed-400b-9f53-6dddb0311007.png)

有关 JSDeliver 的文件都无法加载或加载过慢。

由于 JSDeliver 在国内的支持度大大降低，所以希望作者大大能够换到更多更加优秀、快速的 npm 源。比如 https://unpkg.com ，替换方面，格式未出现较明显的变化。

**Comment by renbaoshuo** [comment]
unpkg 在国内的连通性也不是很优秀吧...

可以考虑换到本地。

**Comment by hayato-blog** [comment]
> unpkg 在国内的连通性也不是很优秀吧...
> 
> 可以考虑换到本地。

非常感谢您的回答，看到您提的 PR 了。合并之后我会试试效果。

**Comment by GouGoBy** [comment]
> 事实上，目前被屏蔽的只有 cdn.jsdelivr.net ，简单把域名换成 fastly.jsdelivr.net 后可以很好解决问题，加载速度很快。 最近有些用了 jsDelivr 的主题也出现了这种问题，把域名替换成 fastly.jsdelivr.net 后就变得像以前一样快速响应了。

请问一下如何修改notes主题中引用remixicon.css的链接，谢谢

**Comment by zi-jing** [comment]
> > 事实上，目前被屏蔽的只有 cdn.jsdelivr.net ，简单把域名换成 fastly.jsdelivr.net 后可以很好解决问题，加载速度很快。 最近有些用了 jsDelivr 的主题也出现了这种问题，把域名替换成 fastly.jsdelivr.net 后就变得像以前一样快速响应了。
> 
> 请问一下如何修改notes主题中引用remixicon.css的链接，谢谢

![image](https://user-images.githubusercontent.com/44922707/172006307-e022c5d7-6514-4f00-a7cb-a0f1928756c0.png)

如图，把所有 cdn.jsdelivr.net 查找替换成 fastly.jsdelivr.net 即可
