### ISSUE TITLE
远程连接成功，点击同步之后一直转圈，点击预览也没有反应，关机重启都没有效果？？

### ISSUE THREAD

**Issue by lvzesen2001** [getgridea/gridea#998]
## 我的环境

| 名称     | 值   |
| ------- | ---- |
| 操作系统 |  win11    | 
| 软件版本 |  0.9.3   |
 | 主题名称 |   pure    |

---

## 期望行为 
点击同步，希望同步成功

## 当前行为

![image](https://user-images.githubusercontent.com/94974996/170871914-175db797-ee1c-4ec0-99fe-0b0dce59922e.png)
点击同步之后，一直转圈，没有反应，关机重启什么的都没有反映，检查远程连接是可以连接成功的
  你可以粘贴截图或附件。

**Comment by Liu-Jiming** [comment]
可以试试用 Proxifier

**Comment by Yirulol** [comment]
> 
Gridea基础配置处填写代理地址和端口吗？小白求教

**Comment by lvzesen2001** [comment]
> > 
> 
> Gridea基础配置处填写代理地址和端口吗？小白求教

地址填127.0.0.1，端口号我拿clash为例，一般都是7890

**Comment by Yirulol** [comment]
感谢解答！等下回到家试一试



| |
周益如
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月10日 21:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [getgridea/gridea] 远程连接成功，点击同步之后一直转圈，点击预览也没有反应，关机重启都没有效果？？ (Issue #998) |

Gridea基础配置处填写代理地址和端口吗？小白求教

地址填127.0.0.1，端口号我拿clash为例，一般都是7890

**Comment by Yirulol** [comment]
已解决，感谢各位大佬！

**Comment by lijiam13** [comment]
> > > 
> > 
> > 
> > Gridea基础配置处填写代理地址和端口吗？小白求教
> 
> 地址填127.0.0.1，端口号我拿clash为例，一般都是7890

是在哪里填写阿，基础配置里没有看到填写地址和端口号的选项
